opea-project/GenAIExamples

ChatQnA/langchain/docker/qna-app/app/server.py

Chat with history in /chat_stream restful api.
Local tested on Habana Gaudi2.

Support chat history for ChatQnA chat_stream

---

CONTRIBUTING.md
LEGAL_INFORMATION.md
LICENSE
README.md
third-party-programs.txt

Update additional content. 
- CONTRIBUTING.md
- LEGAL_INFORMATION.md
- LICENSE
- third-party-programs.txt

update additional content

---

.pre-commit-config.yaml
ChatQnA/langchain/docker/Dockerfile
ChatQnA/langchain/docker/requirements.txt

This pull request refactors the original langchain dockerfile to be based on Intel Optimized Pytorch base image

Refactoring to use Intel Optimized Pytorch

---

ChatQnA/langchain/docker/qna-app/app/NeuralChatEndpoint.py
ChatQnA/langchain/docker/qna-app/app/server.py
ChatQnA/langchain/docker/qna-app/app/utils.py

Local tested on Habana Gaudi.
NeuralChat service on SPR.

Support chatqna with NeuralChat endpoint

---

ChatQnA/README.md

This makes a few small edits to ChatQnA README.md. 
Only content change is removing the 1.8x performance claim for moving from bf16 to fp8 without citation to approved performance claim.

made small edits to ChatQnA README.md file

---

DocSum/ui/src/lib/doc.svelte

fix panelExchange logic

---

.github/workflows/ChatQnA.yml
.github/workflows/CodeGen.yml
.github/workflows/DocSum.yml
.github/workflows/SearchQnA.yml
.github/workflows/VisualQnA.yml

Update CI secrets access
Update CI secrets access
CI
no

Update CI secrets access

---

ChatQnA/langchain/docker/qna-app/app/server.py
ChatQnA/langchain/docker/qna-app/app/utils.py

bug fix
Fix ChatQnA streaming response issue
Local test and pre-CI test.
None.

Fix ChatQnA streaming response issue

---

ChatQnA/README.md
ChatQnA/langchain/docker/docker-compose.yml
ChatQnA/langchain/docker/qna-app/app/server.py
ChatQnA/langchain/redis/ingest.py
ChatQnA/langchain/redis/ingest_intel.py
ChatQnA/ui/.env

Feature/Bug fix
TEI_ENDPOINT was not being used in ingest files which is causing the RAG endpoint to fail while server.py is using the TEI_ENDPOINT.
Yes, Able to verify the ingest to insert the rows in DB and rag endpoint
NA

Added the logic in ingest python files to use the TEI_ENDPOINT to ingest the data into the redis vector DB

---

README.md

feature
Update README for CodeTrans
Just document refine
None.

Update README for CodeTrans

---

CodeTrans/README.md
CodeTrans/langchain/docker/build_docker.sh
CodeTrans/langchain/docker/codetrans-app/prompts.py
CodeTrans/langchain/docker/codetrans-app/server.py

bug fix
Modify prompt and streaming format of Code Translation
Local tested and integrated with frontend @WenjiaoYue .
None

[Code Translation] Modify prompt and streaming format

---

.github/workflows/scripts/codeScan/trellix.sh
.github/workflows/trellix.yml

validation
support scheduled trellix scan 
CI
trellix

support trellix scan

---

.github/workflows/trellix.yml

update trellix scan

---

.github/workflows/AudioQnA.yml

validation 
fix typo in CI workflow

fix typo in AudioQnA CI test

---

ChatQnA/microservice/gaudi/README.md
ChatQnA/microservice/gaudi/docker_compose.yaml
ChatQnA/microservice/xeon/README.md

bug fix
Fix ChatQnA microservice issues on Gaudi
Local test.
None.

Fix ChatQnA microservice issues on Gaudi

---

ChatQnA/microservice/gaudi/README.md
ChatQnA/microservice/gaudi/chatqna.py
ChatQnA/microservice/xeon/README.md
ChatQnA/microservice/xeon/chatqna.py

feature
Update ChatQnA Guadi microservice
Local test
None.

Update ChatQnA Guadi microservice

---

.github/workflows/ChatQnA_gaudi.yml
.github/workflows/ChatQnA_xeon.yml
ChatQnA/microservice/xeon/README.md
ChatQnA/tests/test_chatqna_on_gaudi.sh
ChatQnA/tests/test_chatqna_on_xeon.sh

validation 
- Fix readme
- Update ChatQnA Gaudi workflow
- Add ChatQnA Xeon workflow
CI
No

Add ChatQnA Xeon workflow

---

.github/workflows/ChatQnA_gaudi.yml
.github/workflows/ChatQnA_xeon.yml
ChatQnA/microservice/gaudi/README.md
ChatQnA/microservice/xeon/README.md
ChatQnA/tests/test_chatqna_on_gaudi.sh
ChatQnA/tests/test_chatqna_on_xeon.sh

bug fix
fix dockerfile path for rerank
CI
No

fix dockerfile path for rerank

---

ChatQnA/microservice/xeon/docker_compose.yaml

bug fix
Add TGI service env in Docker Compose
Local tested.
None

Add TGI service env in Docker Compose

---

ChatQnA/microservice/gaudi/README.md
ChatQnA/microservice/gaudi/chatqna.py
ChatQnA/microservice/gaudi/docker/Dockerfile
ChatQnA/microservice/xeon/README.md
ChatQnA/microservice/xeon/chatqna.py

feature
Support megaservice streaming output
Local test.
None

Support megaservice streaming output

---

.github/workflows/ChatQnA_xeon.yml
ChatQnA/microservice/gaudi/README.md
ChatQnA/tests/test_chatqna_on_gaudi.sh
ChatQnA/tests/test_chatqna_on_xeon.sh

validation
run megaservice in container
CI
No

run megaservice in container

---

.github/workflows/ChatQnA_gaudi.yml
.github/workflows/ChatQnA_xeon.yml
ChatQnA/microservice/gaudi/README.md
ChatQnA/microservice/gaudi/docker_compose.yaml
ChatQnA/tests/test_chatqna_on_gaudi.sh
ChatQnA/tests/test_chatqna_on_xeon.sh
CodeGen/tests/test_codegen_inference.sh

check CI issues

---

.github/workflows/CodeGen_gaudi.yml
.github/workflows/CodeGen_xeon.yml

Update CodeGen workflow for the microservice 
n/a
Update CodeGen workflow for the microservice 
Those workflow yaml work for CodeGen CI.

update CodeGen workflow for the microservice 

---

CodeGen/tests/test_codegen_on_gaudi.sh
CodeGen/tests/test_codegen_on_xeon.sh

expand CodeGen service waiting time in CI
n/a
n/a
CI

expand CodeGen service waiting time in CI

---

DocSum/ui/svelte/.env
DocSum/ui/svelte/src/lib/shared/Network.ts
DocSum/ui/svelte/vite.config.ts

Adapting the backend to the new structure
n/a
- [√ ] Breaking change (fix or feature that would break existing design and interface)
no
npm run dev

Adapting the backend to the new structure

---

.github/workflows/CodeTrans_gaudi.yml
.github/workflows/CodeTrans_xeon.yml
.github/workflows/DocSum_gaudi.yml
.github/workflows/DocSum_xeon.yml
ChatQnA/tests/test_chatqna_on_gaudi.sh
ChatQnA/tests/test_chatqna_on_xeon.sh

Add log collect for CI for debug purpose 
n/a
validation  
Add log collect for CI for debug purpose 

Add log collect for CI

---

README.md

Update HW support in README
`n/a`
None
Just document change.

Update HW support in README

---

.github/workflows/container-build.yml
.github/workflows/docker/docker-compose.yaml

Remove the label in docker image tag, for internal ci to pull the latest docker image.
n/a
Remove the label in docker image tag, for internal ci to pull the latest docker image.
Action

remove the job id for internal docker image build

---

CodeGen/ui/svelte/src/lib/doc.svelte

Change file name case
`n/a`.
no
npm run build pass.

Change file name case

---

CodeTrans/ui/svelte/package.json

fix codeTrans build fail
`n/a`.
no
build pass

update codeTrans package.json

---

ChatQnA/chatqna.yaml
ChatQnA/docker-composer/gaudi/README.md
ChatQnA/docker-composer/gaudi/docker_compose.yaml
ChatQnA/docker-composer/xeon/README.md
ChatQnA/docker-composer/xeon/docker_compose.yaml
ChatQnA/tests/test_chatqna_on_gaudi.sh
ChatQnA/tests/test_chatqna_on_xeon.sh
CodeGen/codegen.yaml
CodeGen/docker-composer/gaudi/README.md
CodeGen/docker-composer/gaudi/docker_compose.yaml
CodeGen/docker-composer/xeon/README.md
CodeGen/docker-composer/xeon/docker_compose.yaml
CodeGen/tests/test_codegen_on_gaudi.sh
CodeGen/tests/test_codegen_on_xeon.sh
CodeTrans/codetrans.yaml
CodeTrans/docker-composer/gaudi/README.md
CodeTrans/docker-composer/gaudi/docker_compose.yaml
CodeTrans/docker-composer/xeon/README.md
CodeTrans/docker-composer/xeon/docker_compose.yaml
CodeTrans/tests/test_codetrans_on_gaudi.sh
CodeTrans/tests/test_codetrans_on_xeon.sh
DocSum/docker-composer/gaudi/README.md
DocSum/docker-composer/gaudi/docker_compose.yaml
DocSum/docker-composer/xeon/README.md
DocSum/docker-composer/xeon/docker_compose.yaml
DocSum/docsum.yaml
DocSum/tests/test_docsum_on_gaudi.sh
DocSum/tests/test_docsum_on_xeon.sh

Format opea docker images name
`n/a`
None

Format opea docker images name

---

.github/workflows/E2E_test_with_compose.yml

fix checkout in CI for pull_request_target
n/a
No
CI

fix checkout in CI for pull_request_target

---

ChatQnA/tests/test_chatqna_on_gaudi.sh

fix typo in test scripts
n/a
No change
CI

fix typo in test scripts

---

DocSum/README.md
DocSum/docker-composer/gaudi/README.md
DocSum/docker-composer/xeon/README.md

DocSum example doc review update 

---

CodeGen/README.md
CodeGen/kubernetes/manifests/README.md
CodeGen/kubernetes/manifests/gaudi/codegen.yaml
CodeGen/kubernetes/manifests/xeon/codegen.yaml

kubernetes deployment support for CodeGen

Manifests to deploy CodeGen into Kubernetes

---

ChatQnA/README.md
ChatQnA/docker-composer/gaudi/README.md

[DOC] update ChatQnA README

---

CodeGen/README.md
CodeGen/docker-composer/gaudi/README.md
CodeGen/docker-composer/xeon/README.md

Refine 3 docs including CodeGen application overview, CodeGen Gaudi deployment and CodeGen Xeon deployment.
Refine the readme.

Refine the CodeGen App Readme

---

ChatQnA/kubernetes/manifests/chaqna-xeon-backend-server.yaml
ChatQnA/kubernetes/manifests/embedding.yaml
ChatQnA/kubernetes/manifests/llm.yaml
ChatQnA/kubernetes/manifests/qna_configmap_gaudi.yaml
ChatQnA/kubernetes/manifests/qna_configmap_xeon.yaml
ChatQnA/kubernetes/manifests/reranking.yaml
ChatQnA/kubernetes/manifests/retriever.yaml
ChatQnA/kubernetes/manifests/tei_embedding_gaudi_service.yaml
ChatQnA/kubernetes/manifests/tei_embedding_service.yaml
ChatQnA/kubernetes/manifests/tei_reranking_service.yaml
ChatQnA/kubernetes/manifests/tgi_gaudi_service.yaml
ChatQnA/kubernetes/manifests/tgi_service.yaml

Improve ChatQnA manifests
Remove default namespace setting to allow users to set a namespace
n/a
n/a
n/a

Improve ChatQnA manifests

---

.github/workflows/manifest-validate.yaml

Add manifest validation test to CI
n/a
n/a
n/a

Add manifest validation test to CI

---

ChatQnA/docker-composer/gaudi/README.md
ChatQnA/docker-composer/xeon/README.md
ChatQnA/kubernetes/manifests/README.md
ChatQnA/tests/test_chatqna_on_gaudi.sh
ChatQnA/tests/test_chatqna_on_xeon.sh
CodeGen/docker-composer/gaudi/README.md
CodeGen/docker-composer/xeon/README.md
CodeGen/tests/test_codegen_on_gaudi.sh
CodeGen/tests/test_codegen_on_xeon.sh
DocSum/docker-composer/gaudi/README.md
DocSum/docker-composer/xeon/README.md
DocSum/tests/test_docsum_on_gaudi.sh
DocSum/tests/test_docsum_on_xeon.sh

Remove model info in curl request
`n/a`
None.
Local test.

Remove model info in curl request

---

ChatQnA/docker-composer/gaudi/docker_compose.yaml
ChatQnA/docker-composer/xeon/README.md
ChatQnA/docker-composer/xeon/docker_compose.yaml
ChatQnA/tests/test_chatqna_on_gaudi.sh
ChatQnA/tests/test_chatqna_on_xeon.sh

Add environment variables for dataprep microService of the ChatQnA example.
`n/a`
`n/a`
PreCI

Add Environment Variable for dataprep MicroService of ChatQnA

---

CodeTrans/README.md
CodeTrans/docker-composer/gaudi/README.md
CodeTrans/docker-composer/xeon/README.md
CodeTrans/ui/svelte/README.md

fix grammar errors
fix grammar errors

Fix code trans

---

ChatQnA/docker/gaudi/README.md
ChatQnA/docker/xeon/README.md
CodeGen/docker/gaudi/README.md
CodeGen/docker/xeon/README.md
CodeTrans/docker/gaudi/README.md
CodeTrans/docker/xeon/README.md
DocSum/docker/gaudi/README.md
DocSum/docker/xeon/README.md

Dockerfile is under ..QnA/docker/
n/a
None
None

fix readme issue

---

ChatQnA/README.md
CodeGen/README.md
CodeTrans/README.md
DocSum/README.md

Fix README link issue
`n/a`
None
Just document change.

Fix README link issue

---

.github/workflows/manifest-e2e.yaml
ChatQnA/tests/test_manifest_on_xeon.sh
CodeGen/tests/test_manifest_on_xeon.sh

Enable manifest integration test in CI
n/a
n/a
n/a

Enable manifest integration test in CI

---

.github/workflows/E2E_test_with_compose.yml
ChatQnA/tests/test_chatqna_on_gaudi.sh
ChatQnA/tests/test_chatqna_on_xeon.sh

When several PR use the same test node, the test slow down, so expand test timeout. 
`n/a`.

expand CI timeout

---

CodeTrans/docker/ui/svelte/.env
CodeTrans/docker/ui/svelte/package.json
CodeTrans/docker/ui/svelte/playwright.config.ts
CodeTrans/docker/ui/svelte/src/lib/shared/Network.ts
CodeTrans/docker/ui/svelte/src/routes/+page.svelte
CodeTrans/docker/ui/svelte/tests/codeTrans.spec.ts

Add codeTrans front_end UT
`n/a`.
no
CI pass

Add codeTrans front_end UT

---

DocSum/docker/ui/svelte/.env
DocSum/docker/ui/svelte/package.json
DocSum/docker/ui/svelte/playwright.config.ts
DocSum/docker/ui/svelte/src/lib/doc.svelte
DocSum/docker/ui/svelte/src/lib/shared/Network.ts
DocSum/docker/ui/svelte/src/lib/summary.svelte
DocSum/docker/ui/svelte/tests/docSum.spec.ts

Update docSum ut
`n/a`.
no
CI pass

Update docSum ut

---

CODE_OF_CONDUCT.md
LEGAL_INFORMATION.md
README.md
SECURITY.md

bump release version into v0.6   
update security claim docs   
the security claim docs update request by ospdt

bump release version into v0.6

---

CodeGen/tests/test_codegen_on_gaudi.sh
CodeGen/tests/test_codegen_on_xeon.sh

Refine CodeGen test scripts.
Check http response status code==200.
Check the response content and save into corresponding log files.
n/a
None
CI test

Refine CodeGen Test Scripts

---

CodeGen/docker/codegen.py
CodeGen/docker/gaudi/README.md
CodeGen/docker/gaudi/docker_compose.yaml
CodeGen/docker/xeon/README.md
CodeGen/docker/xeon/docker_compose.yaml
CodeGen/kubernetes/manifests/README.md
CodeGen/kubernetes/manifests/gaudi/codegen.yaml
CodeGen/kubernetes/manifests/xeon/codegen.yaml
CodeGen/tests/test_codegen_on_gaudi.sh
CodeGen/tests/test_codegen_on_xeon.sh

Modify UI port for CodeGen to Avoid unsafe_port Issue.
`n/a`
`n/a`
`n/a`

Modify UI Port for CodeGen to Avoid unsafe_port Issue

---

.github/workflows/bum_list_check.yml

check requirement.txt package list
detail description
CI
No

Add check requirements workflow

---

README.md

Add support Qwen2
`n/a`
- [ x ] Bug fix (non-breaking change which fixes an issue)
None.
Just document change.

Add support Qwen2

---

ChatQnA/docker/xeon/README.md

Fix path in README

---

.github/workflows/E2E_test_with_compose.yml
.github/workflows/manifest-e2e.yaml
ChatQnA/tests/test_manifest_on_xeon.sh
CodeGen/tests/test_manifest_on_xeon.sh

Enable new CI runner and improve manifest e2e test scripts
n/a
n/a
CI e2e tests

Enable new CI runner and improve manifest e2e test scripts

---

CodeGen/docker/xeon/README.md

Fixed incorrect `cd` command and some typos in README.
N/A
N/A
N/A
N/A

[Docs] Fixed incorrect `cd` command in README

---

ChatQnA/docker/gaudi/README.md
ChatQnA/docker/xeon/README.md
ChatQnA/kubernetes/manifests/README.md

Updated the readme for chatqna with path fix and added cd instructions for reproducibility. 
PR # 231 and 232
N/A

Updated ReadMe for ChatQnA

---

ChatQnA/docker/gaudi/README.md
ChatQnA/docker/xeon/README.md
ChatQnA/kubernetes/manifests/README.md
CodeGen/docker/gaudi/README.md
CodeGen/docker/xeon/README.md
CodeTrans/docker/gaudi/README.md
CodeTrans/docker/xeon/README.md
DocSum/docker/gaudi/README.md
DocSum/docker/xeon/README.md

Fix a repeated path error in the documentation.
fixes #231 
fixes #232 
These PRs partially address the path errors and could be rebased on top of this PR.
#255 #257 #259 
n/a
CI

Fix docker paths in examples

---

.github/workflows/bum_list_check.yml

remove exit statement in bum_list_check

---

CodeTrans/docker/gaudi/README.md

fix docker build issues and add UI section
N/A (JIRA Gen-2)
NA
Test on IDC Gaudi2 VM instance

[CodeTrans]Update README.md for docker build issue and UI

---

ChatQnA/docker/chatqna.py
CodeGen/docker/codegen.py
CodeTrans/docker/code_translation.py
DocSum/docker/docsum.py

The scheduling should be called in the gateway. Remove it since single run in the main is useless here.
n/a
None
Local test

Remove useless scheduling statements

---

.github/workflows/image-build.yaml
.github/workflows/manifest-e2e.yaml
.github/workflows/scripts/build_push.sh
ChatQnA/tests/test_manifest_on_xeon.sh
CodeGen/tests/test_manifest_on_xeon.sh

Add docker build job in manifest e2e workflow
n/a
n/a
CI test

Add docker build job in manifest e2e workflow

---

.github/workflows/docker-compose-e2e.yml
.github/workflows/manifest-e2e.yml
.github/workflows/reuse-get-test-matrix.yml
.github/workflows/reuse-image-build.yml
.github/workflows/scripts/build_push.sh
ChatQnA/tests/test_chatqna_on_xeon.sh
CodeGen/tests/test_codegen_on_xeon.sh
CodeTrans/tests/test_codetrans_on_xeon.sh
DocSum/tests/test_docsum_on_xeon.sh

Add image build job in docker compose e2e xeon test in CI
n/a
n/a
CI tests

Add image build job in docker compose e2e xeon test in CI

---

.github/workflows/reuse-image-build.yml

update the image build refer in CI workflow

update the image build refer in CI workflow

---

.github/workflows/manifest-e2e.yml
.github/workflows/scripts/build_push.sh
ChatQnA/tests/test_chatqna_on_gaudi.sh
ChatQnA/tests/test_manifest_on_gaudi.sh
CodeGen/tests/test_codegen_on_gaudi.sh
CodeGen/tests/test_manifest_on_gaudi.sh
CodeTrans/tests/test_codetrans_on_gaudi.sh
DocSum/tests/test_docsum_on_gaudi.sh

Add image build job in docker compose e2e gaudi test in CI
n/a
n/a
CI tests

Add image build job in docker compose e2e gaudi test in CI

---

.github/workflows/docker-compose-e2e.yml
.github/workflows/manifest-e2e.yml
.github/workflows/reuse-image-build.yml
.github/workflows/scripts/build_push.sh
ChatQnA/tests/test_chatqna_on_gaudi.sh
ChatQnA/tests/test_chatqna_on_xeon.sh
ChatQnA/tests/test_manifest_on_gaudi.sh
CodeGen/tests/test_codegen_on_gaudi.sh
CodeGen/tests/test_codegen_on_xeon.sh
CodeTrans/tests/test_codetrans_on_gaudi.sh
CodeTrans/tests/test_codetrans_on_xeon.sh
DocSum/tests/test_docsum_on_gaudi.sh
DocSum/tests/test_docsum_on_xeon.sh

Add build docker image option for test scripts

Add build docker image option for test scripts

---

.github/workflows/docker-compose-e2e.yml

add env for searchqna ci test

---

ChatQnA/docker/ui/svelte/src/routes/+page.svelte

Adapt Chinese characters. Binary cannot automatically summon Chinese characters.
`n/a`.
no
CI pass.

Adapt Chinese characters

---

README.md

add LlamaIndex for readme
`n/a`.

add LlamaIndex for readme

---

README.md

add LlamaIndex to readme

---

CodeGen/kubernetes/codegen_gaudi.yaml
CodeGen/kubernetes/codegen_xeon.yaml
CodeGen/tests/test_gmc_on_gaudi.sh
CodeGen/tests/test_gmc_on_xeon.sh

Add codegen e2e test of GenAIExample.
`n/a`.
`n/a`.
`n/a`.

Add codegen e2e test of genaiexample

---

AudioQnA/deprecated/docker/tts/tts_server.py

Fix minor codescan issue
https://github.com/opea-project/GenAIExamples/issues/328
None
None

Fix minor codescan issue

---

ChatQnA/kubernetes/manifests/README.md

Signed-off-by: mkbhanda <malini.bhandaru@intel.com>

chatqna kubernetes readme.

---

.github/workflows/reuse-get-test-matrix.yml
AudioQnA/tests/test_audioqna_on_gaudi.sh
AudioQnA/tests/test_audioqna_on_xeon.sh
ChatQnA/tests/test_chatqna_on_gaudi.sh
ChatQnA/tests/test_chatqna_on_xeon.sh
CodeGen/tests/test_codegen_on_gaudi.sh
CodeGen/tests/test_codegen_on_xeon.sh
CodeTrans/tests/test_codetrans_on_gaudi.sh
CodeTrans/tests/test_codetrans_on_xeon.sh
DocSum/tests/test_docsum_on_gaudi.sh
DocSum/tests/test_docsum_on_xeon.sh
SearchQnA/tests/test_searchqna_on_gaudi.sh
SearchQnA/tests/test_searchqna_on_xeon.sh
Translation/tests/test_translation_on_gaudi.sh
Translation/tests/test_translation_on_xeon.sh

solution for the conda-forge not available issue

solution for the conda-forge not available issue 

---

.github/workflows/gmc-e2e.yaml
.github/workflows/manifest-e2e.yml
ChatQnA/kubernetes/manifests/docsum_gaudi_llm.yaml
ChatQnA/kubernetes/manifests/docsum_llm.yaml
ChatQnA/tests/test_gmc_on_gaudi.sh
ChatQnA/tests/test_gmc_on_xeon.sh
CodeGen/tests/test_gmc_on_gaudi.sh
CodeGen/tests/test_gmc_on_xeon.sh
CodeTrans/tests/test_gmc_on_gaudi.sh
CodeTrans/tests/test_gmc_on_xeon.sh
DocSum/kubernetes/docsum_gaudi.yaml
DocSum/kubernetes/docsum_xeon.yaml
DocSum/tests/test_gmc_on_gaudi.sh
DocSum/tests/test_gmc_on_xeon.sh

add docsum example e2e test for GMC.
`n/a`.
`n/a`.
It's e2e test.

add docsum example e2e test for GMC.

---

.github/workflows/image-build-on-push.yml
.github/workflows/scripts/build_push.sh

Enable image build on Gaudi when push event
n/a
n/a
CI workflow.
Verified in this action: https://github.com/opea-project/GenAIExamples/actions/runs/9737860208

Enable image build on Gaudi when push event

---

ChatQnA/tests/test_chatqna_on_gaudi.sh

chatqna frontend test failed with unknown timeout issue, but local test passed, so omit the test in CI first, and will be fixed in another PR. @WenjiaoYue  
first found https://github.com/opea-project/GenAIExamples/pull/334 

chatqna frontend test failed with unknown timeout issue

---

CodeTrans/tests/test_gmc_on_gaudi.sh
CodeTrans/tests/test_gmc_on_xeon.sh

Improve the example of  `codetrans` e2e test.
There are something incorrect with the example of `codetrans` e2e test.
`n/a`.
`n/a`.
**e2e for example of codetrans**

Enhancement the codetrans e2e test

---

ChatQnA/docker/gaudi/docker_compose.yaml
ChatQnA/docker/xeon/docker_compose.yaml
ChatQnA/tests/test_chatqna_on_gaudi.sh

update tgi version  
ghcr.io/huggingface/tgi-gaudi:2.0.0  
ghcr.io/huggingface/text-generation-inference:2.1.0  

update tgi version

---

ChatQnA/docker/gaudi/README.md
ChatQnA/docker/gaudi/how_to_validate_service.md

Add valid micro-service details. 
The GenAI build mega-service on top of micro service and server.
This DOC describe the steps to check and validate the mciro-servcie and server in detail.

[Doc] Add valid micro-service details

---

ChatQnA/docker/aipc/README.md
ChatQnA/docker/gaudi/README.md
ChatQnA/docker/gpu/README.md
ChatQnA/docker/xeon/README.md
ChatQnA/tests/test_chatqna_on_gaudi.sh
ChatQnA/tests/test_chatqna_on_xeon.sh
SearchQnA/docker/gaudi/README.md
SearchQnA/docker/xeon/README.md
SearchQnA/tests/test_searchqna_on_gaudi.sh
SearchQnA/tests/test_searchqna_on_xeon.sh

Update reranking microservice dockerfile path
`n/a`
- [ x ] Bug fix (non-breaking change which fixes an issue)
None
Local test.

Update reranking microservice dockerfile path

---

README.md

Fix visualqna readme

---

.gitattributes
ChatQnA/docker/aipc/README.md
ChatQnA/docker/aipc/docker_compose.yaml

* Add doc for windows env params setup
* fix wrong EOL issue
depends on [309](https://github.com/opea-project/GenAIComps/pull/309)
None
Local Test

Fix win PC issues

---

SearchQnA/docker/gaudi/docker_compose.yaml
SearchQnA/tests/test_searchqna_on_gaudi.sh

bug fix. After this the sqna test should pass.
n/a
None
CI

add auto-truncate to gaudi tei

---

AudioQnA/docker/gaudi/README.md
AudioQnA/docker/gaudi/docker_compose.yaml
AudioQnA/tests/test_audioqna_on_gaudi.sh
AudioQnA/tests/test_audioqna_on_xeon.sh

1. update image names
2. reuse test images
https://github.com/opea-project/GenAIComps/pull/316

update audioqna image name

---

ChatQnA/tests/test_chatqna_on_xeon.sh

expand tgi connect timeout in test
https://github.com/opea-project/GenAIExamples/pull/384, test timeout need to expand

expand tgi connect timeout in test

---

ChatQnA/tests/test_chatqna_on_xeon.sh
CodeGen/tests/test_codegen_on_gaudi.sh
CodeGen/tests/test_codegen_on_xeon.sh
CodeTrans/tests/test_codetrans_on_gaudi.sh
CodeTrans/tests/test_codetrans_on_xeon.sh
DocSum/tests/test_docsum_on_gaudi.sh
DocSum/tests/test_docsum_on_xeon.sh

add docker compose yaml print for debug purpose

add docker compose yaml print for debug purpose

---

.github/workflows/gmc-e2e.yaml
DocSum/README.md
DocSum/kubernetes/manifests/README.md
DocSum/kubernetes/manifests/gaudi/docsum.yaml
DocSum/kubernetes/manifests/xeon/docsum.yaml
DocSum/tests/test_manifest_on_gaudi.sh
DocSum/tests/test_manifest_on_xeon.sh

Add Kubernetes manifest files for deploying DocSum.
`n/a`.
n/a.

Add Kubernetes manifest files for deploying DocSum

---

CodeTrans/README.md
CodeTrans/kubernetes/manifests/README.md
CodeTrans/kubernetes/manifests/gaudi/codetrans.yaml
CodeTrans/kubernetes/manifests/xeon/codetrans.yaml
CodeTrans/tests/test_manifest_on_gaudi.sh
CodeTrans/tests/test_manifest_on_xeon.sh

Add Kubernetes manifest files for deploying CodeTrans.
`n/a`.
n/a.

Add Kubernetes manifest files for deploying CodeTrans

---

CodeGen/kubernetes/manifests/README.md
CodeGen/kubernetes/manifests/gaudi/codegen.yaml
CodeGen/kubernetes/manifests/xeon/codegen.yaml
CodeGen/tests/test_manifest_on_gaudi.sh
CodeGen/tests/test_manifest_on_xeon.sh

Updated Kubernetes manifest files for CodeGen to reflect latest changes:
- upgrade tgi/tgi-gaudi image version
- align model with docker version CodeGen
`n/a`.
n/a.

Update Kubernetes manifest files for CodeGen

---

ChatQnA/README.md
CodeGen/README.md
CodeTrans/README.md
DocSum/README.md

Add README to install the following workloads using helm chart:
- ChatQnA
- CodeGen
- CodeTrans
- DocSum
`n/a`.
n/a.
Tested by GenAIInfra.

README for installing 4 worklods using helm chart

---

.github/workflows/gmc-e2e.yaml

Add checkout ref in gmc e2e workflow
n/a
n/a
CI workflow

Add checkout ref in gmc e2e workflow

---

Translation/docker/gaudi/README.md
Translation/docker/xeon/README.md

fix typo on README
`n/a`.
`n/a`.
`n/a`.

Fix Typo for README of Translation Example

---

AudioQnA/docker/ui/svelte/README.md
ChatQnA/docker/ui/svelte/README.md
CodeGen/docker/ui/svelte/README.md
CodeTrans/docker/ui/svelte/README.md
DocSum/docker/ui/svelte/README.md
Translation/docker/ui/svelte/README.md

Update REAME to be consistent with .env variables.
`n/a`.
no.
CI pass.

Update REAME to be consistent with .env variables

---

ChatQnA/docker/gaudi/docker_compose.yaml
ChatQnA/docker/gaudi/docker_compose_guardrails.yaml
ChatQnA/docker/gpu/docker_compose.yaml

Add auto truncate for embedding and rerank
`n/a`
- [ x ] Bug fix (non-breaking change which fixes an issue)
None
Local test and pre-CI.

Add auto truncate for embedding and rerank

---

SearchQnA/kubernetes/README.md
Translation/kubernetes/README.md
Translation/kubernetes/translation_gaudi.yaml
Translation/kubernetes/translation_xeon.yaml
Translation/tests/test_gmc_on_gaudi.sh
Translation/tests/test_gmc_on_xeon.sh

1. Add new example of `Translation` in GenAIExample
2. Add e2e test for example of `Translation` in GenAIExample
`n/a`.
`n/a`.
Please check the [PR#220](https://github.com/opea-project/GenAIInfra/pull/220) in GenAIInfra repo.

Add new example of Translation for GenAIExample

---

ChatQnA/docker/aipc/README.md
ChatQnA/docker/gaudi/README.md
ChatQnA/docker/gpu/README.md
ChatQnA/docker/xeon/README.md
SearchQnA/docker/gaudi/README.md
SearchQnA/docker/xeon/README.md

Refine Rtrieval part in READMEs
n/a
None
CI test

Refine Example READMEs

---

ChatQnA/benchmark/single_gaudi/chatqna_config_map.yaml
ChatQnA/benchmark/single_gaudi/chatqna_mega_service_run.yaml
ChatQnA/benchmark/single_gaudi/dataprep-microservice_run.yaml
ChatQnA/benchmark/single_gaudi/embedding-dependency_run.yaml
ChatQnA/benchmark/single_gaudi/embedding-microservice_run.yaml
ChatQnA/benchmark/single_gaudi/llm-dependency_run.yaml
ChatQnA/benchmark/single_gaudi/llm-microservice_run.yaml
ChatQnA/benchmark/single_gaudi/reranking-dependency_run.yaml
ChatQnA/benchmark/single_gaudi/reranking-microservice_run.yaml
ChatQnA/benchmark/single_gaudi/retrieval-microservice_run.yaml
ChatQnA/benchmark/single_gaudi/vector-db_run.yaml
ChatQnA/benchmark/two_gaudi/chatqna_config_map.yaml
ChatQnA/benchmark/two_gaudi/chatqna_mega_service_run.yaml
ChatQnA/benchmark/two_gaudi/dataprep-microservice_run.yaml
ChatQnA/benchmark/two_gaudi/embedding-dependency_run.yaml
ChatQnA/benchmark/two_gaudi/embedding-microservice_run.yaml
ChatQnA/benchmark/two_gaudi/llm-dependency_run.yaml
ChatQnA/benchmark/two_gaudi/llm-microservice_run.yaml
ChatQnA/benchmark/two_gaudi/reranking-dependency_run.yaml
ChatQnA/benchmark/two_gaudi/reranking-microservice_run.yaml
ChatQnA/benchmark/two_gaudi/retrieval-microservice_run.yaml
ChatQnA/benchmark/two_gaudi/vector-db_run.yaml

upload manifests

---

AudioQnA/tests/test_audioqna_on_gaudi.sh
AudioQnA/tests/test_audioqna_on_xeon.sh
CodeGen/docker/gaudi/compose.yaml
CodeGen/docker/xeon/compose.yaml
DocSum/docker/gaudi/compose.yaml
DocSum/docker/xeon/compose.yaml

update compose.yaml
https://github.com/opea-project/GenAIExamples/pull/446 

update compose.yaml fix the test issue

---

docker_images_list.md

doc: fix markdown in docker_image_list.md

---

SearchQnA/README.md

* indent content in ordered list element
* remove use of please

doc: fix markdown in SearchQnA/README.md

---

FaqGen/README.md

doc: fix FaqGen/README.md markdown

---

DocSum/README.md

* indent content in ordered lists
* remove use of please
* edit use of unnecessary HTML

doc: fix markdown in DocSum/README.md

---

CodeTrans/README.md

* indent content of ordered list
* edit use of please
* edit unnecessary use of HTML

doc: fix markdown in CodeTrans/README.md

---

CodeGen/README.md

* edit use of please
* remove use of unnecessary HTML tags
* add indenting to content of ordered list items

doc: fix CodeGen/README.md markdown

---

ChatQnA/README.md

* remove unnecessary use of HTML
* fix missing indents on ordered list content
* edit use of "please"

doc: fix markdown in ChatQnA/README.md

---

.github/workflows/docker/code-scan.dockerfile
.github/workflows/scripts/codeScan/hadolint.sh
AudioQnA/deprecated/docker/Dockerfile_asr
AudioQnA/deprecated/docker/Dockerfile_tts
AudioQnA/deprecated/langchain/docker/qna-app/Dockerfile
AudioQnA/docker/Dockerfile
ChatQnA/deprecated/langchain/docker/qna-app/Dockerfile
ChatQnA/docker/Dockerfile
ChatQnA/docker/Dockerfile_guardrails
CodeGen/docker/Dockerfile
CodeTrans/docker/Dockerfile
DocSum/deprecated/langchain/docker/summarize-app/Dockerfile
DocSum/docker/Dockerfile
FaqGen/docker/Dockerfile
SearchQnA/docker/Dockerfile
Translation/deprecated/serving/tgi_gaudi/Dockerfile
Translation/docker/Dockerfile

Fix code-scan (hadolint) waring.

Fix code scan warning

---

.github/workflows/infra-issue-creation.yml

This workflow will create an issue in GenAIInfra when docker compose files are changed in GenAIExamples on push.
n/a
n/a
CI workflow

Automatic create issue to GenAIInfra when docker compose files changed

---

.github/workflows/docker/compose/AudioQnA-compose.yaml
.github/workflows/docker/compose/ChatQnA-compose.yaml
.github/workflows/docker/compose/CodeGen-compose.yaml
.github/workflows/docker/compose/CodeTrans-compose.yaml
.github/workflows/docker/compose/DocSum-compose.yaml
.github/workflows/docker/compose/FaqGen-compose.yaml
.github/workflows/docker/compose/SearchQnA-compose.yaml
.github/workflows/docker/compose/Translation-compose.yaml
.github/workflows/image-build-on-manual.yml
.github/workflows/image-build-on-push.yml

Refactor build image workflows with common action.yml
n/a
n/a
CI workflow

Refactor build image workflows with common action.yml

---

ChatQnA/docker/xeon/README.md

Fix typo {your_ip} to {host_ip}

---

ChatQnA/benchmark/two_gaudi/dataprep-microservice_run.yaml
ChatQnA/docker/gaudi/README.md
ChatQnA/docker/gaudi/compose.yaml
ChatQnA/docker/gaudi/compose_guardrails.yaml
ChatQnA/docker/gaudi/compose_vllm.yaml
ChatQnA/docker/gaudi/compose_vllm_ray.yaml
ChatQnA/docker/gpu/README.md
ChatQnA/docker/gpu/compose.yaml
ChatQnA/docker/gpu/set_env.sh
ChatQnA/docker/ui/svelte/.env
ChatQnA/docker/xeon/README.md
ChatQnA/docker/xeon/compose.yaml
ChatQnA/docker/xeon/docker_compose_vllm.yaml
ChatQnA/tests/test_chatqna_on_gaudi.sh
ChatQnA/tests/test_chatqna_on_xeon.sh

unify dataprep-redis microservice port
related [this pr](https://github.com/opea-project/GenAIComps/pull/424)

update chatqna dataprep-redis port

---

ChatQnA/tests/test_manifest_on_gaudi.sh

Improve manifest chaqna test
closes #563 
n/a
CI test

Improve manifest chaqna test

---

.github/workflows/_run-docker-compose.yml

Fix typo in CI workflow

---

ChatQnA/docker/xeon/README.md

fix script issues in MD file
User complain not to get correct result by following the steps in md file.
Fix them.

fix script issues in MD file

---

.github/workflows/_run-docker-compose.yml

Add secrets for CI test, PINECONE_KEY. 
https://github.com/opea-project/GenAIExamples/pull/540#issuecomment-2284498174

Add secrets for CI test

---

VisualQnA/docker/gaudi/README.md
VisualQnA/docker/xeon/README.md
VisualQnA/docker/xeon/compose.yaml
VisualQnA/kubernetes/README.md
VisualQnA/kubernetes/manifests/README.md
VisualQnA/kubernetes/manifests/gaudi/visualqna.yaml
VisualQnA/kubernetes/manifests/xeon/visualqna.yaml
VisualQnA/kubernetes/visualqna_gaudi.yaml
VisualQnA/kubernetes/visualqna_xeon.yaml

Add kubernetes support for VisualQnA
`n/a`
None
Local Gaudi and Xeon node test.

Add kubernetes support for VisualQnA

---

.github/workflows/_run-docker-compose.yml
.github/workflows/pr-docker-compose-e2e.yml

fix corner issue in CI test

---

.github/workflows/_example-workflow.yml
.github/workflows/_manifest-e2e.yml
.github/workflows/pr-manifest-e2e.yml

Add composable manifest e2e test for cd workflow
n/a
n/a
CI workflow

Add composable manifest e2e test for cd workflow

---

CodeGen/docker/docker_build_compose.yaml
DocSum/tests/test_docsum_on_gaudi.sh
DocSum/tests/test_docsum_on_xeon.sh
Translation/docker/docker_build_compose.yaml
Translation/tests/test_translation_on_gaudi.sh
Translation/tests/test_translation_on_xeon.sh

Fix left issues in CI/CD structure refactor. 
https://github.com/opea-project/GenAIExamples/pull/593/files 

Fix left issues in CI/CD structure refactor

---

.github/workflows/pr-docker-compose-e2e.yml

set action back to pull_request_target

set action back to pull_request_target

---

AudioQnA/kubernetes/README.md
AudioQnA/kubernetes/audioQnA_gaudi.yaml
AudioQnA/kubernetes/audioQnA_xeon.yaml
AudioQnA/tests/test_gmc_on_gaudi.sh
AudioQnA/tests/test_gmc_on_xeon.sh

1. Add `AudioQnA` example yaml file via GMC
2. Add e2e test for `AudioQnA` example via GMC 
`n/a`.
`n/a`.
This PR contains the e2e test for `AudioQnA` example.

Add AudioQnA example via GMC

---

.github/workflows/_example-workflow.yml
.github/workflows/manual-example-workflow.yml

remove continue-on-error: true to stop the test when image build failed
https://github.com/opea-project/GenAIExamples/actions/runs/10391811872

remove continue-on-error: true to stop the test when image build failed

---

ChatQnA/docker/gaudi/set_env.sh
ChatQnA/docker/xeon/set_env.sh

Update port for dataprep in set_env.sh.
Unify to `6007`.
n/a
None

Update port in set_env.sh

---

.github/workflows/_gmc-workflow.yml
.github/workflows/manual-example-workflow.yml

Add gmc build, scan and deploy workflow
n/a
n/a
CI/CD workflow

Add gmc build, scan and deploy workflow

---

.github/workflows/_example-workflow.yml
.github/workflows/_manifest-e2e.yml
ChatQnA/tests/test_manifest_on_gaudi.sh
ChatQnA/tests/test_manifest_on_xeon.sh
CodeGen/tests/test_manifest_on_gaudi.sh
CodeGen/tests/test_manifest_on_xeon.sh
CodeTrans/tests/test_manifest_on_gaudi.sh
CodeTrans/tests/test_manifest_on_xeon.sh
DocSum/tests/test_manifest_on_gaudi.sh
DocSum/tests/test_manifest_on_xeon.sh

Change microservice tags in CD workflow
n/a
n/a
CI tests

Change microservice tags in CD workflow

---

.github/workflows/manual-freeze-images.yml
.github/workflows/manual-freeze-tag.yml

update cd workflow name.   
`.github/workflows/manual-freeze-images.yml` is for base images and 3rd part images version freeze after rc branch created.   
`.github/workflows/manual-freeze-tag.yml` is for OPEA images release tag in readme before tag. 

update cd workflow name

---

.github/workflows/_example-workflow.yml
.github/workflows/_gmc-e2e.yml
.github/workflows/pr-gmc-e2e.yaml

Add GMC e2e in CD workflow
n/a
n/a
CI test

Add GMC e2e in CD workflow

---

.github/workflows/manual-freeze-images.yml
.github/workflows/scripts/freeze_images.sh

Fix manual freeze images workflow
Use skopeo to search docker image tag
`n/a`.
`n/a`
`n/a`

Fix manual freeze images workflow

---

ChatQnA/benchmark/four_gaudi/chatqna_mega_service_run.yaml
ChatQnA/benchmark/four_gaudi/llm-dependency_run.yaml
ChatQnA/benchmark/single_gaudi/chatqna_mega_service_run.yaml
ChatQnA/benchmark/single_gaudi/llm-dependency_run.yaml
ChatQnA/benchmark/two_gaudi/chatqna_mega_service_run.yaml
ChatQnA/benchmark/two_gaudi/llm-dependency_run.yaml

Update benchmark manifest to fix errors
n/a
n/a
n/a

Update benchmark manifest to fix errors

---

ChatQnA/kubernetes/manifests/gaudi/chatqna.yaml
ChatQnA/kubernetes/manifests/xeon/chatqna.yaml
ChatQnA/tests/test_manifest_on_gaudi.sh
ChatQnA/tests/test_manifest_on_xeon.sh
CodeGen/kubernetes/manifests/gaudi/codegen.yaml
CodeGen/kubernetes/manifests/xeon/codegen.yaml
CodeTrans/kubernetes/manifests/gaudi/codetrans.yaml
CodeTrans/kubernetes/manifests/xeon/codetrans.yaml
DocSum/kubernetes/manifests/gaudi/docsum.yaml
DocSum/kubernetes/manifests/xeon/docsum.yaml

- Sync with docker-compose changes since v0.8 release
- Add K8S probes
n/a.

Update K8S manifest for ChatQnA/CodeGen/CodeTrans/DocSum

---

CodeTrans/docker/ui/svelte/.env

Update env for manifest.
`n/a`.
no.
CI pass.

Update env for manifest

---

.github/workflows/_gmc-e2e.yml
.github/workflows/_manifest-e2e.yml

Change namespace suffix to random string
n/a
n/a
n/a

Change namespace suffix to random string

---

.github/workflows/manual-bom-scan.yml

This PR adds actions to run SBOM and Trivy, Container scans on demand.
N/A
- [N] Bug fix (non-breaking change which fixes an issue)
- [Y] New feature (non-breaking change which adds new functionality)
- [N] Breaking change (fix or feature that would break existing design and interface)
- [N] Others (enhancement, documentation, validation, etc.)
None
It'll be tested by the GitHub Actions.

Adding Trivy and SBOM actions

---

ChatQnA/docker/Dockerfile_without_rerank
ChatQnA/docker/chatqna_without_rerank.py
ChatQnA/docker/docker_build_compose.yaml
ChatQnA/docker/gaudi/compose_without_rerank.yaml
ChatQnA/docker/xeon/compose_without_rerank.yaml
ChatQnA/tests/test_chatqna_without_rerank_on_gaudi.sh
ChatQnA/tests/test_chatqna_without_rerank_on_xeon.sh

Support ChatQnA pipeline without rerank microservice
`n/a`
None
Local test

Support ChatQnA pipeline without rerank microservice

---

AudioQnA/tests/test_audioqna_on_gaudi.sh
AudioQnA/tests/test_audioqna_on_xeon.sh
ChatQnA/tests/test_chatqna_guardrails_on_gaudi.sh
ChatQnA/tests/test_chatqna_on_gaudi.sh
ChatQnA/tests/test_chatqna_on_xeon.sh
ChatQnA/tests/test_chatqna_qdrant_on_xeon.sh
ChatQnA/tests/test_chatqna_vllm_on_gaudi.sh
ChatQnA/tests/test_chatqna_vllm_on_xeon.sh
ChatQnA/tests/test_chatqna_vllm_ray_on_gaudi.sh
ChatQnA/tests/test_chatqna_without_rerank_on_gaudi.sh
ChatQnA/tests/test_chatqna_without_rerank_on_xeon.sh
CodeGen/tests/test_codegen_on_gaudi.sh
CodeGen/tests/test_codegen_on_xeon.sh
CodeTrans/tests/test_codetrans_on_gaudi.sh
CodeTrans/tests/test_codetrans_on_xeon.sh
DocSum/tests/test_docsum_on_gaudi.sh
DocSum/tests/test_docsum_on_xeon.sh
FaqGen/tests/test_faqgen_on_gaudi.sh
FaqGen/tests/test_faqgen_on_xeon.sh
ProductivitySuite/tests/test_productivitysuite_on_xeon.sh
SearchQnA/tests/test_searchqna_on_gaudi.sh
SearchQnA/tests/test_searchqna_on_xeon.sh
Translation/tests/test_translation_on_gaudi.sh
Translation/tests/test_translation_on_xeon.sh

Optimize CI log format
The CI log is too long to be opened. 

optimize CI log format

---

DocSum/docker/Dockerfile
FaqGen/docker/Dockerfile
Translation/docker/Dockerfile

Replace langchain docker base image with python

update base image with python

---

ChatQnA/README.md
DocSum/docker/xeon/README.md

Draw flow-chat with mermaid script. 
make it easy to be maintained.

[Doc] Update ChatQnA flow chart

---

ChatQnA/docker/aipc/README.md

Update ollama run command
`n/a`
None
Local test
OLLAMA_HOST=$host_ip:11434  ollama run $OLLAMA_MODEL
>>>
Use Ctrl + d or /bye to exit.
curl http://${host_ip}:8888/v1/chatqna -H "Content-Type: application/json" -d '{
"messages": "What is the revenue of Nike in 2023?", "model": "'"${OLLAMA_MODEL}"'"
}'
data: b'I'
data: b"'m"
data: b' happy'
data: b' to'
data: b' help'
data: b'!'
data: b' However'
data: b','
data: b' I'
data: b' need'
data: b' to'
data: b' clarify'
data: b' that'
data: b' the'
data: b' revenue'
data: b' of'

Update ollama run command

---

AudioQnA/kubernetes/README.md
ChatQnA/kubernetes/README.md
CodeGen/kubernetes/README.md
DocSum/kubernetes/README.md
SearchQnA/kubernetes/README.md
Translation/kubernetes/README.md
VisualQnA/kubernetes/README.md

Change docs of kubernetes for curl commands in README
`n/a`.
`n/a`.
`n/a`.

Change docs of kubernetes for curl commands in README

---

.github/workflows/manual-docker-publish.yml

Enhance image publish action, support gmc image publish

enhance image publish action

---

AgentQnA/README.md
DocIndexRetriever/docker/README.md
ProductivitySuite/README.md
ProductivitySuite/docker/ui/react/README.md
ProductivitySuite/docker/xeon/README.md
ProductivitySuite/kubernetes/manifests/README.md

* Fix incorrect uses of heading levels
* fix indenting within lists

doc: fix headings

---

.github/workflows/manual-bom-scan.yml

This PR ensures that scan artifacts are always upladed.
N/A
- [N] New feature (non-breaking change which adds new functionality)
- [N] Breaking change (fix or feature that would break existing design and interface)
None
N/A

Always upload scan artifacts

---

ChatQnA/README.md
ChatQnA/docker/gaudi/README.md
ChatQnA/docker/gpu/README.md
ChatQnA/docker/xeon/README.md
ChatQnA/docker/xeon/README_qdrant.md
CodeTrans/README.md
CodeTrans/docker/gaudi/README.md
CodeTrans/docker/xeon/README.md
CodeTrans/kubernetes/README.md
CodeTrans/kubernetes/manifests/README.md

Explain Default Model in CodeTrans READMEs
n/a

Explain Default Model in ChatQnA and CodeTrans READMEs

---

ChatQnA/README.md

According to TCEs' feedback, don't need to have those open-source project details in the flowchart.
According to TCEs' feedback, don't need to have those open-source project details in the flowchart.
n/a
NA
NA

Update README.md and remove some open-source details

---

CodeTrans/docker/docker_build_compose.yaml
CodeTrans/docker/gaudi/README.md
CodeTrans/docker/xeon/README.md

fix comps/nginx image build content
https://github.com/opea-project/GenAIExamples/actions/runs/10642314104/job/29522529902

fix comps/nginx image build content

---

VisualQnA/README.md

Add default model for VisualQnA README
`n/a`
None
Just document enhancement

Add default model for VisualQnA README

---

InstructionTuning/README.md
InstructionTuning/docker/gaudi/README.md
InstructionTuning/docker/xeon/README.md
InstructionTuning/tests/test_instruction_tuning_on_xeon.sh

Add instruction tuning example.
`n/a`.

Add instruction tuning example

---

ChatQnA/benchmark/README.md

[ChatQnA] Update Benchmark README for w/o rerank

---

ChatQnA/README.md
ChatQnA/docker/gaudi/README.md
ChatQnA/docker/xeon/README.md

Update README for without Rerank Pipeline.
Update README for dataprep get_file/delete_file part.
None
None

[ChatQnA] Update README for without Rerank Pipeline

---

.github/workflows/pr-docker-compose-e2e.yml
.github/workflows/pr-gmc-e2e.yaml
.github/workflows/pr-manifest-e2e.yml
DocIndexRetriever/tests/test_compose_on_gaudi.sh
VisualQnA/tests/test_compose_on_gaudi.sh
VisualQnA/tests/test_compose_on_xeon.sh

Fix refactor bug

---

.pre-commit-config.yaml
DocIndexRetriever/Dockerfile
DocIndexRetriever/docker_image_build/build.yaml
DocIndexRetriever/tests/test_compose_on_gaudi.sh

fix reorg bug

---

AgentQnA/README.md

AgentQnA: Fix erroneous link in the README
`n/a`.

AgentQnA: Fix erroneous link in the README

---

VideoRAGQnA/README.md

Update invalid link in readme
N/A
N/A

Update invalid link

---

InstructionTuning/tests/test_compose_on_xeon.sh
RerankFinetuning/tests/test_compose_on_xeon.sh

Fix InstructionTuning and RerankFinetuning tests.
`n/a`.

Fix InstructionTuning and RerankFinetuning tests

---

AgentQnA/tests/4_launch_and_validate_agent_tgi.sh
AgentQnA/tests/test_compose_on_gaudi.sh

Fix typo in AgentQnA unit test
na
none
unit test

fix typo in test script in AgentQnA

---

ChatQnA/docker_compose/intel/cpu/xeon/README.md

Chane megaservice creation path in line with new dir structure in repo
- [ x] Bug fix (non-breaking change which fixes an issue)

Change megaservice path in line with new file structure

---

ChatQnA/docker_compose/intel/cpu/xeon/README.md
CodeGen/docker_compose/intel/cpu/xeon/README.md
CodeTrans/docker_compose/intel/cpu/xeon/README.md
DocSum/docker_compose/intel/cpu/xeon/README.md
FaqGen/docker_compose/intel/cpu/xeon/README.md
ProductivitySuite/README.md
Translation/docker_compose/intel/cpu/xeon/README.md
VisualQnA/docker_compose/intel/cpu/xeon/README.md

adopted tech writing style

---

AudioQnA/README.md
ChatQnA/README.md
DocSum/README.md
FaqGen/README.md
SearchQnA/README.md
Translation/README.md
VideoQnA/README.md
VisualQnA/README.md

Fix Xeon reference per its trademark

---

ChatQnA/docker_compose/intel/cpu/xeon/README.md

fix the pdf link of https://github.com/opea-project/GenAIComps/blob/main/comps/retrievers/redis/data/nke-10k-2023.pdf

Update README.md of pdf file

---

README.md

Modified README to welcome contributions and link to contributing guide
cc: @mkbhanda @kding1 @chensuyue

add welcoming contributing section

---

ChatQnA/docker_compose/intel/cpu/xeon/README.md
ChatQnA/docker_compose/intel/hpu/gaudi/README.md
CodeGen/docker_compose/intel/cpu/xeon/README.md
CodeGen/docker_compose/intel/hpu/gaudi/README.md
CodeTrans/docker_compose/intel/cpu/xeon/README.md
CodeTrans/docker_compose/intel/hpu/gaudi/README.md
DocSum/docker_compose/intel/cpu/xeon/README.md
DocSum/docker_compose/intel/hpu/gaudi/README.md
FaqGen/docker_compose/intel/cpu/xeon/README.md
FaqGen/docker_compose/intel/hpu/gaudi/README.md
InstructionTuning/docker_compose/intel/cpu/xeon/README.md
InstructionTuning/docker_compose/intel/hpu/gaudi/README.md
MultimodalQnA/docker_compose/intel/cpu/xeon/README.md
MultimodalQnA/docker_compose/intel/hpu/gaudi/README.md
ProductivitySuite/docker_compose/intel/cpu/xeon/README.md
RerankFinetuning/docker_compose/intel/cpu/xeon/README.md
RerankFinetuning/docker_compose/intel/hpu/gaudi/README.md
SearchQnA/docker_compose/intel/cpu/xeon/README.md
SearchQnA/docker_compose/intel/hpu/gaudi/README.md
Translation/docker_compose/intel/cpu/xeon/README.md
Translation/docker_compose/intel/hpu/gaudi/README.md
VideoQnA/docker_compose/intel/cpu/xeon/README.md
VisualQnA/docker_compose/intel/cpu/xeon/README.md
VisualQnA/docker_compose/intel/hpu/gaudi/README.md

Fix README issues
None
Just document change

Fix README issues

---

ChatQnA/benchmark/oob_no_wrapper/with_rerank/eight_gaudi/no_wrapper_oob_eight_gaudi_with_rerank.yaml
ChatQnA/benchmark/oob_no_wrapper/with_rerank/four_gaudi/no_wrapper_oob_four_gaudi_with_rerank.yaml
ChatQnA/benchmark/oob_no_wrapper/with_rerank/single_gaudi/no_wrapper_oob_single_gaudi_with_rerank.yaml
ChatQnA/benchmark/oob_no_wrapper/with_rerank/two_gaudi/no_wrapper_oob_two_gaudi_with_rerank.yaml
ChatQnA/benchmark/oob_no_wrapper/without_rerank/eight_gaudi/no_wrapper_oob_eight_gaudi_without_rerank.yaml
ChatQnA/benchmark/oob_no_wrapper/without_rerank/four_gaudi/no_wrapper_oob_four_gaudi_without_rerank.yaml
ChatQnA/benchmark/oob_no_wrapper/without_rerank/single_gaudi/no_wrapper_oob_single_gaudi_without_rerank.yaml
ChatQnA/benchmark/oob_no_wrapper/without_rerank/two_gaudi/no_wrapper_oob_two_gaudi_without_rerank.yaml
ChatQnA/benchmark/tuned/with_rerank/four_gaudi/tuned_four_gaudi_with_rerank.yaml
ChatQnA/benchmark/tuned/with_rerank/single_gaudi/tuned_single_gaudi_with_rerank.yaml
ChatQnA/benchmark/tuned/with_rerank/two_gaudi/tuned_two_gaudi_with_rerank.yaml
ChatQnA/benchmark/tuned/without_rerank/four_gaudi/tuned_four_gaudi_without_rerank.yaml
ChatQnA/benchmark/tuned/without_rerank/single_gaudi/tuned_single_gaudi_without_rerank.yaml
ChatQnA/benchmark/tuned/without_rerank/two_gaudi/tuned_two_gaudi_without_rerank.yaml
ChatQnA/benchmark/tuned_no_wrapper/with_rerank/eight_gaudi/no_wrapper_tuned_eight_gaudi_with_rerank.yaml
ChatQnA/benchmark/tuned_no_wrapper/with_rerank/four_gaudi/no_wrapper_tuned_four_gaudi_with_rerank.yaml
ChatQnA/benchmark/tuned_no_wrapper/with_rerank/single_gaudi/no_wrapper_tuned_single_gaudi_with_rerank.yaml
ChatQnA/benchmark/tuned_no_wrapper/with_rerank/two_gaudi/no_wrapper_tuned_two_gaudi_with_rerank.yaml
ChatQnA/benchmark/tuned_no_wrapper/without_rerank/eight_gaudi/no_wrapper_tuned_eight_gaudi_without_rerank.yaml
ChatQnA/benchmark/tuned_no_wrapper/without_rerank/four_gaudi/no_wrapper_tuned_four_gaudi_without_rerank.yaml
ChatQnA/benchmark/tuned_no_wrapper/without_rerank/single_gaudi/no_wrapper_tuned_single_gaudi_without_rerank.yaml
ChatQnA/benchmark/tuned_no_wrapper/without_rerank/two_gaudi/no_wrapper_tuned_two_gaudi_without_rerank.yaml

update V1.0 benchmark manifest 

update V1.0 benchmark manifest 

---

.github/workflows/pr-path-detection.yml

Fix other repo issue.

---

MultimodalQnA/README.md
Translation/README.md
VisualQnA/README.md

Update README.md for Multiplatforms

Update README.md for Multiplatforms

---

README.md

doc PR to main instead of of v1.0r

---

VisualQnA/README.md

Remove marketing materials

---

ChatQnA/README.md
DocSum/README.md
DocSum/docker_compose/intel/cpu/xeon/README.md
DocSum/docker_compose/intel/hpu/gaudi/README.md

Refine ChatQnA README
n/a
None
CI test

[Doc] Refine READMEs

---

ChatQnA/README.md
ChatQnA/docker_compose/intel/cpu/xeon/README.md
ChatQnA/docker_compose/intel/hpu/gaudi/README.md
ChatQnA/docker_compose/nvidia/gpu/README.md

Refine ChatQnA README
n/a
None
None

[Doc] Refine ChatQnA README

---

ChatQnA/benchmark/performance/README.md
ChatQnA/benchmark/performance/benchmark.yaml

Add docker based benchmark instructions for ChatQnA
`n/a`
None
Just document change

Add docker based benchmark instructions for ChatQnA

---

ProductivitySuite/README.md
ProductivitySuite/docker_compose/intel/cpu/xeon/README.md
ProductivitySuite/docker_compose/intel/cpu/xeon/keycloak_setup_guide.md
ProductivitySuite/kubernetes/intel/README.md
supported_examples.md

Documentation README update for ProductivitySuite example
n/a
n/a

Documentation README update for ProductivitySuite example

---

VisualQnA/ui/svelte/.env
VisualQnA/ui/svelte/src/lib/modules/chat/ChatMessage.svelte
VisualQnA/ui/svelte/src/lib/modules/upload/imagePrompt.svelte
VisualQnA/ui/svelte/src/lib/modules/upload/upload.svelte
VisualQnA/ui/svelte/src/lib/modules/upload/uploadImg.svelte
VisualQnA/ui/svelte/src/lib/network/chat/Network.ts
VisualQnA/ui/svelte/src/lib/shared/components/header/header.svelte
VisualQnA/ui/svelte/src/lib/shared/stores/common/Store.ts
VisualQnA/ui/svelte/src/routes/+page.svelte
VisualQnA/ui/svelte/vite.config.ts

Added the function of detecting whether the uploaded content is safe and providing prompts.
`n/a`.
Depends on the input and output of the new backend model.
npm run dev

Added the function of detecting whether the uploaded content is safe and providing prompts

---

MultimodalQnA/docker_compose/intel/hpu/gaudi/README.md

Fixes a small typo in image build setup for Gaudi server

[docs] Fixes Typo in Gaudi Docker Images Setup

---

ChatQnA/benchmark/performance/helm_charts/README.md

First H1 heading is the title of the document.

doc: fix doc heading

---

ChatQnA/docker_compose/intel/cpu/aipc/README.md

Update the AIPC: Add Ollama service configuration setting

[doc] Update AIPC document

---

FaqGen/README.md

Added a workflow for FaqGen following what ChatQnA has. [ChatQnA flow](https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA#architecture-and-deploy-details)
`n/a`.
na

Update FaqGen README.md for its workflow

---

VisualQnA/docker_image_build/build.yaml

Fix image name for image build/publish

fix image name

---

SearchQnA/README.md

Added a workflow for SearchQnA following what ChatQnA has. [ChatQnA flow](https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA#architecture-and-deploy-details)
`n/a`.
na

Update SearchQnA README.md for its workflow

---

ChatQnA/kubernetes/intel/hpu/gaudi/manifest/chatqna-vllm.yaml

Added the K8s yaml for vLLM support for ChatQnA

Added the K8s yaml for vLLM support

---

.github/workflows/pr-path-detection.yml

Fix the issue of exiting due to inability to find hyperlinks

Fix the issue of exiting due to inability to find hyperlinks

---

ChatQnA/benchmark/performance/README.md

Fix https://github.com/opea-project/GenAIEval/issues/144

doc: Update ChatQnA/benchmark/performance doc

---

DocSum/README.md

Added a workflow for DocSum following what ChatQnA has. [ChatQnA flow](https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA#architecture-and-deploy-details)
`n/a`.
NA

Update DocSum README.md for its workflow

---

ChatQnA/docker_compose/intel/cpu/aipc/README.md

[DOC] Update ChatQnA AIPC README
Enhancement documentation
No
Verify document locally.

[Doc] Update ChatQnA AIPC README

---

.pre-commit-config.yaml

https://github.com/PyCQA/docformatter/issues/289
CI issue
n/a
pre-commit

Freeze docformatter in pre-commit

---

AudioQnA/benchmark/accuracy/README.md
AudioQnA/benchmark/accuracy/run_acc.sh
ChatQnA/benchmark/accuracy/README.md
ChatQnA/benchmark/accuracy/eval_crud.py
ChatQnA/benchmark/accuracy/eval_multihop.py
ChatQnA/benchmark/accuracy/process_crud_dataset.py
ChatQnA/benchmark/accuracy/run_acc.sh
CodeGen/benchmark/accuracy/README.md
CodeGen/benchmark/accuracy/main.py
CodeGen/benchmark/accuracy/run_acc.sh
FaqGen/benchmark/accuracy/README.md
FaqGen/benchmark/accuracy/run_acc.sh

1. add ChatQnA accuracy evaluation code
2. update accuracy readme

update examples accuracy

---

MultimodalQnA/README.md

Added a workflow for MultiModal following what ChatQnA has. [ChatQnA flow](https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA#architecture-and-deploy-details)
`n/a`.
na

Update MultiModal README.md for workflow

---

ChatQnA/benchmark/performance/helm_charts/customize.yaml
ChatQnA/benchmark/performance/oob/with_rerank/eight_gaudi/oob_eight_gaudi_with_rerank.yaml
ChatQnA/benchmark/performance/oob/with_rerank/four_gaudi/oob_four_gaudi_with_rerank.yaml
ChatQnA/benchmark/performance/oob/with_rerank/single_gaudi/oob_single_gaudi_with_rerank.yaml
ChatQnA/benchmark/performance/oob/with_rerank/two_gaudi/oob_two_gaudi_with_rerank.yaml
ChatQnA/benchmark/performance/oob/without_rerank/eight_gaudi/oob_eight_gaudi_without_rerank.yaml
ChatQnA/benchmark/performance/oob/without_rerank/four_gaudi/oob_four_gaudi_without_rerank.yaml
ChatQnA/benchmark/performance/oob/without_rerank/single_gaudi/oob_single_gaudi_without_rerank.yaml
ChatQnA/benchmark/performance/oob/without_rerank/two_gaudi/oob_two_gaudi_without_rerank.yaml
ChatQnA/benchmark/performance/tuned/with_rerank/eight_gaudi/eight_gaudi_with_rerank.yaml
ChatQnA/benchmark/performance/tuned/with_rerank/four_gaudi/tuned_four_gaudi_with_rerank.yaml
ChatQnA/benchmark/performance/tuned/with_rerank/single_gaudi/tuned_single_gaudi_with_rerank.yaml
ChatQnA/benchmark/performance/tuned/with_rerank/two_gaudi/tuned_two_gaudi_with_rerank.yaml
ChatQnA/benchmark/performance/tuned/without_rerank/eight_gaudi/tuned_eight_gaudi_without_rerank.yaml
ChatQnA/benchmark/performance/tuned/without_rerank/four_gaudi/tuned_four_gaudi_without_rerank.yaml
ChatQnA/benchmark/performance/tuned/without_rerank/single_gaudi/tuned_single_gaudi_without_rerank.yaml
ChatQnA/benchmark/performance/tuned/without_rerank/two_gaudi/tuned_two_gaudi_without_rerank.yaml

Clean no wrapper image in performance benchmark manifests
`n/a`
None

Clean no wrapper image in performance benchmark manifests

---

ProductivitySuite/README.md

Added a workflow for Productivity following what ChatQnA has. [ChatQnA flow](https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA#architecture-and-deploy-details)
`n/a`.
na
```mermaid
---
config:
flowchart:
nodeSpacing: 400
rankSpacing: 100
curve: linear
themeVariables:
fontSize: 50px
---
flowchart LR
%% Colors %%
classDef blue fill:#ADD8E6,stroke:#ADD8E6,stroke-width:2px,fill-opacity:0.5
classDef orange fill:#FBAA60,stroke:#ADD8E6,stroke-width:2px,fill-opacity:0.5
classDef orchid fill:#C26DBC,stroke:#ADD8E6,stroke-width:2px,fill-opacity:0.5
classDef invisible fill:transparent,stroke:transparent;
style ChatQnA-MegaService stroke:#000000
%% Subgraphs %%
subgraph ChatQnA-MegaService["ChatQnA …
```

Update Productivity README.md for workflow

---

ChatQnA/docker_compose/intel/cpu/aipc/compose.yaml
ChatQnA/docker_compose/intel/cpu/xeon/compose.yaml
ChatQnA/docker_compose/intel/cpu/xeon/compose_qdrant.yaml
ChatQnA/docker_compose/intel/cpu/xeon/compose_vllm.yaml
ChatQnA/docker_compose/intel/cpu/xeon/compose_without_rerank.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_guardrails.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_vllm.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_vllm_ray.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_without_rerank.yaml
ChatQnA/tests/test_compose_guardrails_on_gaudi.sh
ChatQnA/tests/test_compose_on_gaudi.sh
ChatQnA/tests/test_compose_on_xeon.sh
ChatQnA/tests/test_compose_qdrant_on_xeon.sh
ChatQnA/tests/test_compose_vllm_on_gaudi.sh
ChatQnA/tests/test_compose_vllm_on_xeon.sh
ChatQnA/tests/test_compose_vllm_ray_on_gaudi.sh
ChatQnA/tests/test_compose_without_rerank_on_gaudi.sh
ChatQnA/tests/test_compose_without_rerank_on_xeon.sh

Add missing nginx microservice and fix frontend test
`n/a`
None
Local test and pre-CI test.

Add missing nginx microservice and fix frontend test

---

DocSum/README.md
DocSum/docker_compose/intel/cpu/xeon/README.md
DocSum/docker_compose/intel/hpu/gaudi/README.md

Support Chinese for Docsum
Related PR of GenAIComps is https://github.com/opea-project/GenAIComps/pull/796

Support Chinese for Docsum

---

.github/workflows/_example-workflow.yml
.github/workflows/manual-image-build.yml

Fix issue find in single image build

Fix issue find in image build

---

ChatQnA/chatqna.py

fix chatqna accuracy issue with incorrect penalty
na
None
UT

fix chatqna accuracy issue with incorrect penalty

---

ChatQnA/chatqna.py

Fix top_n rerank docs
na
na
ut

Fix top_n rerank docs

---

ChatQnA/docker_compose/intel/cpu/xeon/compose_qdrant.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_guardrails.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_vllm.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_vllm_ray.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_without_rerank.yaml
ChatQnA/docker_compose/nvidia/gpu/compose.yaml

Set TEI_EMBEDDING_ENDPOINT to use local embedding service
n/a
docker compose up -d

Update ChatQnA yaml and set retriever's TEI_EMBEDDING_ENDPOINT

---

.github/workflows/pr-manifest-e2e.yml

open manifest test in CI when dockerfile changed

open manifest test in CI when dockerfile changed

---

AudioQnA/benchmark/accuracy/README.md
AudioQnA/benchmark/accuracy/run_acc.sh

Fix script name errors.

---

VideoQnA/README.md

Added a workflow for VideoQnA following what ChatQnA has. [ChatQnA flow](https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA#architecture-and-deploy-details)
`n/a`.
na

Update VideoQnA README.md for workflow

---

ChatQnA/README.md
ChatQnA/docker_compose/intel/cpu/xeon/README.md
ChatQnA/docker_compose/intel/cpu/xeon/README_qdrant.md
ChatQnA/docker_compose/intel/hpu/gaudi/README.md
CodeGen/README.md
CodeTrans/README.md
DocSum/README.md
SearchQnA/README.md
VisualQnA/README.md

Update README for some info updated
`n/a`
None
Just document refine

Update README for some minor issues

---

ChatQnA/docker_compose/intel/cpu/xeon/README.md
ChatQnA/docker_compose/intel/hpu/gaudi/README.md

Address request to get docker logs from general name instead of unique ID
`n/a`.
na
bash command testing

Address request from Issue#971

---

DocSum/ui/svelte/src/lib/doc.svelte
DocSum/ui/svelte/src/lib/dropFile.svelte
DocSum/ui/svelte/src/lib/shared/Network.ts
DocSum/ui/svelte/src/lib/shared/Store.ts
DocSum/ui/svelte/src/routes/+page.svelte

Update upload response format and add streaming method in front_end
`n/a`.
CI pass.
npm run dev

update upload response format and add streaming method in front_end

---

.github/workflows/_manifest-e2e.yml

Repopulate the CI failure from inner test script to make sure the failure is correctly caught.
`n/a`.

manifest CI: repopulate the failure from inner test script

---

AudioQnA/kubernetes/intel/README.md
ChatQnA/kubernetes/intel/cpu/xeon/manifest/chatqna-guardrails.yaml
ChatQnA/kubernetes/intel/cpu/xeon/manifest/chatqna.yaml
ChatQnA/kubernetes/intel/cpu/xeon/manifest/chatqna_bf16.yaml
ChatQnA/kubernetes/intel/hpu/gaudi/manifest/chatqna-guardrails.yaml
ChatQnA/kubernetes/intel/hpu/gaudi/manifest/chatqna.yaml
ChatQnA/tests/test_manifest_on_gaudi.sh
ChatQnA/tests/test_manifest_on_xeon.sh
CodeGen/kubernetes/intel/README.md
CodeGen/kubernetes/intel/cpu/xeon/manifest/README_react_ui.md
CodeTrans/kubernetes/intel/README.md
DocSum/kubernetes/intel/README.md
DocSum/kubernetes/intel/cpu/xeon/manifest/ui/README.md
FaqGen/kubernetes/intel/README.md
FaqGen/kubernetes/intel/cpu/xeon/manifest/README_react_ui.md
ProductivitySuite/kubernetes/intel/README.md
Translation/kubernetes/intel/README.md
VisualQnA/kubernetes/intel/README.md

Fix ChatQnA manifest default port issue
[`1026`](https://github.com/opea-project/GenAIExamples/issues/1026)
None
Local test

Fix ChatQnA manifest default port issue

---

.github/workflows/nightly-docker-build-publish.yml

Update nightly image build jobs

Update nightly image build jobs

---

.github/workflows/pr-path-detection.yml

Remove debug outputs

---

.github/workflows/check-online-doc-build.yml
README.md

Add CI case to check online doc building, not update online doc

Add CI case to check online doc building, not update online doc

---

FaqGen/tests/test_compose_on_gaudi.sh
FaqGen/tests/test_compose_on_xeon.sh

Comment out the front-end test
`n/a`.
CI pass.
CI test

Comment out the front-end test

---

.github/workflows/check-online-doc-build.yml

opt CI to skip none MD and RST files

opt CI to skip none MD and RST files

---

.github/workflows/_example-workflow.yml
.github/workflows/nightly-docker-build-publish.yml

image build bug fix

---

ChatQnA/chatqna.py

Fix issue when no_wrapper "stream" is False
```
http_proxy= curl http://${host_ip}:8888/v1/chatqna     -H "Content-Type: application/json"     -d '{
"messages": "What is the revenue of Nike in 2023?","stream":"False"
}'
```
n/a
na
local test

Fix non stream case

---

ChatQnA/benchmark/performance/kubernetes/intel/gaudi/deploy.py
ChatQnA/benchmark/performance/kubernetes/intel/gaudi/generate_helm_values.py

Here are some adjustments for v1.1:
- Remove llm/rerank/embedding microservices for v1.1 default pipeline is no-wrapper.
- Remove configmap which was added for teirerank on Gaudi

Adjustments for v1.1 [pending for v1.1-dev]

---

SearchQnA/docker_compose/intel/hpu/gaudi/compose.yaml
SearchQnA/tests/test_compose_on_gaudi.sh
SearchQnA/ui/svelte/tests/searchQnA.spec.ts

SearchQnA CI test failed at frontend test.
Fix the CI issue, update the test prompt.
n/a
None
Local tested

Fix SearchQnA CI Issue

---

AgentQnA/docker_compose/intel/cpu/xeon/README.md
AgentQnA/docker_compose/intel/hpu/gaudi/README.md

Update AgentQnA README.md for refactor doc structure

---

.github/workflows/_example-workflow.yml

Fix typo in ci workflow
https://github.com/opea-project/GenAIExamples/pull/1142/files

fix typo involved in ci workflow

---

.github/workflows/_get-test-matrix.yml
.github/workflows/push-image-build.yml
.github/workflows/scripts/get_test_matrix.sh

optimize hardware list for test

optimize hardware list for test

---

GraphRAG/docker_compose/intel/hpu/gaudi/compose.yaml
GraphRAG/docker_image_build/build.yaml

Rename the GraphRAG UI image per the review [comment ](https://github.com/opea-project/GenAIExamples/pull/1007#discussion_r1845469474 )
n/a 
n/a
Use `tests/test_compose_on_gaudi.sh` to verify the change.

Rename the GraphRAG UI image

---

ChatQnA/kubernetes/intel/README_single_node.md

Change `minikube apply -f chatqna.yaml` to `kubectl apply -f chatqna.yaml`
Error: unknown command "apply" for "minikube"

Fix command in README for deploying ChatQnA application

---

.github/workflows/manual-freeze-tag.yml

Align https://github.com/opea-project/GenAIExamples/pull/1141
`n/a`
`n/a`
`n/a`

Update manual-freeze-tag workflow

---

ChatQnA/tests/test_compose_on_gaudi.sh
README.md

1. freeze nodejs version in CI test
2. remove version flag in main page

freeze nodejs version in CI test

---

ChatQnA/benchmark/performance/kubernetes/intel/gaudi/benchmark.sh
ChatQnA/benchmark/performance/kubernetes/intel/gaudi/benchmark.yaml
ChatQnA/benchmark/performance/kubernetes/intel/gaudi/deploy.py
ChatQnA/benchmark/performance/kubernetes/intel/gaudi/generate_helm_values.py

chatqna benchmark for v1.1 release 

chatqna benchmark for v1.1 release 

---

Translation/kubernetes/intel/cpu/xeon/manifest/translation.yaml
Translation/kubernetes/intel/hpu/gaudi/manifest/translation.yaml

Fix Translation Manifest CI with MODEL_ID。
[CI test failed](https://github.com/opea-project/GenAIExamples/actions/runs/11925942899/job/33243080819)
None
Local tested

Fix Translation Manifest CI with MODEL_ID

---

.github/workflows/_example-workflow.yml

Limit the version of vllm to avoid dockers build failures.

Limit the version of vllm to avoid dockers build failures.

---

ChatQnA/docker_compose/intel/cpu/xeon/README.md
ChatQnA/docker_compose/intel/cpu/xeon/compose_vllm.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/README.md

Refactor service names
na
None
UT

Refactor service names

---

.github/ISSUE_TEMPLATE/1_bug_template.yml
.github/ISSUE_TEMPLATE/2_feaure_template.yml

add label automaticly when create issue
Feature

add label automaticly when create issue

---

.github/workflows/pr-check-duplicated-image.yml
.github/workflows/scripts/check_duplicated_image.py

Add check for conflict image build definition which generate the same image name with conflict content.
`n/a`.

CI: Add check for conflict image build definition

---

ChatQnA/docker_compose/intel/cpu/xeon/README_pinecone.md

Readme was outdated for ChatQnA pinecone, updated it now to reflect the current changes and structure.
n/a
documentation

Updated the Pinecone readme to reflect the new structure

---

ChatQnA/README.md

Fixes the embedding endpoint based on the one defined in https://github.com/opea-project/GenAIComps/blob/main/comps/embeddings/tei/langchain/embedding_tei.py#L43
na

[ChatQNA] Fixes Embedding Endpoint

---

.github/workflows/pr-dependency-review.yml

Change to pull_request_target for dependency review workflow
`n/a`
`n/a`
`n/a`

Change to pull_request_target for dependency review workflow

---

DocIndexRetriever/tests/test_compose_on_xeon.sh
DocIndexRetriever/tests/test_compose_without_rerank_on_xeon.sh

Align DocIndexRetriever Xeon w/o rerank tests with Gaudi
As a subsequent PR of https://github.com/opea-project/GenAIExamples/pull/1266, these Xeon tests are adapted.
na
NA
The tests are refined.

Align DocIndexRetriever Xeon tests with Gaudi

---

FaqGen/docker_compose/intel/cpu/xeon/README.md
FaqGen/docker_compose/intel/hpu/gaudi/README.md
FaqGen/tests/test_compose_on_gaudi.sh
FaqGen/tests/test_compose_on_xeon.sh

Fix issue https://github.com/opea-project/GenAIExamples/issues/1275

FaqGen param fix

---

VisualQnA/docker_compose/amd/gpu/rocm/compose.yaml
VisualQnA/docker_compose/intel/cpu/xeon/compose.yaml
VisualQnA/docker_image_build/build.yaml
VisualQnA/tests/test_compose_on_xeon.sh

Fix VisualQnA CI issues caused by Comps refactor

---

AudioQnA/tests/test_compose_on_rocm.sh

AudioQnA GPU 

---

AvatarChatbot/avatarchatbot.py
AvatarChatbot/docker_compose/intel/cpu/xeon/compose.yaml
AvatarChatbot/docker_compose/intel/hpu/gaudi/compose.yaml
AvatarChatbot/tests/test_compose_on_gaudi.sh
AvatarChatbot/tests/test_compose_on_xeon.sh

AvatarChatbot - refactor UT

---

AvatarChatbot/tests/test_compose_on_gaudi.sh

AvatarChatbot gaudi refactor ut

---

ChatQnA/tests/test_compose_on_rocm.sh

chatqna rocm ut trigger

---

SearchQnA/tests/test_compose_on_gaudi.sh
SearchQnA/tests/test_compose_on_xeon.sh
SearchQnA/ui/svelte/src/routes/+page.svelte
SearchQnA/ui/svelte/tests/searchQnA.spec.ts

Update SearchQnA response format.
`n/a`.
no
CI pass.

Update SearchQnA response format

---

CodeGen/ui/svelte/src/routes/+page.svelte

update codeGen ui format
`n/a`.
no
CI pass.

update codeGen ui format

---

CodeTrans/ui/svelte/src/routes/+page.svelte

Update codeTrans format.
`n/a`.
no
CI pass.

update codeTrans format

---

GraphRAG/docker_image_build/build.yaml

Update dockerfile for GraphRAG
`n/a`
None
CI test

Update dockerfile for GraphRAG

---

CodeGen/docker_compose/amd/gpu/rocm/compose.yaml
CodeGen/docker_compose/intel/cpu/xeon/compose.yaml
CodeGen/docker_compose/intel/hpu/gaudi/compose.yaml
CodeGen/tests/test_compose_on_gaudi.sh
CodeGen/tests/test_compose_on_rocm.sh
CodeGen/tests/test_compose_on_xeon.sh
CodeGen/ui/svelte/src/routes/+page.svelte

Update CodeGen for GenAIComps Refactor
`n/a`.
None
CI test

Update CodeGen for GenAIComps Refactor

---

ChatQnA/docker_compose/intel/cpu/aipc/set_env.sh
ChatQnA/docker_compose/intel/cpu/xeon/set_env.sh
ChatQnA/docker_compose/intel/hpu/gaudi/set_env.sh

Update set_env.sh to fix LOGFLAG warning

---

EdgeCraftRAG/Dockerfile
EdgeCraftRAG/Dockerfile.server
EdgeCraftRAG/README.md
EdgeCraftRAG/docker_compose/intel/gpu/arc/compose.yaml
EdgeCraftRAG/docker_compose/intel/gpu/arc/compose_vllm.yaml
EdgeCraftRAG/edgecraftrag/api/v1/chatqna.py
EdgeCraftRAG/edgecraftrag/api/v1/data.py
EdgeCraftRAG/edgecraftrag/api/v1/pipeline.py
EdgeCraftRAG/edgecraftrag/api_schema.py
EdgeCraftRAG/edgecraftrag/base.py
EdgeCraftRAG/edgecraftrag/components/benchmark.py
EdgeCraftRAG/edgecraftrag/components/generator.py
EdgeCraftRAG/edgecraftrag/components/indexer.py
EdgeCraftRAG/edgecraftrag/components/model.py
EdgeCraftRAG/edgecraftrag/components/node_parser.py
EdgeCraftRAG/edgecraftrag/components/pipeline.py
EdgeCraftRAG/edgecraftrag/controllers/pipelinemgr.py
EdgeCraftRAG/edgecraftrag/requirements.txt
EdgeCraftRAG/edgecraftrag/utils.py
EdgeCraftRAG/requirements.txt
EdgeCraftRAG/tests/common.sh
EdgeCraftRAG/tests/configs/test_pipeline_vllm.json
EdgeCraftRAG/tests/test_compose_on_arc.sh
EdgeCraftRAG/tests/test_compose_vllm_on_arc.sh
EdgeCraftRAG/ui/gradio/ecrag_client.py
EdgeCraftRAG/ui/gradio/ecragui.py
EdgeCraftRAG/ui/gradio/requirements.txt

- Support image/url data retrieval and display in EC-RAG
- Support display of LLM-used context sources in UI
- Support pipeline remove operation in RESTful API and UI
- Support RAG pipeline performance benchmark and display in UI
- Fixed known issues in EC-RAG UI and server
n/a
- [√ ] Bug fix (non-breaking change which fixes an issue)
- [ √] New feature (non-breaking change which adds new functionality)
llama-index

add new feature and bug fix for EC-RAG 

---

DocIndexRetriever/docker_compose/intel/cpu/xeon/compose.yaml
DocIndexRetriever/docker_compose/intel/cpu/xeon/compose_without_rerank.yaml
DocIndexRetriever/docker_compose/intel/hpu/gaudi/compose.yaml
DocIndexRetriever/retrieval_tool.py
DocIndexRetriever/tests/test_compose_on_gaudi.sh
DocIndexRetriever/tests/test_compose_on_xeon.sh
DocIndexRetriever/tests/test_compose_without_rerank_on_xeon.sh

Update DocIndexRetriever for GenAIComps refactor
`n/a`.
None
CI test

Update DocIndexRetriever for GenAIComps refactor

---

CodeTrans/docker_compose/amd/gpu/rocm/compose.yaml
CodeTrans/docker_compose/intel/cpu/xeon/compose.yaml
CodeTrans/docker_compose/intel/hpu/gaudi/compose.yaml
CodeTrans/docker_image_build/build.yaml
CodeTrans/tests/test_compose_on_gaudi.sh
CodeTrans/tests/test_compose_on_rocm.sh
CodeTrans/tests/test_compose_on_xeon.sh
CodeTrans/ui/svelte/src/routes/+page.svelte

Update CodeTrans for GenAIComps Refactor
`n/a`
None
CI test

Update CodeTrans for GenAIComps Refactor

---

AudioQnA/audioqna.py
AudioQnA/docker_compose/amd/gpu/rocm/compose.yaml
AudioQnA/docker_compose/intel/cpu/xeon/compose.yaml
AudioQnA/docker_compose/intel/hpu/gaudi/compose.yaml
AudioQnA/tests/test_compose_on_gaudi.sh
AudioQnA/tests/test_compose_on_rocm.sh
AudioQnA/tests/test_compose_on_xeon.sh
AvatarChatbot/docker_compose/intel/cpu/xeon/compose.yaml
AvatarChatbot/docker_compose/intel/hpu/gaudi/README.md
AvatarChatbot/docker_compose/intel/hpu/gaudi/compose.yaml
AvatarChatbot/tests/test_compose_on_gaudi.sh
AvatarChatbot/tests/test_compose_on_xeon.sh

AudioQnA/AvatarChatbot fix
https://github.com/opea-project/GenAIExamples/actions/runs/12570011134/job/35039336086?pr=1285

 AudioQnA/AvatarChatbot fix

---

ProductivitySuite/docker_compose/intel/cpu/xeon/compose.yaml
ProductivitySuite/tests/test_compose_on_xeon.sh

Fix ProductivitySuite Issue

---

.github/workflows/_get-test-matrix.yml
ProductivitySuite/docker_image_build/build.yaml
Translation/docker_compose/amd/gpu/rocm/README.md
Translation/docker_compose/amd/gpu/rocm/compose.yaml
Translation/tests/test_compose_on_rocm.sh

ProductivitySuite/Translation fix

 ProductivitySuite/Translation fix

---

.github/workflows/pr-docker-compose-e2e.yml
.github/workflows/pr-gmc-e2e.yaml
.github/workflows/pr-manifest-e2e.yml.disabled
.github/workflows/scripts/get_test_matrix.sh

Fix changed file detect issue while generate test matrix. 
https://github.com/opea-project/GenAIExamples/actions/runs/12579489197/job/35059866400?pr=1335 
```
print all changed files=.github/workflows/_get-test-matrix.yml
ProductivitySuite/docker_image_build/build.yaml
Translation/docker_compose/amd/gpu/rocm/README.md
Translation/docker_compose/amd/gpu/rocm/compose.yaml
Translation/tests/test_compose_on_rocm.sh
filtered changed_files=ProductivitySuite/docker_image_build/build.yaml
Translation/tests/test_compose_on_rocm.sh
```
`Translation/docker_compose/amd/gpu/rocm/compose.yaml` should also in the filtered list. 
Describe the tests that you ran to …

Fix changed file detect issue

---

.github/workflows/pr-docker-compose-e2e.yml
AgentQnA/tests/test_compose_on_gaudi.sh
AgentQnA/tests/test_compose_on_rocm.sh
AudioQnA/docker_compose/amd/gpu/rocm/compose.yaml
AudioQnA/tests/test_compose_on_gaudi.sh
AudioQnA/tests/test_compose_on_rocm.sh
AudioQnA/tests/test_compose_on_xeon.sh
AvatarChatbot/tests/test_compose_on_gaudi.sh
AvatarChatbot/tests/test_compose_on_xeon.sh
ChatQnA/tests/test_compose_on_gaudi.sh
ChatQnA/tests/test_compose_on_rocm.sh
ChatQnA/tests/test_compose_on_xeon.sh
GraphRAG/tests/test_compose_on_gaudi.sh
MultimodalQnA/tests/test_compose_on_gaudi.sh
MultimodalQnA/tests/test_compose_on_rocm.sh
MultimodalQnA/tests/test_compose_on_xeon.sh

UT fix for https://github.com/opea-project/GenAIExamples/pull/1332
test following examples:
AgentQnA
AudioQnA 
AvatarChatbot  
ChatQnA 
GraphRAG 
MultimodalQnA 

UT test for PR1332

---

AgentQnA/tests/step2_start_retrieval_tool.sh
AgentQnA/tests/test_compose_on_gaudi.sh
AgentQnA/tests/test_compose_on_rocm.sh

[for quick UT only] Stream ut agent

---

ChatQnA/benchmark/performance/kubernetes/intel/gaudi/deploy.py
ChatQnA/benchmark/performance/kubernetes/intel/gaudi/generate_helm_values.py

Fix chatqna benchmark without rerank config issue
adapt to https://github.com/opea-project/GenAIInfra/pull/653/files#diff-9f2a6f57822f888ca755c92ad336f3db9c594d83628dffbaa1087b0a9a4931c6R40 

fix chatqna benchmark without rerank config issue

---

.github/CODEOWNERS

In `.github/CODEOWNERS` the last pattern go first, so need to adjust the list. 

Fix code owner list

---

FaqGen/docker_compose/intel/hpu/gaudi/README.md

fix https://github.com/opea-project/GenAIExamples/issues/1349 : 
The faqgen example does now work after the steps are followed in the documentation]
give a quick start

Update README.md for quick start guide

---

.github/CODEOWNERS
.github/license_template.txt

Change license template 2024 to 2025

Change license template from 2024 to 2025

---

EdgeCraftRAG/README.md
EdgeCraftRAG/docker_compose/intel/gpu/arc/compose_vllm.yaml
EdgeCraftRAG/edgecraftrag/api/v1/data.py
EdgeCraftRAG/edgecraftrag/api/v1/pipeline.py
EdgeCraftRAG/edgecraftrag/api_schema.py
EdgeCraftRAG/edgecraftrag/base.py
EdgeCraftRAG/edgecraftrag/components/retriever.py
EdgeCraftRAG/edgecraftrag/controllers/nodemgr.py

Bug fix and code enhancement for EC-RAG
n/a
- [ √] Bug fix (non-breaking change which fixes an issue)
n/a
function test/ api test

minor bug fix for EC-RAG

---

.github/workflows/_example-workflow.yml
ChatQnA/tests/test_compose_vllm_on_gaudi.sh

Before add this version limit to avoid main branch bug, now remove it.

Remove vllm hpu commit id limit 

---

.github/workflows/pr-dockerfile-path-and-build-yaml-scan.yml

Fix CI filter issue

---

WorkflowExecAgent/docker_compose/intel/cpu/xeon/compose_vllm.yaml
WorkflowExecAgent/docker_image_build/build.yaml

update `build.yaml` and `compose_vllm.yaml` because of refactoring of GenAIComps.

update agent example for the GenAIComps changes.

---

DocIndexRetriever/tests/test_compose_on_gaudi.sh
DocIndexRetriever/tests/test_compose_on_xeon.sh
DocIndexRetriever/tests/test_compose_without_rerank_on_xeon.sh

Update DocIndexRetriever CI test scripts: 
1. Add image build condition.
2. Update single branch clone.
Use local registry image during release test. 

Update DocIndexRetriever CI test scripts

---

Text2Image/docker_image_build/build.yaml
Text2Image/tests/test_compose_on_gaudi.sh

Add UT for Text2Image on Gaudi.
https://github.com/opea-project/GenAIExamples/issues/1421.
UT itself.

Add UT for Text2Image on Gaudi

---

MultimodalQnA/tests/test_compose_on_gaudi.sh
MultimodalQnA/tests/test_compose_on_xeon.sh

target https://github.com/opea-project/GenAIExamples/pull/1408

for test only

---

ProductivitySuite/tests/test_compose_on_xeon.sh

Change in FAQGen microservice for content-type header result in CI failure.
https://github.com/opea-project/GenAIExamples/issues/1431
n/a
n/a

ProductivitySuite: Fix FaqGen Microservice CI test fail

---

.github/workflows/_helm-e2e.yml

Fix CD workflow issue
Fix the issue of CD workflow values_files errors.
Test: Validating Output Parameters
Link: https://github.com/opea-project/GenAIExamples/actions/runs/12879512969/job/35907128919
Status: passed

Fix CD workflow issue

---

.github/workflows/_example-workflow.yml
.github/workflows/pr-dockerfile-path-and-build-yaml-scan.yml
AgentQnA/tests/step1_build_images.sh
ChatQnA/tests/test_compose_guardrails_on_gaudi.sh
ChatQnA/tests/test_compose_on_gaudi.sh
ChatQnA/tests/test_compose_on_xeon.sh
ChatQnA/tests/test_compose_pinecone_on_xeon.sh
ChatQnA/tests/test_compose_qdrant_on_xeon.sh
ChatQnA/tests/test_compose_without_rerank_on_gaudi.sh
ChatQnA/tests/test_compose_without_rerank_on_xeon.sh
CodeGen/tests/test_compose_on_gaudi.sh
CodeGen/tests/test_compose_on_rocm.sh
CodeGen/tests/test_compose_on_xeon.sh
CodeTrans/tests/test_compose_on_gaudi.sh
CodeTrans/tests/test_compose_on_rocm.sh
CodeTrans/tests/test_compose_on_xeon.sh
DBQnA/tests/test_compose_on_xeon.sh
DocSum/tests/test_compose_on_rocm.sh
EdgeCraftRAG/tests/test_compose_vllm_on_arc.sh
FaqGen/tests/test_compose_on_gaudi.sh
FaqGen/tests/test_compose_on_rocm.sh
FaqGen/tests/test_compose_on_xeon.sh
InstructionTuning/tests/test_compose_on_xeon.sh

1. Simplify git clone code in CI test.
2. Replace git clone branch in Dockerfile.

Simplify git clone code in CI test

---

.github/workflows/_helm-e2e.yml
.github/workflows/scripts/k8s-utils.sh

- support setting helm version
- introduce wait timeout time during helm install
- dump more k8s information in failure.
`n/a`.

CI: improve helm CI

---

AgentQnA/tests/step1_build_images.sh
AgentQnA/tests/step4_launch_and_validate_agent_tgi.sh
AgentQnA/tests/test_compose_on_gaudi.sh

Use local hub cache for AgentQnA test to save workspace.

Use local hub cache for AgentQnA test

---

AgentQnA/tests/step1_build_images.sh

use `vllm-fork` for gaudi.
fix the issue  https://github.com/opea-project/GenAIExamples/issues/1451

fix wrong vllm repo.

---

ChatQnA/docker_compose/intel/cpu/xeon/README.md

This PR fixes the missing protocol for in the curl command mentioned in chatqna readme for tei-embedding-service.
- [ x] Others (enhancement, documentation, validation, etc.)

[chore/chatqna] Missing protocol in curl command

---

MultimodalQnA/docker_compose/intel/hpu/gaudi/compose.yaml
MultimodalQnA/docker_image_build/build.yaml
MultimodalQnA/tests/test_compose_on_gaudi.sh

Fix multimodal docker image issue for MutimodalQnA on Gaudi
`n/a`
None

Fix multimodal docker image issue for MutimodalQnA on Gaudi

---

ChatQnA/kubernetes/helm/README.md

Update ChatQnA helm chart README.

---

RerankFinetuning/docker_image_build/build.yaml
RerankFinetuning/tests/test_compose_on_gaudi.sh

Added UT for rerank finetuning on Gaudi.
`n/a`.
none.
UT itself.

Added UT for rerank finetuning on Gaudi

---

ChatQnA/docker_compose/intel/hpu/gaudi/README.md
ChatQnA/docker_compose/intel/hpu/gaudi/compose.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_guardrails.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_tgi.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_without_rerank.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/set_env.sh
ChatQnA/tests/test_compose_guardrails_on_gaudi.sh
ChatQnA/tests/test_compose_on_gaudi.sh
ChatQnA/tests/test_compose_tgi_on_gaudi.sh
ChatQnA/tests/test_compose_without_rerank_on_gaudi.sh

Add support for latest deepseek models on Gaudi
`n/a`
None

Add support for latest deepseek models on Gaudi

---

.github/workflows/nightly-docker-build-publish.yml

Restore test code.

---

.github/workflows/manual-docker-publish.yml

Fix publish issue
Link: https://github.com/opea-project/GenAIExamples/actions/runs/13255319890/job/37001084485
Status: passed

Fix publish issue

---

AgentQnA/ui/svelte/README.md

Change Agent UI port in the README 
The UI port 5173 works for me instead of 3000.
Dockerfile also sets 5173 as the UI Port
https://github.com/intel-ai-tce/GenAIExamples/blob/ai_agent_ui/AgentQnA/ui/docker/Dockerfile#L23
`n/a`.
NA
manual test

Update README.md for Agent UI

---

.github/workflows/manual-image-build.yml
.github/workflows/pr-docker-compose-e2e.yml

Fix manual-image-build.yml issue
Link: https://github.com/opea-project/GenAIExamples/actions/runs/13258712448
Status: passed

Fix manual-image-build.yml issue

---

.github/workflows/manual-freeze-tag.yml
.github/workflows/manual-image-build.yml
.github/workflows/pr-docker-compose-e2e.yml
.github/workflows/weekly-update-images.yml

1. Update auto commit account.
2. Fix test condition. 

Update CI/CD workflow

---

ChatQnA/README.md
ChatQnA/tests/test_compose_on_gaudi.sh
ChatQnA/tests/test_compose_on_xeon.sh
ChatQnA/tests/test_compose_tgi_on_gaudi.sh
ChatQnA/tests/test_compose_tgi_on_xeon.sh

a quick fix for test script issue due to name change of telemetry feature yaml files.
https://github.com/opea-project/GenAIExamples/pull/1488
`n/a`.
MA
NA

fix a test script issue due to name change for telemetry yaml files

---

.github/workflows/_run-docker-compose.yml

Update workflow condition and env

Update workflow condition and env

---

ChatQnA/benchmark_chatqna.yaml
README-deploy-benchmark.md
deploy.py
deploy_and_benchmark.py

This is to enhance the deploy process of deploy_and_benchmark on vllm, rerank/no-rerank and batch size support, also update README.

Enhance deploy

---

.github/workflows/_helm-e2e.yml
.github/workflows/manual-docker-scan.yml
.github/workflows/manual-reset-local-registry.yml
.github/workflows/push-image-build.yml
AgentQnA/docker_compose/intel/hpu/gaudi/compose.yaml

1.Fix docker images BoM/CVE scan
2.Fix Clean up Local Registry on manual event workflow
3.Fix helm test For Call workflow
4.Fix Build latest images on push event workflow
https://github.com/opea-project/GenAIExamples/issues/1529
Test: Test docker image scan
Link: https://github.com/opea-project/GenAIExamples/actions/runs/13298122740/job/37134465370
Status: passed
Test: Helm Pr test
Link: https://github.com/opea-project/GenAIExamples/actions/runs/13298815931/job/37136383565?pr=1533
Status: Passed
Test: Build latest images on push event
Link: https://github.com/opea-project/GenAIExamples/actions/runs/13299349663/job/37137839993 …

Fix CICD workflow

---

deploy_and_benchmark.py

Provide the number of nodes to benchmark.py, as it needs this value to calculate the number of requests to be simulated.

Pass the number of nodes to benchmark

---

.github/workflows/_example-workflow.yml
ChatQnA/tests/test_compose_on_xeon.sh
ChatQnA/tests/test_compose_pinecone_on_xeon.sh
ChatQnA/tests/test_compose_qdrant_on_xeon.sh
ChatQnA/tests/test_compose_without_rerank_on_xeon.sh
WorkflowExecAgent/tests/2_start_vllm_service.sh

update vLLM CPU to latest stable version
default vllm main branch are in development and changed from time to time. It may be broken sometimes.
https://github.com/opea-project/GenAIExamples/issues/1532
https://github.com/opea-project/GenAIExamples/issues/1519
test local, vLLM works as expecte on multiple CPUs.

update vLLM CPU to the latest stable version

---

ChatQnA/docker_compose/intel/cpu/aipc/set_env.sh

Fix mismatched environment variable
- [X ] Others (enhancement, documentation, validation, etc.)
No
locally passed test.

Fix mismatched environment variable

---

ChatQnA/benchmark_chatqna.yaml
benchmark.py

Refine benchmark to load eval_path dynamically.
Allow dataset to be null.
Fix other minor issues/setting.
n/a
None
Local tested

Refine benchmark.py

---

ChatQnA/docker_compose/intel/cpu/aipc/README.md

Update README.md of AIPC quick start part for good user experience

Update README.md of AIPC quick start

---

README.md

Add a link to the github.io documentation for OPEA. Reference the sample guides on the github.io for deployment.
n/a
None.
Documentation only, no tests needed.

Top level README: add link to github.io documentation

---

.github/workflows/manual-example-workflow.yml

Fix cd workflow condition 
https://github.com/opea-project/GenAIExamples/actions/runs/13566111674/job/37919523636

Fix cd workflow condition 

---

ChatQnA/docker_compose/amd/gpu/rocm/compose.yaml
ChatQnA/docker_compose/intel/cpu/xeon/compose.yaml
ChatQnA/docker_compose/intel/cpu/xeon/compose_pinecone.yaml
ChatQnA/docker_compose/intel/cpu/xeon/compose_qdrant.yaml
ChatQnA/docker_compose/intel/cpu/xeon/compose_tgi.yaml
ChatQnA/docker_compose/intel/cpu/xeon/compose_without_rerank.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_guardrails.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_tgi.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_without_rerank.yaml
ChatQnA/tests/test_compose_guardrails_on_gaudi.sh
ChatQnA/tests/test_compose_on_gaudi.sh
ChatQnA/tests/test_compose_on_rocm.sh
ChatQnA/tests/test_compose_on_xeon.sh
ChatQnA/tests/test_compose_pinecone_on_xeon.sh
ChatQnA/tests/test_compose_qdrant_on_xeon.sh
ChatQnA/tests/test_compose_tgi_on_gaudi.sh
ChatQnA/tests/test_compose_tgi_on_xeon.sh
ChatQnA/tests/test_compose_without_rerank_on_gaudi.sh
ChatQnA/tests/test_compose_without_rerank_on_xeon.sh

Enable ChatQnA model cache for docker compose test.

Enable ChatQnA model cache for docker compose test.

---

SearchQnA/docker_compose/amd/gpu/rocm/compose.yaml
SearchQnA/docker_compose/intel/cpu/xeon/compose.yaml
SearchQnA/docker_compose/intel/hpu/gaudi/compose.yaml
SearchQnA/tests/test_compose_on_gaudi.sh
SearchQnA/tests/test_compose_on_rocm.sh
SearchQnA/tests/test_compose_on_xeon.sh

Enable SearchQnA model cache for docker compose test.

Enable SearchQnA model cache for docker compose test.

---

EdgeCraftRAG/Dockerfile.server
EdgeCraftRAG/edgecraftrag/requirements.txt
EdgeCraftRAG/ui/docker/Dockerfile.ui

Fix docker image opea/edgecraftrag security issue
https://github.com/opea-project/GenAIExamples/issues/1577
- [ √] Bug fix (non-breaking change which fixes an issue)

Fix docker image opea/edgecraftrag security issue #1577

---

SearchQnA/docker_compose/amd/gpu/rocm/compose.yaml
SearchQnA/docker_compose/intel/cpu/xeon/compose.yaml
SearchQnA/docker_compose/intel/hpu/gaudi/compose.yaml

Update compose.yaml for SearchQnA

Update compose.yaml for SearchQnA

---

ChatQnA/docker_compose/amd/gpu/rocm/compose.yaml
ChatQnA/docker_compose/intel/cpu/xeon/compose.yaml
ChatQnA/docker_compose/intel/cpu/xeon/compose_pinecone.yaml
ChatQnA/docker_compose/intel/cpu/xeon/compose_qdrant.yaml
ChatQnA/docker_compose/intel/cpu/xeon/compose_tgi.yaml
ChatQnA/docker_compose/intel/cpu/xeon/compose_without_rerank.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_guardrails.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_tgi.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_without_rerank.yaml

Update compose.yaml for ChatQnA

Update compose.yaml for ChatQnA

---

README.md

Fixes the introduction in GenAIExamples main README
Fixes #112
Co-authored-by: Piroozan, Nariman <nariman.piroozan@intel.com>
Signed-off-by:  Ghosh, Soumyadip <soumyadip.ghosh@intel.com>
Signed-off-by:  Jaini, Pallavi <pallavi.jaini@intel.com>
Signed-off-by: Kavulya, Soila <soila.kavulya@intel.com>
Signed-off-by: Rajabose, Shifani <shifani.rajabose@intel.com>
Fixes the introduction in GenAIExamples main README
https://github.com/opea-project/docs/issues/112
- [* ] Others (enhancement, documentation, validation, etc.)
n/a
the page should be visible in 
https://opea-project.github.io/latest/examples/examples.html

[Bug: 112] Fix introduction in GenAIExamples main README

---

.github/workflows/scripts/get_test_matrix.sh

Fix corner CI issue when the example path deleted
https://github.com/opea-project/GenAIExamples/actions/runs/13692095197/job/38287000987?pr=1603#step:5:57

Fix corner CI issue when the example path deleted

---

.github/workflows/_example-workflow.yml
AgentQnA/tests/step1_build_images.sh
ChatQnA/tests/test_compose_guardrails_on_gaudi.sh
ChatQnA/tests/test_compose_on_gaudi.sh
ChatQnA/tests/test_compose_without_rerank_on_gaudi.sh
CodeTrans/tests/test_compose_on_gaudi.sh

Use the latest HabanaAI/vllm-fork release tag to build and release opea/vllm-gaudi:latest image. 

Use the latest HabanaAI/vllm-fork release tag to build vllm-gaudi image

---

ChatQnA/docker_compose/intel/cpu/xeon/compose_milvus.yaml
ChatQnA/tests/test_compose_guardrails_on_gaudi.sh
ChatQnA/tests/test_compose_milvus_on_xeon.sh
ChatQnA/tests/test_compose_qdrant_on_xeon.sh
ChatQnA/tests/test_compose_tgi_on_gaudi.sh
ChatQnA/tests/test_compose_tgi_on_xeon.sh
ChatQnA/tests/test_compose_without_rerank_on_gaudi.sh
ChatQnA/tests/test_compose_without_rerank_on_xeon.sh

1. Enhance validate response checking.
2. Add model cache for milvus test. 

Enhance ChatQnA test scripts

---

.github/workflows/daily_check_issue.yml
.github/workflows/daily_check_issue_and_pr.yml

Add GitHub Action to check and close stale issues and PRs
https://github.com/opea-project/GenAIExamples/issues/1633#event-16626809181
No
CI

Add GitHub Action to check and close stale issues and PRs

---

.github/workflows/nightly-docker-build-publish.yml

Enable inject_commit to docker image feature.

Enable inject_commit to docker image feature.

---

CodeGen/docker_compose/intel/cpu/xeon/README.md
CodeGen/docker_compose/intel/cpu/xeon/compose.yaml
CodeGen/docker_compose/intel/hpu/gaudi/README.md
CodeGen/docker_compose/intel/hpu/gaudi/compose.yaml
CodeGen/docker_compose/set_env.sh
CodeGen/docker_image_build/build.yaml
CodeGen/tests/test_compose_on_gaudi.sh
CodeGen/tests/test_compose_on_xeon.sh

vLLM service
Eanble CodeGen vLLM
N/A
No
local Test passed.

Enable CodeGen vLLM

---

GraphRAG/docker_compose/intel/hpu/gaudi/compose.yaml
GraphRAG/tests/test_compose_on_gaudi.sh
ProductivitySuite/docker_compose/intel/cpu/xeon/compose.yaml
ProductivitySuite/tests/test_compose_on_xeon.sh

Enable GraphRAG and ProductivitySuite model cache for docker compose test.

Enable GraphRAG and ProductivitySuite model cache for docker compose test.

---

.github/workflows/daily_check_issue_and_pr.yml

Update stale issue and PR settings to 30 days for inactivity
`n/a`

Update stale issue and PR settings to 30 days for inactivity

---

.github/workflows/_example-workflow.yml
.github/workflows/manual-example-workflow.yml
.github/workflows/manual-image-build.yml

Fix input issue for manual-image-build.yml
https://github.com/opea-project/GenAIExamples/actions/runs/13889729080
NA
https://github.com/opea-project/GenAIExamples/actions/runs/13890272677/job/38860948673
https://github.com/opea-project/GenAIExamples/actions/runs/13891196709

Fix input issue for manual-image-build.yml

---

.github/workflows/_run-docker-compose.yml

Fix workflow issues.
Test Link: https://github.com/opea-project/GenAIExamples/actions/runs/13921236444

Fix workflow issues.

---

.github/workflows/_build_image.yml
.github/workflows/_example-workflow.yml

Fix CD cancel issue.
Test links: 
https://github.com/opea-project/GenAIExamples/actions/runs/14027381138
Status: Cancel succeed

Fix CD cancel issue

---

AgentQnA/docker_compose/intel/cpu/xeon/compose_openai.yaml

issue fix for a typo for agent on Xeon
`n/a`.
NA
NA

typo for docker image

---

ChatQnA/README.md

Better to have table of contents for the growing contents in README
`n/a`.
NA
NA

Update README.md to have Table for contents

---

.github/workflows/_helm-e2e.yml

Fix model cache path and use Random to avoid ns conflict

---

benchmark.py

Add model environment variable

Add model environment variable

---

.github/workflows/pr-link-path-scan.yml
ChatQnA/README.md

Fix relative path validity issue in readme 
Test link: http://github.com/opea-project/GenAIExamples/actions/runs/14239088436/job/39904631517?pr=1750
Status: passed

Fix relative path validity issue 

---

AudioQnA/tests/test_compose_multilang_on_xeon.sh

Add multilang tts test
https://github.com/opea-project/GenAIInfra/issues/922
na
ut

Add AudioQnA multilang tts test

---

FinanceAgent/docker_compose/intel/hpu/gaudi/compose.yaml
FinanceAgent/prompts/research_prompt.py
FinanceAgent/tests/test_compose_on_gaudi.sh
FinanceAgent/tools/research_agent_tools.yaml
FinanceAgent/tools/research_tools.py

1. add financial research prompt
2. add tools to get data source from `finnhub`

Add financial research agent.

---

ChatQnA/docker_compose/intel/cpu/xeon/grafana/dashboards/download_opea_dashboard.sh
ChatQnA/docker_compose/intel/cpu/xeon/set_env.sh
ChatQnA/docker_compose/intel/hpu/gaudi/compose.telemetry.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_tgi.telemetry.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/grafana/dashboards/download_opea_dashboard.sh
ChatQnA/docker_compose/intel/hpu/gaudi/set_env.sh

Getting most of the updated Grafana Dashboard for ChatQnA
Gaudi2 Snapshot running GenAIEval
https://snapshots.raintank.io/dashboard/snapshot/WC02g0ZugBYibM6I177TGsVEu3PktIZ1?orgId=0&refresh=5s
https://snapshots.raintank.io/dashboard/snapshot/SAJFc4xELoEt8417yXsEvTgb0tKQG8Jk?orgId=0
https://snapshots.raintank.io/dashboard/snapshot/heUhMVzHffbuMKGZH9rp39dYohQmDzhA?orgId=0&refresh=1m
https://snapshots.raintank.io/dashboard/snapshot/vv9k6CqWHdSCG7xSxTWDnz1g1wL1RjgZ?orgId=0
https://snapshots.raintank.io/dashboard/snapshot/iMELRy0JH2KT5cXLYaZ3luvKPYjQqrXE?orgId=0&refresh=5s
`n/a`.
NA
manually testing

[ChatQnA] update to the latest Grafana Dashboard

---

.github/workflows/_build_image.yml
.github/workflows/pr-docker-compose-e2e.yml
AgentQnA/tests/step1_build_images.sh
AudioQnA/docker_compose/intel/cpu/xeon/README.md
AudioQnA/docker_compose/intel/hpu/gaudi/README.md
AudioQnA/tests/test_compose_multilang_on_xeon.sh
AudioQnA/tests/test_compose_on_gaudi.sh
AudioQnA/tests/test_compose_on_xeon.sh
ChatQnA/tests/test_compose_faqgen_on_gaudi.sh
ChatQnA/tests/test_compose_faqgen_on_xeon.sh
ChatQnA/tests/test_compose_faqgen_tgi_on_xeon.sh
ChatQnA/tests/test_compose_guardrails_on_gaudi.sh
ChatQnA/tests/test_compose_milvus_on_xeon.sh
ChatQnA/tests/test_compose_on_gaudi.sh
ChatQnA/tests/test_compose_on_xeon.sh
ChatQnA/tests/test_compose_pinecone_on_xeon.sh
ChatQnA/tests/test_compose_qdrant_on_xeon.sh
ChatQnA/tests/test_compose_without_rerank_on_gaudi.sh
ChatQnA/tests/test_compose_without_rerank_on_xeon.sh
CodeGen/tests/test_compose_on_gaudi.sh
CodeGen/tests/test_compose_on_xeon.sh
CodeTrans/tests/test_compose_on_gaudi.sh
CodeTrans/tests/test_compose_on_xeon.sh
DocSum/tests/test_compose_on_gaudi.sh
DocSum/tests/test_compose_on_xeon.sh
WorkflowExecAgent/tests/2_start_vllm_service.sh

Limit vllm and vllm-fork tags

---

.github/workflows/_run-docker-compose.yml

Add dockerhub login step to avoid 429 Too Many Requests

Add dockerhub login step to avoid 429 Too Many Requests

---

.github/workflows/_run-docker-compose.yml
.github/workflows/scripts/docker_compose_clean_up.sh

fix docker image clean up issue
https://github.com/opea-project/GenAIExamples/actions/runs/14331395637/job/40168067273

fix docker image clean up issue

---

CodeGen/README.md

Fix typo in CodeGen README
`n/a`
None
Just document change

Fix typo in CodeGen README

---

.github/ISSUE_TEMPLATE/1_bug_template.yml
.github/ISSUE_TEMPLATE/2_feature_template.yml

Add 'N/A' in template options.
https://github.com/opea-project/GenAIExamples/issues/1002.

add 'N/A' to option

---

AgentQnA/kubernetes/helm/cpu-values.yaml
AgentQnA/kubernetes/helm/gaudi-values.yaml
AudioQnA/docker_compose/intel/hpu/gaudi/compose.yaml
AudioQnA/kubernetes/helm/gaudi-values.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_faqgen.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_guardrails.yaml
ChatQnA/docker_compose/intel/hpu/gaudi/compose_without_rerank.yaml
ChatQnA/kubernetes/helm/faqgen-gaudi-values.yaml
ChatQnA/kubernetes/helm/gaudi-values.yaml
ChatQnA/kubernetes/helm/guardrails-gaudi-values.yaml
CodeTrans/docker_compose/intel/hpu/gaudi/compose.yaml
CodeTrans/kubernetes/helm/gaudi-values.yaml
DocSum/docker_compose/intel/hpu/gaudi/compose.yaml
DocSum/kubernetes/helm/gaudi-values.yaml

`--max-seq_len-to-capture` need to be updated by `--max-seq-len-to-capture`.
https://github.com/opea-project/GenAIExamples/issues/1805
None
CI test

Update vLLM parameter max-seq-len-to-capture

---

ChatQnA/tests/test_compose_faqgen_on_gaudi.sh
ChatQnA/tests/test_compose_faqgen_on_rocm.sh
ChatQnA/tests/test_compose_faqgen_on_xeon.sh
ChatQnA/tests/test_compose_faqgen_tgi_on_gaudi.sh
ChatQnA/tests/test_compose_faqgen_tgi_on_xeon.sh
ChatQnA/tests/test_compose_faqgen_vllm_on_rocm.sh
ChatQnA/tests/test_compose_guardrails_on_gaudi.sh
ChatQnA/tests/test_compose_milvus_on_xeon.sh
ChatQnA/tests/test_compose_on_gaudi.sh
ChatQnA/tests/test_compose_on_rocm.sh
ChatQnA/tests/test_compose_on_xeon.sh
ChatQnA/tests/test_compose_pinecone_on_xeon.sh
ChatQnA/tests/test_compose_qdrant_on_xeon.sh
ChatQnA/tests/test_compose_tgi_on_gaudi.sh
ChatQnA/tests/test_compose_tgi_on_xeon.sh
ChatQnA/tests/test_compose_vllm_on_rocm.sh
ChatQnA/tests/test_compose_without_rerank_on_gaudi.sh
ChatQnA/tests/test_compose_without_rerank_on_xeon.sh

Group log lines in GHA outputs for better readable logs, fix typo. 

Group log lines in GHA outputs for better readable logs.

---

ChatQnA/docker_compose/intel/hpu/gaudi/README.md
ChatQnA/docker_compose/intel/hpu/gaudi/compose_guardrails.yaml
ChatQnA/tests/test_compose_guardrails_on_gaudi.sh

Replaced TGI with vLLM for guardrail serving
`n/a`
None
CI test

Replaced TGI with vLLM for guardrail serving

---

MultimodalQnA/docker_compose/amd/gpu/rocm/compose.yaml
ProductivitySuite/docker_compose/intel/cpu/xeon/compose.yaml
ProductivitySuite/tests/test_compose_on_xeon.sh

Fix failed CI issues of https://github.com/opea-project/GenAIExamples/pull/1800

Fix Multimodal & ProductivitySuite Issue

---

EdgeCraftRAG/edgecraftrag/requirements.txt

Fix missing python package caused by third-party software update
n/a
- [ √] Bug fix (non-breaking change which fixes an issue)

fix missing package

---

ChatQnA/README.md
ChatQnA/README_miscellaneous.md

Redirect users to github io for opentelemetry usage
`n/a`.
na
na

Redirect Users to github.io for ChatQnA telemetry materials

---

DocSum/README.md
DocSum/README_miscellaneous.md
DocSum/docker_compose/amd/gpu/rocm/README.md
DocSum/docker_compose/intel/cpu/xeon/README.md
DocSum/docker_compose/intel/hpu/gaudi/README.md
DocSum/docker_compose/set_env.sh

Refine documents for DocSum to align with new template

Refine documents for DocSum

---

ChatQnA/kubernetes/helm/cpu-milvus-values.yaml
ChatQnA/kubernetes/helm/cpu-values.yaml
ChatQnA/kubernetes/helm/guardrails-gaudi-values.yaml

Update value files from GenAIInfra to Examples

Update chatqna values file changes

---

EdgeCraftRAG/Dockerfile.server

permission issue due to third party software update
n/a
- [ √] Bug fix (non-breaking change which fixes an issue)

hot fix for permission issue

---

AgentQnA/tests/test_compose_on_gaudi.sh
AudioQnA/Dockerfile
AudioQnA/Dockerfile.multilang
AudioQnA/docker_image_build/build.yaml
AudioQnA/tests/test_compose_multilang_on_xeon.sh
AudioQnA/tests/test_compose_on_gaudi.sh
AudioQnA/tests/test_compose_on_rocm.sh
AudioQnA/tests/test_compose_on_xeon.sh
AudioQnA/tests/test_compose_tgi_on_gaudi.sh
AudioQnA/tests/test_compose_tgi_on_xeon.sh
AudioQnA/tests/test_compose_vllm_on_rocm.sh
AudioQnA/tests/test_gmc_on_gaudi.sh
AudioQnA/tests/test_gmc_on_xeon.sh

[CICD enhance] AudioQnA run CI with latest base image, group logs in GHA outputs.

---

AudioQnA/Dockerfile
AudioQnA/Dockerfile.multilang
EdgeCraftRAG/Dockerfile
EdgeCraftRAG/docker_compose/intel/gpu/arc/compose_vllm.yaml
EdgeCraftRAG/docker_image_build/build.yaml
EdgeCraftRAG/tests/test_compose_on_arc.sh
EdgeCraftRAG/tests/test_compose_vllm_on_arc.sh

[CICD enhance] EdgeCraftRAG run CI with latest base image, group logs in GHA outputs.

[CICD enhance] EdgeCraftRAG run CI with latest base image, group logs in GHA outputs.

---

FinanceAgent/README.md

missing required env vars settings in readme and fix a path

README fixes Finance Example

---

ChatQnA/benchmark_chatqna.yaml
DocSum/benchmark_docsum.yaml
README-deploy-benchmark.md
deploy.py
deploy_and_benchmark.py
requirements.txt

- Update benchmark helm charts version. 
- Update benchmark readme. 

Update benchmark scripts

---

.github/CODEOWNERS

Remove invalid codeowner.

---

.github/CODEOWNERS

update PR reviewers

---

DocSum/kubernetes/helm/README.md

Update doc script paths to match https://github.com/opea-project/GenAIInfra/pull/1041.
`n/a`.
`n/a`.
`n/a`.

Update paths to GenAIInfra scripts

---

.github/workflows/daily-update-vllm-version.yml

set fail-fast to false in vLLM update actions

set fail-fast to false in vLLM update actions

---

DocIndexRetriever/docker_compose/intel/cpu/xeon/set_env.sh
DocIndexRetriever/docker_compose/intel/hpu/gaudi/set_env.sh
DocIndexRetriever/tests/README.md
DocIndexRetriever/tests/test_compose_milvus_on_gaudi.sh
DocIndexRetriever/tests/test_compose_milvus_on_xeon.sh
DocIndexRetriever/tests/test_compose_on_gaudi.sh
DocIndexRetriever/tests/test_compose_on_xeon.sh

Integrate DocIndexRetriever set_env to ut scripts.
Add README.md for UT scripts.

Integrate DocIndexRetriever set_env to ut scripts.

---

AvatarChatbot/Dockerfile
AvatarChatbot/docker_image_build/build.yaml
AvatarChatbot/tests/test_compose_on_gaudi.sh
AvatarChatbot/tests/test_compose_on_rocm.sh
AvatarChatbot/tests/test_compose_on_xeon.sh

[CICD enhance] AvatarChatbot run CI with latest base image, group logs in GHA outputs.

---

.github/workflows/_run-docker-compose.yml
ChatQnA/tests/test_compose_mariadb_on_xeon.sh
VisualQnA/Dockerfile
VisualQnA/docker_image_build/build.yaml
VisualQnA/tests/test_compose_on_gaudi.sh
VisualQnA/tests/test_compose_on_rocm.sh
VisualQnA/tests/test_compose_on_xeon.sh
VisualQnA/tests/test_compose_tgi_on_gaudi.sh
VisualQnA/tests/test_compose_tgi_on_xeon.sh
VisualQnA/tests/test_compose_vllm_on_rocm.sh

1. Specify image build list for VisualQnA.
2. Fix docker clean up function.
3. Enable latest base image test for CI.
4. Group log lines in GHA outputs for better readable logs.

Specify image build list for VisualQnA

---

.github/workflows/pr-link-path-scan.yml

Reduce the verification delay time to 1s

Reduce the verification delay time to 1s

---

CodeGen/tests/test_compose_on_gaudi.sh
CodeGen/tests/test_compose_on_xeon.sh

Add tests for different input formats

---

.github/workflows/_example-workflow.yml
.github/workflows/manual-example-workflow.yml
.github/workflows/manual-image-build.yml
.github/workflows/manual-reset-local-registry.yml
.github/workflows/nightly-docker-build-publish.yml
.github/workflows/push-image-build.yml
.github/workflows/weekly-example-test.yml
AudioQnA/docker_image_build/build.yaml

Fix workflow permission issues for nightly, weekly, CD, push-image-build, manual-reset-local-registry and manual-image-build.
https://github.com/opea-project/GenAIExamples/actions/runs/15407412265
https://github.com/opea-project/GenAIExamples/actions/runs/15406636495
https://github.com/opea-project/GenAIExamples/actions/runs/15406509235
https://github.com/opea-project/GenAIExamples/actions/runs/15406932447
https://github.com/opea-project/GenAIExamples/actions/runs/15406986580
https://github.com/opea-project/GenAIExamples/actions/runs/15407079184

Fix workflow permission issues.

---

MultimodalQnA/tests/test_compose_milvus_on_xeon.sh
MultimodalQnA/tests/test_compose_on_xeon.sh

Fix MultimodalQnA UT issues

---

AudioQnA/benchmark/accuracy/run_acc.sh
AudioQnA/docker_compose/amd/gpu/rocm/README.md
AudioQnA/docker_compose/amd/gpu/rocm/compose.yaml
AudioQnA/docker_compose/amd/gpu/rocm/compose_vllm.yaml
AudioQnA/docker_compose/amd/gpu/rocm/set_env.sh
AudioQnA/docker_compose/amd/gpu/rocm/set_env_vllm.sh
AudioQnA/docker_compose/intel/cpu/xeon/README.md
AudioQnA/docker_compose/intel/cpu/xeon/README_vllm.md
AudioQnA/docker_compose/intel/cpu/xeon/compose.yaml
AudioQnA/docker_compose/intel/cpu/xeon/compose_multilang.yaml
AudioQnA/docker_compose/intel/cpu/xeon/compose_tgi.yaml
AudioQnA/docker_compose/intel/cpu/xeon/set_env.sh
AudioQnA/docker_compose/intel/hpu/gaudi/README.md
AudioQnA/docker_compose/intel/hpu/gaudi/compose.yaml
AudioQnA/docker_compose/intel/hpu/gaudi/compose_tgi.yaml
AudioQnA/docker_compose/intel/hpu/gaudi/set_env.sh
AudioQnA/kubernetes/helm/README.md
AudioQnA/tests/README.md
README-deploy-benchmark.md
deploy.py
deploy_and_benchmark.py

update secrets token name for AudioQnA.
Fix Shellcheck issues
https://github.com/opea-project/GenAIExamples/issues/1954
https://github.com/opea-project/GenAIExamples/issues/1999

update secrets token name for AudioQnA.

---

AvatarChatbot/docker_compose/amd/gpu/rocm/README.md
AvatarChatbot/docker_compose/amd/gpu/rocm/compose.yaml
AvatarChatbot/docker_compose/amd/gpu/rocm/set_env.sh
AvatarChatbot/docker_compose/intel/cpu/xeon/README.md
AvatarChatbot/docker_compose/intel/cpu/xeon/compose.yaml
AvatarChatbot/docker_compose/intel/cpu/xeon/set_env.sh
AvatarChatbot/docker_compose/intel/hpu/gaudi/README.md
AvatarChatbot/docker_compose/intel/hpu/gaudi/compose.yaml
AvatarChatbot/docker_compose/intel/hpu/gaudi/set_env.sh
AvatarChatbot/tests/README.md
DBQnA/docker_compose/amd/gpu/rocm/README.md
DBQnA/docker_compose/amd/gpu/rocm/set_env.sh
DBQnA/docker_compose/intel/cpu/xeon/README.md
DBQnA/docker_compose/intel/cpu/xeon/compose.yaml
DBQnA/docker_compose/intel/cpu/xeon/set_env.sh
DBQnA/tests/README.md

update secrets token name for AvatarChatbot and DBQnA.
https://github.com/opea-project/GenAIExamples/issues/1954

update secrets token name for AvatarChatbot and DBQnA.

---

CodeGen/codegen.py
CodeGen/tests/test_compose_on_xeon.sh

Fix CodeGen non stream output issue

---

GraphRAG/Dockerfile
GraphRAG/docker_image_build/build.yaml
GraphRAG/tests/test_compose_on_gaudi.sh

[CICD enhance] GraphRAG run CI with latest base image, group logs in GHA outputs.

[CICD enhance] GraphRAG run CI with latest base image, group logs in GHA outputs.

---

DocSum/tests/test_compose_on_gaudi.sh
DocSum/tests/test_compose_on_rocm.sh
DocSum/tests/test_compose_on_xeon.sh
DocSum/tests/test_compose_tgi_on_gaudi.sh
DocSum/tests/test_compose_tgi_on_xeon.sh
DocSum/tests/test_compose_vllm_on_rocm.sh

[CICD enhance] DocSum group logs in GHA outputs.

[CICD enhance] DocSum group logs in GHA outputs.

---

HybridRAG/tests/test_compose_on_gaudi.sh
ProductivitySuite/docker_image_build/build.yaml
ProductivitySuite/tests/test_compose_on_xeon.sh

[CICD enhance] ProductivitySuite run CI with latest base image, group logs in GHA outputs.

[CICD enhance] ProductivitySuite run CI with latest base image, group logs in GHA outputs.

---

InstructionTuning/tests/test_compose_on_xeon.sh
MultimodalQnA/Dockerfile
MultimodalQnA/docker_image_build/build.yaml
MultimodalQnA/tests/test_compose_milvus_on_xeon.sh
MultimodalQnA/tests/test_compose_on_gaudi.sh
MultimodalQnA/tests/test_compose_on_rocm.sh
MultimodalQnA/tests/test_compose_on_xeon.sh
MultimodalQnA/tests/test_compose_vllm_on_rocm.sh
RerankFinetuning/tests/test_compose_on_gaudi.sh
RerankFinetuning/tests/test_compose_on_xeon.sh

1. InstructionTuning, RerankFinetuning log group. 
2. MultimodalQnA run CI with latest base image, group logs in GHA outputs.

[CICD enhance] run CI with latest base image, group logs in GHA outputs. 

---

AvatarChatbot/README.md
AvatarChatbot/docker_compose/intel/cpu/xeon/README.md
AvatarChatbot/docker_compose/intel/hpu/gaudi/README.md

Refine documents for AvatarChatbot.
https://github.com/opea-project/GenAIExamples/issues/1679

Refine documents for AvatarChatbot.

---

deploy.py

Current helm charts template still use HUGGINGFACEHUB_API_TOKEN, so revert this change to fix benchmark issue. 

support current helm charts template

---

.github/workflows/_helm-e2e.yml

helm CI: create LOG_PATH directory.
`n/a`.

helm CI: create LOG_PATH directory

---

.github/workflows/push-infra-issue-creation.yml
WorkflowExecAgent/tests/example_workflow/Dockerfile.example_workflow_api

use upstream action tool

---

.github/workflows/pr-docker-compose-e2e.yml

update test trigger path with requirements.txt

update test trigger path

---

.github/workflows/_get-test-matrix.yml
.github/workflows/pr-docker-compose-e2e.yml

update get test matrix scope

---

RerankFinetuning/README.md
RerankFinetuning/docker_compose/intel/cpu/xeon/README.md
RerankFinetuning/docker_compose/intel/hpu/gaudi/README.md

Refine RerankFinetuning Readmes
n/a
None
None

Refine RerankFinetuning Readmes

---

.github/workflows/scripts/codeScan/hadolint.sh
ChatQnA/Dockerfile.openEuler
ChatQnA/ui/docker/Dockerfile.openEuler

Fix hadolint scan bugs

---

ChatQnA/docker_compose/intel/cpu/xeon/compose_openeuler.yaml

Fix the version of vllm

---

ChatQnA/docker_compose/amd/cpu/epyc/README.md
ChatQnA/docker_compose/amd/cpu/epyc/README_qdrant.md
ChatQnA/docker_compose/amd/cpu/epyc/compose_milvus.yaml
ChatQnA/docker_compose/amd/cpu/epyc/compose_qdrant.yaml
ChatQnA/docker_compose/amd/cpu/epyc/compose_without_rerank.yaml
ChatQnA/tests/README.md
ChatQnA/tests/test_compose_milvus_on_epyc.sh
ChatQnA/tests/test_compose_on_epyc.sh
ChatQnA/tests/test_compose_qdrant_on_epyc.sh
ChatQnA/tests/test_compose_tgi_on_epyc.sh
ChatQnA/tests/test_compose_without_rerank_on_epyc.sh

This PR introduces support for AMD EPYC servers by providing Docker container configurations, environment setup scripts, and updated documentation.
- Added Dockerfiles specific to AMD EPYC for the following ChatQnA use cases: Milvus, without_rerank, TGI, VLLM, and Qdrant.
- Introduced set_env.sh scripts tailored for AMD EPYC deployment.
- Made adjustments to environment variables for smoother integration.
- Updated the README files to include deployment instructions for AMD EPYC servers.
- Added guidance for environment setup and troubleshooting on AMD servers.

Support for ChatQnA Docker Containers

---

ChatQnA/docker_compose/intel/cpu/xeon/compose_openeuler.yaml

Update text-embeddings-inference to 1.7.0

---

GraphRAG/README.md
GraphRAG/docker_compose/intel/hpu/gaudi/README.md

Refine documents for GraphRAG

---

VideoQnA/README.md
VideoQnA/docker_compose/intel/cpu/xeon/README.md

Refine VideoQnA READMEs

---

.github/workflows/manual-example-workflow.yml
ChatQnA/docker_image_build/build.yaml

Remove invalid image ${REGISTRY:-opea}/guardrails:${TAG:-latest}-openeuler 

Remove invalid image

---

CodeGen/ui/docker/Dockerfile.gradio
EdgeCraftRAG/Dockerfile.server
MultimodalQnA/ui/docker/Dockerfile

Remove libgl1-mesa-glx from Dockerfiles
https://github.com/opea-project/GenAIComps/issues/1781

Remove libgl1-mesa-glx from Dockerfiles

---

AgentQnA/kubernetes/helm/rocm-tgi-values.yaml
AgentQnA/kubernetes/helm/rocm-values.yaml
ChatQnA/kubernetes/helm/faqgen-gaudi-tgi-values.yaml
ChatQnA/kubernetes/helm/faqgen-gaudi-values.yaml
ChatQnA/kubernetes/helm/faqgen-rocm-tgi-values.yaml
ChatQnA/kubernetes/helm/faqgen-rocm-values.yaml
ChatQnA/kubernetes/helm/gaudi-tgi-values.yaml
ChatQnA/kubernetes/helm/gaudi-values.yaml
ChatQnA/kubernetes/helm/guardrails-gaudi-values.yaml
ChatQnA/kubernetes/helm/rocm-tgi-values.yaml
ChatQnA/kubernetes/helm/rocm-values.yaml
SearchQnA/kubernetes/helm/gaudi-values.yaml

Sync helm charts values with GenAIInfra for v1.4 release. 

Sync helm charts values with GenAIInfra

---

ChatQnA/kubernetes/helm/README.md
validated_configurations.md

Update v1.4 Release Test Config

Update v1.4 Release Test Config

---

CodeGen/Dockerfile.openEuler
CodeGen/docker_compose/intel/cpu/xeon/compose_openeuler.yaml
CodeGen/docker_compose/intel/cpu/xeon/compose_tgi_openeuler.yaml
CodeGen/docker_image_build/build.yaml
CodeGen/tests/test_compose_openeuler_on_xeon.sh
CodeGen/ui/docker/Dockerfile.gradio.openEuler
CodeGen/ui/docker/Dockerfile.openEuler
CodeGen/ui/docker/Dockerfile.react.openEuler

openEuler is an open source OS run by the OpenAtom Foundation that builds a global community to enhance digital infrastructure and support diverse architectures.
This PR adds support for openEuler-based container images to CodeGen by introducing Dockerfiles that use openEuler as the base image instead of the current Ubuntu/Alpine base images.
**Benefits of this change**:
- Provides alternative base image option for users preferring openEuler ecosystem
- Enhances compatibility with openEuler-based Kubernetes clusters
- Supports diverse enterprise environments that standardize on openEuler
- Maintains feature parity with existing images while offering different base OS option
The changes include:
- New Dockerfiles using openEuler base images for core CodeGen components
- Updated package …

Add openEuler support for CodeGen

---

.github/workflows/weekly-one-click-test.yml

Exclude AudioQnA k8s test
