- ChatQnA/langchain/docker/docker-compose.yml
- ChatQnA/langchain/docker/requirements.txt
- ChatQnA/langchain/redis/ingest_wiki.py
feature - add wikiQnA
Enable WikiQnA to empower enterprise to use internal wiki resources, such as Intel EnterpriseWiki. Access token is passed from environment variable with on premise deployment to safeguard customer's secrets. 
It's tested on Intel Enterprise Wiki information RAG. 
Add "atlassian-python-api" library to support Enterprise Wiki read using wiki_url and page_ids.
> Enable WikiQnA to empower enterprise to use  internal wiki resources for RAG.

- .github/workflows/ChatQnA_gaudi.yml
- .github/workflows/ChatQnA_xeon.yml
- ChatQnA/tests/test_chatqna_on_gaudi.sh
- ChatQnA/tests/test_chatqna_on_xeon.sh
validation 
Add docker container clean up to avoid the port conflict. 
CI
No
> add docker container clean up

- ChatQnA/microservice/xeon/README.md
- ChatQnA/microservice/xeon/chatqna.py
- ChatQnA/microservice/xeon/docker/Dockerfile
feature
Add docker for ChatQnA Mega Service.
ChatQnA can be started using docker now.
Local tested on SPR
The docker image will rely on the latest version of GenAIComps repository.
> Add docker for ChatQnA Mega Service on Xeon

- ChatQnA/docker-composer/xeon/README.md
1. Added instructions for populating environment variables host_ip and your_hf_api_token. This elps to run the other export commands as is and not to change in multiple places
2. The docker compose yaml file is in the folder location `/home/ubuntu/GenAIComps/GenAIExamples/ChatQnA/microservice/xeon`. Added instruction to navigate to this folder location before running the docker compose command
3. For testing in m7i EC2 instance in AWS, certain ports in the security group needs to be opened up. Otherwise the communication to the microservices using curl commands do not work. Added the instruction in the Readme.md
Issues - https://github.com/opea-project/GenAIExamples/issues/155.
Issues - https://github.com/opea-project/GenAIExamples/issues/157
Other confusions encountered in testing this …
> Update Readme.md for clarity, security group and curl command

- .pre-commit-config.yaml
- .prettierignore
To support helm charts and k8s manifest yamls, change pre-commit-config to allow multiple documents for yaml and change prettier to ignore k8s related yaml files.
n/a
n/a
n/a
> Change pre-commit-config to support helm charts and k8s manifest yamls

- ChatQnA/docker/ui/svelte/src/lib/modules/chat/ChatMessage.svelte
- ChatQnA/docker/ui/svelte/src/routes/+page.svelte
Update the front end to adapt to the new return format
`n/a`.
no
CI pass
> Update the front end to adapt to the new return format

- CodeGen/docker/gaudi/README.md
Changed cd GenAIExamples/CodeGen/ui/ to cd GenAIExamples/CodeGen/docker/ui/. As the ui directory is in the docker directory.
> Fixed incorrect cd command in README

- ChatQnA/docker/gaudi/README.md
- ChatQnA/docker/gaudi/docker_compose.yaml
- ChatQnA/docker/xeon/README.md
- ChatQnA/docker/xeon/docker_compose.yaml
- CodeGen/docker/gaudi/README.md
- CodeGen/docker/gaudi/docker_compose.yaml
- CodeGen/docker/xeon/README.md
- CodeGen/docker/xeon/docker_compose.yaml
- CodeTrans/docker/gaudi/README.md
- CodeTrans/docker/gaudi/docker_compose.yaml
- CodeTrans/docker/xeon/README.md
- CodeTrans/docker/xeon/docker_compose.yaml
- DocSum/docker/gaudi/README.md
- DocSum/docker/gaudi/docker_compose.yaml
- DocSum/docker/xeon/README.md
- DocSum/docker/xeon/docker_compose.yaml
Add no_proxy env for embedding-tei-server container
In a proxy r&d or deployment environment ( need proxy to access external network, no proxy to access internal network)
we need to pass no_proxy setting to embedding-tei-server, otherwise by following https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/docker/xeon/README.md
"TEI embedding service" access is OK, but inside "Embedding Microservice", it failed to access "Embedding Microservice".
some discussion in https://github.com/opea-project/GenAIExamples/issues/251
TEI Embedding Service
curl ${host_ip}:6006/embed
-X POST
-d '{"inputs":"What is Deep Learning?"}'
-H 'Content-Type: application/json'
Embedding Microservice
curl http://${host_ip}:6000/v1/embeddings
-X POST
-d '{"text":"hello"}'
-H 'Content-Type: application/json' …
> Add no_proxy env for embedding-tei-server container

- AudioQnA/audio/docker/asr/asr.py
- AudioQnA/audio/docker/asr/asr_server.py
In this PR Whisper ASR inference is enabled on HPU, and at the same time optimized with one warmup with a long enough audio. (<The Whisper short-form case 30s limit). After this warmup, future shorter generation should follow the same subset of cached HPU graph and be fast. The e2e perf gain HPU compared to CPU can be up to roughly 2~3x.
Language is updated to be required as explicitly specified: (e.g. "english", "chinese"). Check the Whisper compatible language [list](https://github.com/huggingface/transformers/blob/main/src/transformers/models/whisper/tokenization_whisper.py). The default language is "english". We deprecate the auto language detection (where `AudioSpeechRecognition.language` is None) until [#1049](https://github.com/huggingface/optimum-habana/issues/1049) is considered …
> support/optimize ASR on HPU

- ChatQnA/docker/gaudi/README.md
- ChatQnA/docker/xeon/README.md
- ChatQnA/tests/test_chatqna_on_gaudi.sh
- ChatQnA/tests/test_chatqna_on_xeon.sh
Fix dataprep microservice path issue, similar as PR https://github.com/opea-project/GenAIComps/pull/163
The Dockerfile path in GenAIComps/comps/dataprep is changed.
n/a
CI test
> Fix dataprep microservice path issue

- .github/workflows/path_detection.yml
- DocSum/docker/xeon/README.md
> Check if the path exists.

- .github/workflows/image-build-on-push.yml
- .github/workflows/manifest-e2e.yml
- .github/workflows/reuse-get-test-matrix.yml
Enable building latest megaservice image on push event in CI and pushing it to image registry
n/a
n/a
n/a
> Enable building latest megaservice image on push event in CI

- .github/workflows/reuse-get-test-matrix.yml
- ChatQnA/docker/gaudi/README.md
- ChatQnA/docker/xeon/README.md
- ChatQnA/tests/test_chatqna_on_gaudi.sh
- ChatQnA/tests/test_chatqna_on_xeon.sh
Fix missing Dockerfiles path comps/retrievers/langchain/docker/Dockerfile in GenAIComps
Two errors reported by check-dockerfile-paths in CI:
```
Missing Dockerfile: GenAIComps/comps/retrievers/langchain/docker/Dockerfile (Referenced in GenAIExamples/./ChatQnA/docker/gaudi/README.md:25)
Missing Dockerfile: GenAIComps/comps/retrievers/langchain/docker/Dockerfile (Referenced in GenAIExamples/./ChatQnA/docker/xeon/README.md:78)
```
n/a
CI tests
> Fix missing Dockerfiles path in GenAIComps

- .github/workflows/docker-compose-e2e.yml
- CodeTrans/kubernetes/codetrans_gaudi.yaml
- CodeTrans/kubernetes/codetrans_xeon.yaml
- CodeTrans/tests/test_gmc_on_gaudi.sh
- CodeTrans/tests/test_gmc_on_xeon.sh
Add codetrans example test for genaiexample.
`n/a`.
`n/a`.
It's e2e test
> Add codetrans example test for genaiexample

- ChatQnA/tests/test_chatqna_on_gaudi.sh
expand chatqna gaudi service start waiting time
https://github.com/opea-project/GenAIExamples/pull/340
> expand chatqna service start waiting time

- .github/workflows/gmc-e2e.yaml
- ChatQnA/tests/test_gmc_on_gaudi.sh
- ChatQnA/tests/test_gmc_on_xeon.sh
- CodeGen/tests/test_gmc_on_gaudi.sh
- CodeGen/tests/test_gmc_on_xeon.sh
- CodeTrans/tests/test_gmc_on_gaudi.sh
- CodeTrans/tests/test_gmc_on_xeon.sh
- DocSum/tests/test_gmc_on_gaudi.sh
- DocSum/tests/test_gmc_on_xeon.sh
Optimize gmc manifest e2e tests to achieve parallel testing by removing the gmc installation.
n/a
n/a
CI tests
> Optimize gmc manifest e2e tests

- ChatQnA/kubernetes/manifests/README.md
- DocSum/kubernetes/README.md
Fixing minor issues in GMC documentation
* align deployment name in doc with the one in yaml file
* add the missing namespace in the command
`n/a`
- [*] Bug fix (non-breaking change which fixes an issue)
`n/a`
`n/a`
> doc: fix minor issue in GMC doc

- .github/workflows/gmc-e2e.yaml
Allow gmc e2e workflow to get secrets to support more examples
n/a
n/a
CI improvement
> Allow gmc e2e workflow to get secrets

- ChatQnA/docker/gpu/docker_compose.yaml
Embedding and reranking services failed to run on GPU H100. 
Change the image tag and use CPU for these services. This PR will fix #442
#442
N/A
N/A
> Fix a minor bug for chatqna in docker-compose (#442)

- SearchQnA/docker/ui/svelte/README.md
* First (and only) H1 heading should be the document title
* image reference was broken
> doc: fix headings and broken image reference

- DocSum/docker/ui/react/README.md
- DocSum/docker/xeon/README.md
First (and only) H1 heading is the title and subsequent headings should not skip levels (e.g., from H2 to H4).
> doc: fix headings in markdown files

- Translation/README.md
> doc: fix markdown in Translation/README.md

- ChatQnA/docker/gaudi/README.md
ChatQnA needs two gaudi cards. put a note to inform users.
ChatQnA needs two gaudi cards. put a note to inform users.
N/A
NA
> Update README.md to notify two gaudi cards needed

- ChatQnA/docker/gaudi/README.md
- ChatQnA/tests/test_chatqna_guardrails_on_gaudi.sh
Update guardrail docker file path
`n/a`
None
Local test and pre-CI test.
> Update guardrail docker file path

- CodeGen/README.md
This PR makes minor documentation updates for things that I noticed when running this example:
* There is a "Guide" link that took me to a directory without a README.md, so I changed this to link to the Gaudi and Xeon READMEs that have instructions for building the docker images from source
* The instructions have me set my HF token env var, but there is no mention of what model is being used and I didn't previously have access CodeLlama. 
* Fixed a typo in the Gaudi driver version
N/A
N/A
> Minor documentation improvements in the CodeGen README

- ChatQnA/README.md
Updated ChatQnA readme with OpenShift instructions. Includes instructions from Intel technology enabling for openshift project [readme](https://github.com/intel/intel-technology-enabling-for-openshift/blob/main/workloads/opea/chatqna/README.md). This is a prototype and more workloads supported on opea will be added.
n/a.
> Update ChatQnA readme with OpenShift instructions

- ChatQnA/docker/gaudi/README.md
This PR fixes a minor issue in the ChatQnA Gaudi docker README, where a couple of commands are using a `${your_ip}` env var when the rest of the README is using `${host_ip}`. Copy/pasting the commands cause an error without this fix.
N/A
N/A
> Fix minor issue in ChatQnA Gaudi docker README

- ChatQnA/docker/aipc/compose.yaml
set OLLAMA_MODEL environment variable for docker container.
LLM micro service gets OLLAMA_MDOEL from ENV.
> set OLLAMA_MODEL env to docker container

- ChatQnA/kubernetes/chatQnA_dataprep_gaudi.yaml
- ChatQnA/kubernetes/chatQnA_dataprep_xeon.yaml
- ChatQnA/tests/test_gmc_on_gaudi.sh
- ChatQnA/tests/test_gmc_on_xeon.sh
1. Add `dataprep` microservice to `chatQnA` example 
2. Add the e2e test for this example on both Xeon and Gaudi
https://github.com/opea-project/GenAIInfra/issues/168
https://github.com/opea-project/GenAIInfra/issues/207
`n/a`.
This PR includes e2e test.
> Add dataprep microservice to chatQnA example and the e2e test

- .github/workflows/_example-workflow.yml
- .github/workflows/manual-bom-scan.yml
- .github/workflows/manual-docker-publish.yml
Fix CD workflow typo 
https://github.com/opea-project/GenAIExamples/actions/runs/10408131527/job/28826916518 
Some typos. 
> Fix CD workflow typos

- README.md
Use the normal markdown syntax for tables instead of HTML. Make the output for the github.io HTML website look better.
> doc: remove use of HTML for table in README

- .github/workflows/_get-test-matrix.yml
The original used base_commit=${{ github.event.pull_request.base.sha }} is freeze when the PR is created. So if the main branch has new changes, the changed files detect will be wrong.
Same issue as https://github.com/opea-project/GenAIComps/pull/512
> Fix CI test changed file detect issue

- DocSum/README.md
According to #https://github.com/opea-project/GenAIExamples/issues/338: 
The motivation paragraph 2 is more general and perhaps should move up as paragraph-1. Original paragraph-1 gets too specific into legal documents prematurely.
so Remove the paragraph 1 as it is not related.
> doc fix: Update README.md to remove specific dicscription of paragraph-1

- .github/workflows/_gmc-workflow.yml
- .github/workflows/manual-example-workflow.yml
- update deploy_gmc logical in cd workflow
- bug fix
> update deploy_gmc logical in cd workflow

- ChatQnA/benchmark/four_gaudi/embedding-dependency_run.yaml
- ChatQnA/benchmark/four_gaudi/llm-dependency_run.yaml
- ChatQnA/benchmark/four_gaudi/reranking-dependency_run.yaml
- ChatQnA/benchmark/single_gaudi/chatqna_config_map.yaml
- ChatQnA/benchmark/single_gaudi/embedding-dependency_run.yaml
- ChatQnA/benchmark/single_gaudi/llm-dependency_run.yaml
- ChatQnA/benchmark/single_gaudi/reranking-dependency_run.yaml
- ChatQnA/benchmark/two_gaudi/chatqna_config_map.yaml
- ChatQnA/benchmark/two_gaudi/embedding-dependency_run.yaml
- ChatQnA/benchmark/two_gaudi/llm-dependency_run.yaml
- ChatQnA/benchmark/two_gaudi/reranking-dependency_run.yaml
update LLM manifests for v0.9
N/A
N/A
N/A
> update manifests for v0.9

- DocSum/README.md
fix the sentence for more general hardware
> [doc] Update README.md

- DocSum/README.md
added a micro/megaservice workflow for Doc Sum
Need a workflow how we build DocSum via mega and micro service
n/a
NA
NA
> [Doc]Add a micro/mega service WorkFlow for DocSum 

- AudioQnA/docker/xeon/compose.yaml
- ChatQnA/docker/xeon/compose.yaml
- ChatQnA/docker/xeon/compose_qdrant.yaml
- ChatQnA/kubernetes/README.md
- ChatQnA/kubernetes/manifests/xeon/chatqna.yaml
- CodeGen/docker/xeon/compose.yaml
- CodeGen/kubernetes/manifests/xeon/codegen.yaml
- CodeGen/kubernetes/manifests/xeon/ui/react-codegen.yaml
- CodeGen/tests/test_codegen_on_xeon.sh
- CodeTrans/docker/xeon/compose.yaml
- CodeTrans/kubernetes/manifests/xeon/codetrans.yaml
- DocSum/docker/xeon/compose.yaml
- DocSum/kubernetes/README.md
- DocSum/kubernetes/manifests/xeon/docsum.yaml
- DocSum/kubernetes/manifests/xeon/ui/react-docsum.yaml
- FaqGen/docker/xeon/compose.yaml
- FaqGen/kubernetes/manifests/xeon/ui/react-faqgen.yaml
- SearchQnA/docker/xeon/compose.yaml
- SearchQnA/tests/test_searchqna_on_xeon.sh
- Translation/docker/xeon/compose.yaml
- VisualQnA/docker/xeon/README.md
- VisualQnA/docker/xeon/compose.yaml
fix tgi xeon tag
https://github.com/opea-project/GenAIExamples/issues/636
None
All UT
> fix tgi xeon tag

- .github/workflows/_gmc-e2e.yml
- .github/workflows/_manifest-e2e.yml
- ChatQnA/kubernetes/manifests/gaudi/chatqna.yaml
- ChatQnA/kubernetes/manifests/xeon/chatqna.yaml
chatqna k8s manifest: Fixed retriever-redis v0.9 image issue.
`n/a`.
n/a.
manually tested.
> chatqna k8s manifest: Fixed retriever-redis v0.9 image issue

- CodeGen/kubernetes/codegen_gaudi.yaml
- CodeGen/kubernetes/codegen_xeon.yaml
Same as https://github.com/opea-project/GenAIExamples/issues/625 mentioned, the tgi 2.2.0 in v0.9 is also not compatible with "ise-uiuc/Magicoder-S-DS-6.7B" model, which GMC e2e is using in the codegen tests.
Update the model to "meta-llama/CodeLlama-7b-hf" in gaudi and "HuggingFaceH4/mistral-7b-grok" in xeon for codegen in GMC pipeline config
`n/a`.
`n/a`.
CI/CD will cover this
> change codegen tgi model

- AudioQnA/kubernetes/manifests/gaudi/audioqna.yaml
- AudioQnA/kubernetes/manifests/xeon/audioqna.yaml
Fix wrong HF token pattern of `sed -i` following README for audioqna k8s manifest
```
sed -i "s/insert-your-huggingface-token-here/${HUGGINGFACEHUB_API_TOKEN}/g" audioqna.yaml
```
n/a
na
local test
> minor fix mismatched hf token

- ChatQnA/docker/xeon/set_env.sh
fix issue #591 
set_env.sh for ChantQnA on Xeon is missing the REDIS_HOST environment variable. because of that when do docker compose up -d, the retriever-redis-server container is showing errors. I solved the problem by adding export REDIS_HOST=${host_ip} Perhaps the same change in needed in other examples as well.
[-] Bug fix (non-breaking change which fixes an issue)
> Update set_env.sh to add REDIS_HOST

- DocSum/docker/Dockerfile
- FaqGen/docker/Dockerfile
- Translation/docker/Dockerfile
- Translation/docker/gaudi/compose.yaml
- Translation/tests/test_translation_on_gaudi.sh
- Translation/tests/test_translation_on_xeon.sh
1. Fix translation gaudi env
2. Replace langchain docker with python
https://github.com/opea-project/GenAIExamples/actions/runs/10493762658/job/29070605482
> fix translation gaudi env

- VisualQnA/docker/xeon/compose.yaml
- Changed the external port of llava-tgi-service from 9399 to 8399
- This change aligns the port with the configuration in VisualQnA/docker/gaudi/compose.yaml 
- Resolves the port conflict with the lvm-tgi service
- Internal port mapping remains unchanged (80)
n/a
> Fix port conflict in llava-tgi-service in VisualQnA

- .github/workflows/scripts/update_images_tag.sh
- .github/workflows/weekly-update-images.yml
> fix token name

- CodeGen/README.md
- CodeGen/kubernetes/manifests/README.md
> [Codegen] Refine readme to prompt users on how to change the model.

- .github/workflows/scripts/codeScan/hadolint.sh
Modify the handling of detected warnings to only prompt.
> Modify the handling of detected warnings to only prompt.

- .github/workflows/_get-image-list.yml
- .github/workflows/manual-docker-publish.yml
- .github/workflows/manual-docker-scan.yml
- Collect the docker scan logs in one folder, avoid to download artifact one by one.   
- Support both example and image as image scan/publish inputs. 
> docker image cd workflow enhance 

- VisualQnA/docker/gaudi/compose.yaml
- VisualQnA/docker/xeon/compose.yaml
Update the environment variable name of the settings of `visualqna-gaudi-ui-server` in `compose.yaml` for both Xeon and Gaudi, from `CHAT_BASE_URL` to `BACKEND_BASE_URL`. 
Otherwise, the user's setting of `BACKEND_SERVICE_ENDPOINT` is invalid and won't be passed to the UI setting, instead using the default value `http://backend_address:8888/v1/visualqna` in [VisualQnA/docker/ui/svelte/.env](https://github.com/opea-project/GenAIExamples/blob/main/VisualQnA/docker/ui/svelte/.env#L1C21-L1C61), with the error below in the UI console.
Fix https://github.com/opea-project/GenAIExamples/issues/683
N/A
Test both [UI for Gaudi](https://github.com/opea-project/GenAIExamples/tree/main/VisualQnA/docker/gaudi#-launch-the-ui) and [UI for Xeon](https://github.com/opea-project/GenAIExamples/tree/main/Visua …
> [VisualQnA] Update compose.yaml to fix the endpoint url issue in UI

- .github/CODEOWNERS
Add more code owners
n/a
- [Y] Others (enhancement, documentation, validation, etc.)
n/a
n/a
> add more code owners

- ChatQnA/README.md
- ChatQnA/docker/gaudi/README.md
- ChatQnA/docker/gpu/README.md
- ChatQnA/docker/xeon/README.md
- ChatQnA/docker/xeon/README_qdrant.md
Refin ChatQnA README for TGI.
Check the TGI status before consuming it.
https://github.com/opea-project/GenAIExamples/issues/706
None
> Refine ChatQnA README for TGI

- ChatQnA/docker/ui/react/src/redux/Conversation/ConversationSlice.ts
llm-tgi microservice from GenAIComps has encoded each output text, so Chinese response will be shown as hexadecimal in react UI. Add support to decode and display the response in Chinese correctly.
> react-ui: Add support to display Chinese

- ChatQnA/benchmark/README.md
Update Benchmark README to Fix Input Length.
Upload a specified file for retrieval.
n/a
None
local tested
> [ChatQnA] Update Benchmark README to Fix Input Length

- supported_examples.md
replace raw html with markdown table syntax to fix yucky github.io rendering for raw html tables
> doc: use markdown table in supported_examples

- ChatQnA/docker/gpu/README.md
Fix `Conversational UI` part of readme for nv gpu
`n/a`
> Fix readme for nv gpu

- .github/workflows/push-infra-issue-creation.yml
watch more docker compose files' changes
`n/a`.
> watch more docker compose files' changes

- .github/workflows/_get-test-matrix.yml
- ChatQnA/benchmark/README.md
- opea_release_data.md
> Update v0.9 RAG release data

- .github/workflows/_manifest-e2e.yml
- .github/workflows/scripts/k8s-utils.sh
- ChatQnA/kubernetes/manifests/gaudi/chatqna-guardrails.yaml
- ChatQnA/kubernetes/manifests/gaudi/chatqna.yaml
- ChatQnA/kubernetes/manifests/xeon/chatqna-guardrails.yaml
- ChatQnA/tests/test_manifest_on_gaudi.sh
- ChatQnA/tests/test_manifest_on_xeon.sh
- CodeGen/kubernetes/manifests/gaudi/codegen.yaml
- CodeGen/kubernetes/manifests/xeon/codegen.yaml
- CodeTrans/kubernetes/manifests/gaudi/codetrans.yaml
- CodeTrans/kubernetes/manifests/xeon/codetrans.yaml
- DocSum/kubernetes/manifests/gaudi/docsum.yaml
- DocSum/kubernetes/manifests/xeon/docsum.yaml
- Update ChatQnA/CodeGen/CodeTrans/DocSum k8s manifest to avoid requiring creating directory for cache model.
- Add chatqna-guardrails manifest files.
- Fix bug #752 introduced by PR #669
- Dump pod status in manifest CI test failure
issue #752
> K8S manifest: Update ChatQnA/CodeGen/CodeTrans/DocSum

- ChatQnA/docker/xeon/README.md
Provide 2 methods, one is by web browser, another is on the a terminal.
When we get the nke-10k-2023.pdf from github directly,  the files is not the right one, and it will cause upload failed later by dataprep API.
`n/a`.
`n/a`.
`wget https://raw.githubusercontent.com/opea-project/GenAIComps/main/comps/retrievers/langchain/redis/data/nke-10k-2023.pdf`
and then run:
```
curl -x "" -X POST "http://${host}:${port}/v1/dataprep" \
-H "Content-Type: multipart/form-data" \
-F "files=@./nke-10k-2023.pdf"
```
> Provide the method to get nke-10k-2023.pdf

- ChatQnA/kubernetes/manifests/gaudi/chatqna-guardrails.yaml
- ChatQnA/kubernetes/manifests/gaudi/chatqna.yaml
- ChatQnA/kubernetes/manifests/xeon/chatqna-guardrails.yaml
- ChatQnA/kubernetes/manifests/xeon/chatqna.yaml
- CodeGen/kubernetes/manifests/gaudi/codegen.yaml
- CodeGen/kubernetes/manifests/xeon/codegen.yaml
- CodeGen/tests/test_manifest_on_gaudi.sh
- CodeGen/tests/test_manifest_on_xeon.sh
- CodeTrans/kubernetes/manifests/gaudi/codetrans.yaml
- CodeTrans/kubernetes/manifests/xeon/codetrans.yaml
- CodeTrans/tests/test_manifest_on_gaudi.sh
- CodeTrans/tests/test_manifest_on_xeon.sh
- DocSum/kubernetes/manifests/gaudi/docsum.yaml
- DocSum/kubernetes/manifests/xeon/docsum.yaml
- DocSum/tests/test_manifest_on_gaudi.sh
- DocSum/tests/test_manifest_on_xeon.sh
Add ui/nginx support in K8S manifest for ChatQnA/CodeGen/CodeTrans/Docsum.
`n/a`.
> Add ui/nginx support in K8S manifest for ChatQnA/CodeGen/CodeTrans/Docsum

- SearchQnA/docker_compose/intel/cpu/xeon/README.md
- SearchQnA/docker_compose/intel/cpu/xeon/compose.yaml
Up data REAME.md build UI image.
Add missed environment set and compose service name
> Update SearchQnA document and compose.yaml

- VideoRAGQnA/docker_compose/intel/cpu/xeon/README.md
* fix path to image
* fix indenting content within an ordered list
* remove use of please
> doc: fix broken image reference and markdown

- ChatQnA/README.md
- CodeTrans/README.md
- README.md
update GenAIExample introduction, codetrans readme and chatqna readme.
> update doc according to comments

- InstructionTuning/README.md
- InstructionTuning/docker_compose/intel/cpu/xeon/README.md
- RerankFinetuning/README.md
- RerankFinetuning/docker_compose/intel/hpu/gaudi/README.md
Added gaudi example for rerank model finetuning.
`n/a`.
> Added gaudi example for rerank model finetuning

- ChatQnA/README.md
Improve ChatQnA flowchat according to feedback
https://github.com/opea-project/GenAIExamples/issues/681
NA
NA
> Improve ChatQnA flowchat according to feedback

- VideoQnA/docker_compose/intel/cpu/xeon/README.md
This PR fixes an issue with the VideoQnA backend service endpoint environment variable in the docs where it incorrectly says chatqna instead of videoqna. Without this fix, I'm seeing the following error:
Also, I have a minor change to use `${host_ip}` when setting up the no_proxy env var, since that's `host_ip` is already defined earlier in the README.
None
Built all images and ran the VideoQnA microservices on a Xeon machine. I updated sample videos, brought up the UI, and submitted prompts.
> Fix BACKEND_SERVICE_ENDPOINT variable value in the VideoQnA instructions

- AgentQnA/README.md
- AgentQnA/docker_compose/intel/cpu/xeon/compose_openai.yaml
- AgentQnA/docker_compose/intel/hpu/gaudi/compose.yaml
- AgentQnA/docker_image_build/build.yaml
- AgentQnA/tests/1_build_images.sh
- AgentQnA/tests/_test_compose_openai_on_xeon.sh
> update image name

- ChatQnA/docker_compose/intel/cpu/xeon/README.md
- ChatQnA/docker_compose/intel/hpu/gaudi/README.md
- ChatQnA/docker_compose/nvidia/gpu/README.md
Refine the quick start of ChatQnA.
n/a
- [Y] Others (enhancement, documentation, validation, etc.)
n/a
n/a
> Refine the quick start of ChatQnA

- MultimodalQnA/ui/gradio/multimodalqna_ui_gradio.py
Fix code scanning alert for uncontrolled data used in path expression for MultimodalQnA for v1.0 release
[https://github.com/opea-project/GenAIExamples/issues/833](https://github.com/opea-project/GenAIExamples/issues/833)
- [ x] Bug fix (non-breaking change which fixes an issue)
N/A
N/A
> Handle uncontrolled data path for MultimodalQnA v1.0 release

- ChatQnA/docker_compose/intel/cpu/aipc/README.md
- ChatQnA/docker_compose/intel/cpu/xeon/README.md
- ChatQnA/docker_compose/intel/cpu/xeon/README_qdrant.md
Add validate microservice details link
`n/a`.
None
Just document enhancement
> Add validate microservice details link

- .github/workflows/_example-workflow.yml
> print image build test commit

- SearchQnA/tests/test_compose_on_gaudi.sh
- SearchQnA/tests/test_compose_on_xeon.sh
> Fix SearchQnA tests bug

- InstructionTuning/README.md
I was able to successfully run the instruction finetune on Gaudi 2 and I am just adding a few comments to the README for clarity.
I tested with a more recent Gaudi image than the one in [Dockerfile.intel_hpu](https://github.com/opea-project/GenAIComps/blob/main/comps/finetuning/Dockerfile.intel_hpu)
I used:
FROM vault.habana.ai/gaudi-docker/1.17.0/ubuntu22.04/habanalabs/pytorch-installer-2.3.1:latest as hpu
Instead of:
FROM opea/habanalabs:1.16.1-pytorch-installer-2.2.2 as hpu
This PR only has the readme additions but let me know if you want a PR to upgrade that as well.
> instruction finetune README improvement

- CodeGen/README.md
Added a workflow for CodeGen following what ChatQnA has. [ChatQnA flow](https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA#architecture-and-deploy-details)
`n/a`.
NA
> Update CodeGen README for its workflow

- .github/workflows/_run-docker-compose.yml
add PINECONE_KEY_LANGCHAIN_TEST token for CI test
https://github.com/opea-project/GenAIExamples/pull/540
> add PINECONE_KEY_LANGCHAIN_TEST for CI test

- AgentQnA/README.md
Added a workflow for AgentQnA following what ChatQnA has. [ChatQnA flow](https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA#architecture-and-deploy-details)
n/a
NA
NA
> Update Agent README.md for workflow

- Translation/README.md
Added a workflow for VideoQnA following what ChatQnA has. [ChatQnA flow](https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA#architecture-and-deploy-details)
`n/a`.
na
> Update Translation README.md for workflow

- ChatQnA/docker_compose/intel/cpu/aipc/compose.yaml
AIPC Ollama Docker container failed to download LLM model because of http_proxy
- [X ] Bug fix (non-breaking change which fixes an issue)
#docker compose up -d
ollama automatically download set LLM model
> Fix AIPC docker container network issue

- CodeTrans/README.md
Added a workflow for CodeTrans following what ChatQnA has. [ChatQnA flow](https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA#architecture-and-deploy-details)
`n/a`.
NA
> Update CodeTrans README.md for workflow

- FaqGen/benchmark/accuracy/evaluate.py
- FaqGen/benchmark/accuracy/launch_tgi.sh
fix FaqGen accuracy scripts bug
> fix FaqGen accuracy scripts bug

- VisualQnA/README.md
Added a workflow for VisualQnA following what ChatQnA has. [ChatQnA flow](https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA#architecture-and-deploy-details)
`n/a`.
na
> Update VisualQnA README.md for its workflow

- ChatQnA/benchmark/accuracy/eval_multihop.py
for no wrapper ChatQnA service, there is no wrapper `embedding_endpoint`, so replace it with `tei_embedding_endpoint`.
> update accuracy embedding endpoint for no wrapper

- .github/workflows/nightly-docker-build-publish.yml
Add nightly image build and publish action to refresh all the released images. 
In the development cycle, images with bug fix are not available in public docker hub. So add this action to refresh the published images nightly. 
> Add nightly image build and publish action

- .github/workflows/_run-docker-compose.yml
Use docker stop instead of docker compose stop to avoid container clean up issue
`no port specified: :<empty>` will cause the container clean up issue, which lead to port allocate issue for the next test. 
https://github.com/opea-project/GenAIExamples/actions/runs/11657629022/job/32477125804?pr=999#step:5:62 
> Use docker stop instead of docker compose stop to avoid container clean up issue

- ChatQnA/docker_compose/intel/hpu/gaudi/README.md
- ChatQnA/docker_compose/nvidia/gpu/README.md
- DocSum/docker_compose/intel/hpu/gaudi/README.md
- SearchQnA/docker_compose/intel/hpu/gaudi/README.md
- Translation/docker_compose/intel/hpu/gaudi/README.md
Update document fix document broken build instructions
Fix the github issue
[List the issue or RFC link this PR is working on. If there is no such link, please mark it as `n/a`.](https://github.com/opea-project/GenAIExamples/issues/1001)
No
> [Doc] Fix broken build instruction

- CodeGen/benchmark/performance/README.md
- CodeTrans/benchmark/performance/README.md
- FaqGen/benchmark/performance/README.md
- VisualQnA/benchmark/performance/README.md
fix wrong format which break online doc build
> fix wrong format which break online doc build

- ProductivitySuite/docker_compose/intel/cpu/xeon/README.md
- ProductivitySuite/docker_compose/intel/cpu/xeon/compose.yaml
- ProductivitySuite/tests/test_compose_on_xeon.sh
Update TGI CPU image to align with other services with respect to recent updating effort in [PR1035](https://github.com/opea-project/GenAIExamples/pull/1035)
n/a
n/a
n/a
> ProductivitySuite: Update TGI CPU image version to 2.4.0

- ChatQnA/docker_compose/intel/cpu/xeon/README.md
- ChatQnA/docker_compose/intel/cpu/xeon/compose_vllm.yaml
Enable vLLM PyTorch Profiling for ChatQnA.
For advance users who want to do vLLM performance profiling, good to have profiling feature enabled.
`n/a`.
NA
Manual Testing
> Enable vLLM Profiling for ChatQnA

- ChatQnA/docker_compose/intel/cpu/xeon/README.md
- FaqGen/docker_compose/intel/cpu/xeon/README.md
- FaqGen/docker_compose/intel/cpu/xeon/compose.yaml
- FaqGen/docker_compose/intel/hpu/gaudi/README.md
- FaqGen/docker_compose/intel/hpu/gaudi/compose.yaml
- FaqGen/kubernetes/intel/cpu/xeon/manifest/faqgen_react_ui.yaml
- FaqGen/kubernetes/intel/cpu/xeon/manifest/faqgen_ui.yaml
- FaqGen/kubernetes/intel/hpu/gaudi/manifest/faqgen_ui.yaml
- FaqGen/tests/test_compose_on_gaudi.sh
- FaqGen/tests/test_compose_on_xeon.sh
> fix faq ui bug

- ChatQnA/docker_compose/intel/hpu/gaudi/README.md
- ChatQnA/docker_compose/intel/hpu/gaudi/compose_vllm.yaml
Enable vLLM PyTorch Profiling for ChatQnA on Gaudi.
For advance users who want to do vLLM performance profiling, good to have profiling feature enabled.
`n/a`.
NA
manually testing
> Enable vLLM Profiling for ChatQnA on Gaudi

- DocSum/docker_compose/amd/gpu/rocm/README.md
- DocSum/docker_compose/amd/gpu/rocm/compose.yaml
- DocSum/docker_compose/amd/gpu/rocm/set_env.sh
- DocSum/tests/test_compose_on_rocm.sh
- Added compose file for AMD ROCm deployment.
- Added Readme file for AMD ROCm deployment example.
- Added tests for AMD ROCm deployment
Go to GenAIExamples/DocSum/tests and run test_compose_on_rocm.sh test(./test_compose_on_rocm.sh test) script
> Add compose example for DocSum amd rocm deployment

- ChatQnA/docker_compose/nvidia/gpu/README.md
Add instructions of modifying reranking docker image based on different GPU Archs to fix the runtime/compilation backend mismatch issue.
The default tei-reranking docker image is for ampere arch with 8.0 compute capacity. If using the default tei reranking docker image on H100 NVL, there will be an issue `Could not start backend: Runtime compute cap 90 is not compatible with compile time compute cap 80`.
n/a
Run on both A100 and H100 NVL.
> Add instructions of modifying reranking docker image for NVGPU

- ChatQnA/benchmark/performance/kubernetes/intel/gaudi/README.md
- ChatQnA/benchmark/performance/kubernetes/intel/gaudi/deploy.py
The way that Helm Chart Release has been changed, charts can now be installed from oci://ghcr.io/opea-project/charts without the need to add a repository. Make update in this implementation accordingly.
opea-project/GenAIInfra#592
> Adjustments for helm release change

- EdgeCraftRAG/Dockerfile.server
- EdgeCraftRAG/README.md
- EdgeCraftRAG/docker_compose/intel/gpu/arc/compose.yaml
- EdgeCraftRAG/docker_compose/intel/gpu/arc/compose_vllm.yaml
- EdgeCraftRAG/edgecraftrag/components/generator.py
- EdgeCraftRAG/tests/configs/test_pipeline_local_llm.json
- EdgeCraftRAG/tests/configs/test_pipeline_vllm.json
- EdgeCraftRAG/tests/test_compose_vllm_on_arc.sh
- EdgeCraftRAG/tests/test_pipeline_local_llm.json
- EdgeCraftRAG/ui/gradio/default.yaml
- EdgeCraftRAG/ui/gradio/ecrag_client.py
Fixes [https://github.com/opea-project/GenAIExamples/security/code-scanning/21](https://github.com/opea-project/GenAIExamples/security/code-scanning/21)
To fix the problem, we need to ensure that the `template` path is validated before being used. We can achieve this by normalizing the path and ensuring it is within a predefined safe directory. This will prevent path traversal attacks and ensure that only files within the allowed directory can be accessed.
1. Define a safe root directory where the templates are stored.
2. Normalize the `template` path using `os.path.normpath`.
3. Check that the normalized path starts with the safe root directory.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Fix code scanning alert no. 21: Uncontrolled data used in path expression

- ChatQnA/docker_compose/amd/gpu/rocm/README.md
- ChatQnA/docker_compose/intel/hpu/gaudi/README.md
- ChatQnA/docker_compose/nvidia/gpu/README.md
* Update the tgi/vllm llm backend ports in the readme to align with what in the yaml file for HPU/amdgpu/nvgpu .
* Update the checking command of container logs of tgi-service, to use the specified container name instead of service name.
n/a
n/a
> Update the llm backend ports

- ChatQnA/benchmark/performance/kubernetes/intel/gaudi/README.md
- ChatQnA/benchmark/performance/kubernetes/intel/gaudi/benchmark.yaml
Modify Retrieval top_k Parameter to 1, to align with/without rerank pipeline llm input token length.
N/A
None
Local tested
> [ChatQnA] Update Benchmark E2E Parameters

- AudioQnA/audioqna.py
- AudioQnA/audioqna_multilang.py
- AvatarChatbot/avatarchatbot.py
- CodeGen/codegen.py
- CodeTrans/code_translation.py
- DocIndexRetriever/retrieval_tool.py
- EdgeCraftRAG/chatqna.py
- GraphRAG/graphrag.py
- MultimodalQnA/multimodalqna.py
- SearchQnA/searchqna.py
- Translation/translation.py
- VideoQnA/videoqna.py
- VisualQnA/visualqna.py
remove examples gateway because GenAIComps deprecates it https://github.com/opea-project/GenAIComps/pull/979
> remove examples gateway.

- AgentQnA/docker_compose/amd/gpu/rocm/compose.yaml
- AgentQnA/docker_compose/amd/gpu/rocm/launch_agent_service_tgi_rocm.sh
- AgentQnA/docker_compose/amd/gpu/rocm/set_env.sh
- AgentQnA/tests/step4a_launch_and_validate_agent_tgi_on_rocm.sh
- AgentQnA/tests/test_compose_on_rocm.sh
- Added docker compose example for AgentQnA deployment on AMD ROCm (TGI service is in use).  
- Added CI tests for Docker compose AgentQnA deploymen example on AMD ROCm systems
Go to GenAIExamples/AgentQnA/tests and run test_compose_on_rocm.sh bash script (./test_compose_on_rocm.sh).
> Added docker compose example for AgentQnA deployment on AMD ROCm 

- MultimodalQnA/docker_compose/amd/gpu/rocm/README.md
- MultimodalQnA/docker_compose/amd/gpu/rocm/compose.yaml
- MultimodalQnA/docker_compose/amd/gpu/rocm/set_env.sh
- MultimodalQnA/tests/test_compose_on_rocm.sh
Changes for MultimodalQnA example deployment to AMD ROCm systems.
- Added compose example for MultimodalQnA deployment on AMD ROCm systems.
- Added Readme file for MultimodalQnA compose deployment example on AMD ROCm systems.
- Added CI tests for MultimodalQnA compose deployment example on AMD ROCm systems.
For manual test s go to GenAIExamples/MultimodalQnA/tests dir and run test_compose_on_rocm.sh script (./test_compose_on_rocm.sh)
> Added compose example for MultimodalQnA deployment on AMD ROCm systems

- Translation/docker_compose/intel/cpu/xeon/compose.yaml
- Translation/docker_compose/intel/hpu/gaudi/compose.yaml
- Translation/docker_image_build/build.yaml
- Translation/tests/test_compose_on_xeon.sh
- Translation/ui/svelte/.env
- VideoQnA/docker_image_build/build.yaml
- VideoQnA/tests/test_compose_on_xeon.sh
> Fix Translation and VideoQnA CI issues

- ChatQnA/tests/test_compose_on_rocm.sh
- ChatQnA/tests/test_compose_on_xeon.sh
- ChatQnA/tests/test_compose_without_rerank_on_xeon.sh
Remove chatqna-conversation-ui build in CI test. It's actually not used by test scripts. 
chatqna-conversation-ui image build failed with `npm install`, https://github.com/opea-project/GenAIExamples/actions/runs/12662950313/job/35288707727?pr=1360. 
> remove chatqna-conversation-ui build in CI test

- ChatQnA/ui/react/package.json
- CodeGen/ui/react/package.json
- DBQnA/ui/react/package.json
- DocSum/ui/react/package.json
- FaqGen/ui/react/package.json
- GraphRAG/ui/react/package.json
- ProductivitySuite/ui/react/package.json
Fixed build issue
https://github.com/opea-project/GenAIExamples/issues/1365
> fixed build issue

- EdgeCraftRAG/tests/test_compose_vllm_on_arc.sh
vllm-openvino is a dependency for text generation comps, in GenAIComps PR https://github.com/opea-project/GenAIComps/pull/1141 we move it to third-parties folder, update the path accordingly.
#998 
-  Others (enhancement, documentation, validation, etc.)
no
EdgeCraftRAG/tests/test_compose_vllm_on_arc.sh
EdgeCraftRAG/tests/test_compose_on_arc.sh
> Refactor vllm openvino to third parties

- AudioQnA/Dockerfile
- AudioQnA/Dockerfile.multilang
- AvatarChatbot/Dockerfile
- ChatQnA/Dockerfile
- ChatQnA/Dockerfile.guardrails
- ChatQnA/Dockerfile.without_rerank
- ChatQnA/Dockerfile.wrapper
- CodeGen/Dockerfile
- CodeTrans/Dockerfile
- DocIndexRetriever/Dockerfile
- DocSum/Dockerfile
- EdgeCraftRAG/Dockerfile
- EdgeCraftRAG/Dockerfile.server
- FaqGen/Dockerfile
- GraphRAG/Dockerfile
- MultimodalQnA/Dockerfile
- SearchQnA/Dockerfile
- Translation/Dockerfile
- VideoQnA/Dockerfile
- VisualQnA/Dockerfile
Staged image builds so that final images do not have redundant things like:
- Git tool and its deps (e.g. Perl)
- Git repo history
- Test directories
And drop explicit installation of:
- `langchain_core`: _GenAIComps_ installs `langchain` which already depends on that
- `jemalloc` & GLX: nothing uses them (in any of the ChatQnA services), and for testing[1] it's trivial to create separate image adding those on top
- File descriptor limit increase for `~/.bashrc` (as these images run Python programs directly, not through Bash scripts)
=> This demonstrates that only 2-3 lines in the Dockerfiles are unique, and everything preceding those could be removed with a common base image.
[1] I assume those files were there to test this: https://pytorch.org/tutorials/recipes/recipes/tuning_guide.html# …
> Use staged builds to minimize final image sizes

- ChatQnA/docker_compose/intel/cpu/aipc/README.md
- CodeGen/docker_compose/intel/cpu/xeon/README.md
- CodeGen/docker_compose/intel/hpu/gaudi/README.md
The number of built docker images is incorrect in
CodeGen and ChatQnA REAME.md.
Fix issue #1383
#1383 
No
No
> [DOC] Fix document issue

- DocSum/docker_compose/intel/hpu/gaudi/compose.yaml
- DocSum/docsum.py
- DocSum/tests/test_compose_on_gaudi.sh
- DocSum/tests/test_compose_on_rocm.sh
- DocSum/tests/test_compose_on_xeon.sh
- FaqGen/docker_compose/intel/hpu/gaudi/compose.yaml
- FaqGen/faqgen.py
- FaqGen/tests/test_compose_on_gaudi.sh
- FaqGen/tests/test_compose_on_rocm.sh
- FaqGen/tests/test_compose_on_xeon.sh
Algin all the inputs to OpenAI API format for FaqGen, DocSum, related with GenAIComps PR https://github.com/opea-project/GenAIComps/pull/1161
https://github.com/opea-project/GenAIComps/issues/998
no
DocSum/tests/
FaqGen/tests/
> Align OpenAI API for FaqGen, DocSum

- .github/workflows/_run-docker-compose.yml
- .github/workflows/scripts/docker_compose_clean_up.sh
Add secrets OPENAI_API_KEY for AMD GPU CI test
https://github.com/opea-project/GenAIExamples/pull/1193/files
https://github.com/opea-project/GenAIExamples/pull/1288/files
> Add secrets OPENAI_API_KEY

- ChatQnA/docker_compose/amd/gpu/rocm/compose.yaml
- ChatQnA/tests/test_compose_on_rocm.sh
This PR is to correct the env variable names in chatqna example on ROCm platform passing to the docker container of TGI and TEI. For tgi, either `HF_TOKEN` and `HUGGING_FACE_HUB_TOKEN` could be parsed in TGI while `HF_API_TOKEN` can be parsed in TEI.
TGI: https://github.com/huggingface/text-generation-inference/blob/main/router/src/server.rs#L1700C1-L1702C15
TEI: https://github.com/huggingface/text-embeddings-inference/blob/main/router/src/main.rs#L112
Fix the model download error of CI issue for ROCm in https://github.com/opea-project/GenAIExamples/pull/1430
> [ROCm] Fix the hf-token setting for TGI and TEI in ChatQnA

- .github/workflows/_example-workflow.yml
Test compose cd workflow depend on image build, so if we want to run both compose and helm charts deployment in cd workflow, this condition should be removed. 
https://github.com/opea-project/GenAIExamples/actions/runs/12911771576
While testing both docker compose and helm charts, test only trigger helm chart. 
> remove image build condition

- .github/workflows/_example-workflow.yml
- AgentQnA/tests/step1_build_images.sh
- AgentQnA/tests/test_compose_on_gaudi.sh
- ChatQnA/tests/test_compose_guardrails_on_gaudi.sh
- ChatQnA/tests/test_compose_on_gaudi.sh
- ChatQnA/tests/test_compose_without_rerank_on_gaudi.sh
The new triton version 3.2.0 can't work with vllm-gaudi. Freeze the triton version in vllm-gaudi image to 3.1.0. 
https://github.com/opea-project/GenAIExamples/actions/runs/12925473915/job/36046527660#step:5:180
Issue create for vllm-fork: https://github.com/HabanaAI/vllm-fork/issues/732
> Freeze the triton version in vllm-gaudi image to 3.1.0

- ChatQnA/README.md
Add contents to explain how to understand OPEA telemetry tracing for ChatQnA.
The PR depends on https://github.com/opea-project/GenAIComps/pull/1122
`n/a`.
NA
manually testing
> Update README.md for OPEA OTLP tracing

- DocSum/docker_compose/intel/hpu/gaudi/compose.yaml
- FaqGen/docker_compose/intel/hpu/gaudi/compose.yaml
Docker Compose requires all named volumes to be explicitly defined.
Fix github issue #1486
docker compose up -d
without error response
Without the fix, there is error:
service "tgi-gaudi-server" refers to undefined volume data: invalid compose project
> Fix docker compose.yaml error

- ChatQnA/docker_compose/intel/cpu/xeon/README.md
- ChatQnA/docker_compose/intel/hpu/gaudi/README.md
Add a section how to change LLM model properly by following validated LLM model table
https://github.com/opea-project/GenAIComps/pull/1267
`n/a`.
NA
NA
> Add a new section to change LLM model such as deepseek based on validated model table in LLM microservice

- ChatQnA/benchmark_chatqna.yaml
- README-deploy-benchmark.md
- benchmark.py
Enhance the benchmark process:
1. support ingest/delete dataset files in for-loop
2. delete unused parameters in `benchmark.py` and `benchmark_chatqna.yaml`
3. enhance the `bench_target` process part
n/a
None
Local tested on k8s
> Enhance benchmark

- ChatQnA/benchmark_chatqna.yaml
- benchmark.py
Support multiple concurrencies and add node_num for user queries
n/a
None
Local tested
> Support multiple concurrencies and add node_num for user queries

- ChatQnA/README.md
The source of the set_env.sh from the root folder of the example does not work, need to cd into each of the hardware option (intel/nvidia).
- [https://github.com/opea-project/GenAIExamples/issues/1550](https://github.com/opea-project/GenAIExamples/issues/1550)
N/A
N/A
> Make a fix in the main README.md of the ChatQnA.

- AvatarChatbot/Dockerfile
- ChatQnA/tests/test_compose_on_gaudi.sh
- EdgeCraftRAG/Dockerfile.server
- EdgeCraftRAG/ui/docker/Dockerfile.ui
- VideoQnA/ui/docker/Dockerfile
Fix docker image security issue
> Fix trivy issue

- AgentQnA/README.md
- AgentQnA/docker_compose/intel/cpu/xeon/compose_openai.yaml
- AgentQnA/docker_compose/intel/cpu/xeon/launch_agent_service_openai.sh
- AgentQnA/docker_compose/intel/hpu/gaudi/compose.yaml
- AgentQnA/docker_compose/intel/hpu/gaudi/launch_agent_service_gaudi.sh
- AgentQnA/tests/step4_launch_and_validate_agent_gaudi.sh
- AgentQnA/tests/test.py
- AgentQnA/tests/test_compose_on_gaudi.sh
- DocIndexRetriever/docker_compose/intel/cpu/xeon/compose.yaml
- DocIndexRetriever/retrieval_tool.py
- DocIndexRetriever/tests/test.py
1. AgentQnA: supervisor agent to support multi-turn conversations with checkpointer
2. AgentQnA: Xeon with OpenAI - update db for sql agent
3. DocIndexRetriever: update retrieval_tool.py to allow user to pass in retriever and reranker params
https://github.com/opea-project/GenAIExamples/issues/1511
No new dependencies
UTs
> Update AgentQnA and DocIndexRetriever

- AgentQnA/docker_compose/intel/cpu/xeon/README.md
- ChatQnA/chatqna.py
- GraphRAG/graphrag.py
Fix "OpenAI" & "response" spelling.
`n/a`.
`n/a`.
`n/a`.
> Fix "OpenAI" & "response" spelling

- benchmark.py
- deploy.py
- deploy_and_benchmark.py
> Unify dir for benchmark result

- AudioQnA/Dockerfile
- AudioQnA/Dockerfile.multilang
- DocIndexRetriever/Dockerfile
- EdgeCraftRAG/Dockerfile
- FaqGen/Dockerfile
- VideoQnA/Dockerfile
Update Dockerfiles for 5 apps to use "GenAIComp" base image: https://github.com/opea-project/GenAIComps/blob/main/Dockerfile
(Instead of each re-building that same content.)
This is subset of https://github.com/opea-project/GenAIExamples/pull/1369 changes, for apps which do not show CI issues (currently).
Larger than necessary disk usage, much more complex Dockerfiles than needed.
`n/a`.
CI.
> Use GenAIComp base image to simplify Dockerfiles - part 1

- ChatQnA/ui/svelte/src/lib/shared/components/loading/Spinner.svelte
- ChatQnA/ui/svelte/src/routes/+page.svelte
Add spinner component and show it after query sending by user.
Fixes #1003
N/A
Once query send and waiting for answer, Spinner will be shown as reminder, the UI like as below:
> [ChatQnA] Show spinner after query to improve user experience (#1003)

- ChatQnA/docker_compose/intel/cpu/xeon/README.md
- ChatQnA/docker_compose/intel/cpu/xeon/README_pinecone.md
- ChatQnA/docker_compose/intel/cpu/xeon/compose.yaml
- ChatQnA/docker_compose/intel/cpu/xeon/compose_milvus.yaml
- ChatQnA/docker_compose/intel/cpu/xeon/compose_qdrant.yaml
- ChatQnA/docker_compose/intel/cpu/xeon/compose_without_rerank.yaml
- CodeTrans/docker_compose/intel/cpu/xeon/README.md
- CodeTrans/docker_compose/intel/cpu/xeon/compose.yaml
- CodeTrans/docker_compose/intel/hpu/gaudi/README.md
- CodeTrans/docker_compose/intel/hpu/gaudi/compose.yaml
- FaqGen/docker_compose/intel/cpu/xeon/compose.yaml
- FaqGen/docker_compose/intel/hpu/gaudi/compose.yaml
The LLM will be downloaded and saved under `/root/.cache/huggingface/hub` in vLLM docker container, using `-v ./data:/data` would cause the LLM to be downloaded again instead of loading from cache.
n/a
n/a
Local tests
> Fix vllm model cache directory

- ChatQnA/Dockerfile
- ChatQnA/Dockerfile.guardrails
- ChatQnA/Dockerfile.without_rerank
- DocSum/Dockerfile
- GraphRAG/Dockerfile
- SearchQnA/Dockerfile
- Translation/Dockerfile
- VisualQnA/Dockerfile
Update Dockerfiles for next 6 apps to use "GenAIComp" base image: https://github.com/opea-project/GenAIComps/blob/main/Dockerfile
(Instead of each re-building that same content.)
This is subset of https://github.com/opea-project/GenAIExamples/pull/1369 changes, for apps which do not (currently) show CI issues.
Larger than necessary disk usage, much more complex Dockerfiles than needed.
`n/a`.
* CI
* Manual testing for ChatQnA + DocSum, when the parent PR and https://github.com/opea-project/GenAIExamples/pull/1031 were created.  Because there are no conflicts, the updated Dockerfiles have not changed after that
> Use GenAIComp base image to simplify Dockerfiles & reduce image sizes - part 2

- ChatQnA/docker_compose/intel/cpu/xeon/compose.yaml
- ChatQnA/docker_compose/intel/hpu/gaudi/compose.yaml
Sometime redis startup take longer time, dataprep will connect to redis before redis ready , add health check and dependence to avoid this situation.
#1590
n/a
prepare all models and docker images ready.
docker compose up -d
> [ChatQnA][docker]Check healthy of redis to avoid dataprep failure

- AudioQnA/audioqna.py
- AudioQnA/audioqna_multilang.py
- AudioQnA/docker_compose/intel/cpu/xeon/README.md
- AudioQnA/docker_compose/intel/cpu/xeon/compose.yaml
- AudioQnA/docker_compose/intel/cpu/xeon/compose_multilang.yaml
- AudioQnA/docker_compose/intel/cpu/xeon/compose_tgi.yaml
- AudioQnA/docker_compose/intel/cpu/xeon/set_env.sh
- AudioQnA/docker_compose/intel/hpu/gaudi/README.md
- AudioQnA/docker_compose/intel/hpu/gaudi/compose.yaml
- AudioQnA/docker_compose/intel/hpu/gaudi/compose_tgi.yaml
- AudioQnA/docker_compose/intel/hpu/gaudi/set_env.sh
- AudioQnA/docker_image_build/build.yaml
- AudioQnA/tests/test_compose_on_gaudi.sh
- AudioQnA/tests/test_compose_on_xeon.sh
- AudioQnA/tests/test_compose_tgi_on_gaudi.sh
- AudioQnA/tests/test_compose_tgi_on_xeon.sh
- Enable vLLM for AudioQnA and set it as the default LLM serving framework on both Xeon and Gaudi
- Update the default LLM to avoid the chat template issue with neural-chat 
- Make asr/llm/tts service ports and vllm-gaudi parameters configurable in compose files
- Modify readmes
- Add test scripts
https://github.com/opea-project/GenAIExamples/issues/1436
n/a
Local tests
> [AudioQnA] Enable vLLM and set it as default LLM serving

- ChatQnA/docker_compose/intel/hpu/gaudi/README.md
- ChatQnA/docker_compose/intel/hpu/gaudi/set_env.sh
Description
These are review comments on the "Build MegaService of ChatQnA on Gaudi" example README.md, in response to feedback from Rory Finnegan from Denvr and his request:
“I'd recommend asking a colleague at Intel, who isn't a major contributor, to run through the QuickStart guide. If they can do it quickly and without asking for help, then you're probably good. However, if they start encountering errors or need to ask questions about configuration variables, then you have a problem.”
The "GenAIExamples/ChatQnA/docker_compose/intel/hpu/gaudi/README.md" file was selected for this review because Rory’s initial comments, made last fall, were about documentation that has since been refactored. The suggested changes should serve as a template for other examples in the GenAIExamples …
> Add final README.md and set_env.sh script for quickstart review. Previous pull request was 1595.

- ChatQnA/docker_compose/intel/hpu/gaudi/compose.telemetry.yaml
- ChatQnA/docker_compose/intel/hpu/gaudi/compose_tgi.telemetry.yaml
- ChatQnA/docker_compose/intel/hpu/gaudi/set_env.sh
The gaudi node exporter on the host system might occupy the port 41611 so gaudi node exporter created by docker compose will have issues to use the same port 41611.
change port mapping to map to port 41612 instead. 
`n/a`.
NA
manually test on gaudi2
> change gaudi node exporter from default one to 41612 

- CodeGen/Dockerfile
- CodeTrans/Dockerfile
- MultimodalQnA/Dockerfile
Update Dockerfiles for next 3 apps to use "GenAIComp" base image: https://github.com/opea-project/GenAIComps/blob/main/Dockerfile
(Instead of each re-building that same content.)
This is subset of https://github.com/opea-project/GenAIExamples/pull/1369 changes, for apps which do not (currently) show CI issues.
Larger than necessary disk usage, much more complex Dockerfiles than needed.
`n/a`.
CI.  And same change working for the earlier 11 apps which Dockerfile changes have already been merged.
> Use GenAIComp base image to simplify Dockerfiles - part 3/4

- .github/workflows/_run-docker-compose.yml
- AudioQnA/tests/test_compose_on_xeon.sh
Expand example running timeout for the new test cluster with k8s runner set
The new runner set with ARC able to run 8 examples cases + 8 comps cases in parallel, which widely enhance the test resource dispatch. Meanwhile need to expand the example timeout limitation. 
> Expand example running timeout for the new test cluster with k8s runner set

- AgentQnA/README.md
- AgentQnA/docker_compose/intel/hpu/gaudi/compose.telemetry.yaml
- AgentQnA/docker_compose/intel/hpu/gaudi/grafana/dashboards/download_opea_dashboard.sh
- AgentQnA/docker_compose/intel/hpu/gaudi/grafana/provisioning/dashboards/local.yaml
- AgentQnA/docker_compose/intel/hpu/gaudi/grafana/provisioning/datasources/datasource.yml
- AgentQnA/docker_compose/intel/hpu/gaudi/prometheus.yaml
- AgentQnA/docker_compose/intel/hpu/gaudi/set_env.sh
- AgentQnA/tests/step4_launch_and_validate_agent_gaudi.sh
- AgentQnA/tools/tools.py
- AgentQnA/ui/svelte/.env
Enabling Telemetry by an additional compose.telemetry.yaml file.
By default, it is disabled. 
it is only enabled by having compose.telemetry during docker compose up.
`docker compose -f $WORKDIR/GenAIExamples/DocIndexRetriever/docker_compose/intel/cpu/xeon/compose.yaml -f compose.yaml  -f compose.telemetry.yaml up -d`
The PR enables Prometheus connections with Agent Microservices.
Then it could show different Agent statistics like react agent.  
BTW, the dashboard name will be AgentQnA_MicroServices_Grafana instead. 
SQL agent.
vLLM service
CPU statistics
Also add Telemetry tracing into ReactAgent Tools.py
[ 1542.](https://github.com/opea-project/GenAIExamples/issues/1542)
Grafana, Prometheus, and Jaeger …
> Add Telemetry support for AgentQnA using Grafana, Prometheus and Jaeger

- ChatQnA/docker_compose/intel/cpu/xeon/compose.yaml
When running `deepseek-ai/DeepSeek-R1-Distill-Qwen-14B` using vllm, it reported the below errror: 
ValueError: The model's max seq len (131072) is larger than the maximum number of tokens that can be stored in KV cache (21840). Try increasing `VLLM_CPU_KVCACHE_SPACE` or decreasing `max_model_len` when initializing the engine.
Need to increase `VLLM_CPU_KVCACHE_SPACE`.
`n/a`.
None
> Fix vLLM CPU initialize engine issue for DeepSeek models

- AvatarChatbot/tests/test_compose_on_gaudi.sh
- AvatarChatbot/tests/test_compose_on_xeon.sh
Fix #1607 
[List the issue or RFC link this PR is working on. If there is no such link, please mark it as `n/a`.](https://github.com/opea-project/GenAIExamples/issues/1607)
`GenAIExamples/AvatarChatbot/tests/test_compose_on_gaudi.sh`  
`GenAIExamples/AvatarChatbot/tests/test_compose_on_xeon.sh`
> Fix GenAIExamples #1607

- DocSum/docker_compose/set_env.sh
Fix issue https://github.com/opea-project/GenAIExamples/issues/1778
> Align DocSum env to vllm

- .github/workflows/_helm-e2e.yml
- .github/workflows/pr-chart-e2e.yml
Support rocm helm charts values test.   
The test should able to run after we add ROCm k8s cluster into the GHA. 
https://github.com/opea-project/GenAIExamples/pull/1759
https://github.com/opea-project/GenAIExamples/pull/1758
> support rocm helm charts test

- .github/workflows/nightly-docker-build-publish.yml
- .github/workflows/weekly-example-test.yml
1. CICD infrastructure has more test resource on Xeon than Gaudi, so move the nightly test from Gaudi to Xeon. 
2. Xeon image registry only has 1TB disk, so keep image build on Gaudi which has 7TB. 
3. Add weekly job test examples on all HWs we supported in CI. 
> Optimize the nightly/weekly example test

- VisualQnA/docker_compose/intel/cpu/xeon/compose.yaml
Remove template_llava.jinja in command since its no longer included in default vllm image, and pipeline works fine without it.
https://github.com/opea-project/GenAIExamples/issues/1808
no.
UT.
> Remove template_llava.jinja in command

- AgentQnA/retrieval_tool/run_ingest_data.sh
I just merged #1777 but the actual required packages did not make it through!
Please see #1777 
Neither `requests` nor `tqdm` are new.
AgentQnA tests
> Adding the two missing packages for ingest script

- AgentQnA/README.md
Add a small new section to redirect users to new github.io sections for AgentQnA opentelemetry materials
`n/a`.
na
na
> Redirect users to new github.io sections for AgentQnA opentelemetry materials

- DocSum/benchmark_docsum.yaml
- benchmark.py
- deploy.py
* Added docsumbench and docsumfixed testbenches to scripts
* Added new variables to be used for docsum benchmarking
Added Initial version of DocSum support for benchmarking scripts for OPEA
This is feature requested in (https://github.com/opea-project/GenAIExamples/issues/1724)
- [ x] New feature (non-breaking change which adds new functionality)
No new dependencies
Run deploy_and_benchmark.py scripts for both docsumfixed and docsumbench.
> Added Initial version of DocSum support for benchmarking scripts for OPEA

- .github/workflows/_helm-e2e.yml
- .github/workflows/pr-chart-e2e.yml
https://github.com/opea-project/GenAIExamples/security/code-scanning/30
https://github.com/opea-project/GenAIExamples/actions/runs/14698146775/job/41242911239
> Fix security issue

- EdgeCraftRAG/Dockerfile.server
fix OSPDT issue (pytorch include nv packages)
n/a
- [√ ] Bug fix (non-breaking change which fixes an issue)
> Install cpu version for components

- .github/workflows/_helm-e2e.yml
Fix security issue.
https://github.com/opea-project/GenAIExamples/security/code-scanning/30
https://github.com/opea-project/GenAIExamples/actions/runs/14658733798/job/41138357893 test passed
> Fix security issue.

- EdgeCraftRAG/docker_image_build/build.yaml
Restore context in EdgeCraftRAG build.yaml to avoid the issue of can't find Dockerfiles.
> Restore context in EdgeCraftRAG build.yaml.

- CodeGen/ui/gradio/codegen_ui_gradio.py
Added 5 enhancements to CodeGen Gradio UI:
- Code Generation tab has a cleaner outlook
- Query now appears in chat history before response is generated
- Text box now clears upon submission
- Re-worded a few labels
- Added a clear button
N/A, for 1.4
N/A
Manually testing CodeGen UI + FastAPI commands
> CodeGen Gradio UI Enhancements 

- .github/workflows/_helm-e2e.yml
Fix security issues for helm test workflow
https://github.com/opea-project/GenAIExamples/security/code-scanning/31
https://github.com/opea-project/GenAIExamples/actions/runs/14853044830/job/41700159514
> Fix security issues for helm test workflow

- ChatQnA/docker_compose/intel/cpu/xeon/README.md
- ChatQnA/docker_compose/intel/cpu/xeon/README_mariadb.md
- ChatQnA/docker_compose/intel/cpu/xeon/compose_mariadb.yaml
- ChatQnA/docker_compose/intel/cpu/xeon/set_env_mariadb.sh
- ChatQnA/tests/test_compose_mariadb_on_xeon.sh
Add ChatQnA docker-compose example on Intel Xeon using MariaDB Vector
`n/a`
`n/a`
Set the HF API token environment variable and:
```
cd ChatQnA/tests
bash test_compose_mariadb_on_xeon.sh
```
> Add ChatQnA docker-compose example on Intel Xeon using MariaDB Vector

- .github/workflows/_helm-e2e.yml
Fix input check for helm test workflow
https://github.com/opea-project/GenAIExamples/actions/runs/14966494611 test passed
> Fix input check for helm test workflow

- .github/workflows/pr-link-path-scan.yml
Blocking link checks that require a login
> Blocking link checks that require a login

- CodeTrans/Dockerfile
- CodeTrans/docker_image_build/build.yaml
- CodeTrans/tests/test_compose_on_gaudi.sh
- CodeTrans/tests/test_compose_on_rocm.sh
- CodeTrans/tests/test_compose_on_xeon.sh
- CodeTrans/tests/test_compose_tgi_on_gaudi.sh
- CodeTrans/tests/test_compose_tgi_on_xeon.sh
- CodeTrans/tests/test_compose_vllm_on_rocm.sh
> [CICD enhance]  CodeTrans run CI with latest base image, group logs in GHA outputs.

- GraphRAG/docker_compose/intel/hpu/gaudi/set_env.sh
- GraphRAG/tests/README.md
- GraphRAG/tests/test_compose_on_gaudi.sh
Integrate GraphRAG set_env to ut scripts.
Add README.md for UT scripts.
> Integrate GraphRAG set_env to ut scripts.

- DBQnA/docker_image_build/build.yaml
- DBQnA/tests/test_compose_on_rocm.sh
- DBQnA/tests/test_compose_on_xeon.sh
> [CICD enhance] DBQnA run CI with latest base image, group logs in GHA outputs.

- DocIndexRetriever/Dockerfile
- DocIndexRetriever/docker_image_build/build.yaml
- DocIndexRetriever/tests/test_compose_milvus_on_gaudi.sh
- DocIndexRetriever/tests/test_compose_milvus_on_xeon.sh
- DocIndexRetriever/tests/test_compose_on_gaudi.sh
- DocIndexRetriever/tests/test_compose_on_xeon.sh
- DocIndexRetriever/tests/test_compose_without_rerank_on_xeon.sh
> [CICD enhance] DocIndexRetriever run CI with latest base image, group logs in GHA outputs.

- CodeGen/Dockerfile
- CodeGen/docker_image_build/build.yaml
- CodeGen/tests/test_compose_on_gaudi.sh
- CodeGen/tests/test_compose_on_rocm.sh
- CodeGen/tests/test_compose_on_xeon.sh
- CodeGen/tests/test_compose_vllm_on_rocm.sh
> [CICD enhance] CodeGen run CI with latest base image, group logs in GHA outputs.

- .github/workflows/pr-docker-compose-e2e.yml
- AgentQnA/tests/step1_build_images.sh
Build comps-base:ci for AgentQnA test
https://github.com/opea-project/GenAIExamples/pull/1922
> Build comps-base:ci for AgentQnA test

- .github/workflows/scripts/get_test_matrix.sh
- .github/workflows/weekly-example-test.yml
Stop CI test on rocm due to lack of test machine
> Stop CI test on rocm due to lack of test machine

- AgentQnA/retrieval_tool/run_ingest_data.sh
Add an `if` condition to check if `host_ip` has already been configured, so the script does not overwrite a manually assigned value. This is important for Kubernetes, where the local `host_ip` address is private to the cluster and not directly accessible instead of the ip captured running `$(hostname -I | awk '{print $1}')`.
Even when using port forwarding, host_ip must be set before running the script. This validation allows the script to work properly in both Docker and Kubernetes environments while still allowing users to specify host_ip manually if needed.
n/a
- [ x ] Others (enhancement, documentation, validation, etc.)
N/A. It's just a validation condition
> Add if validation to retrieval tool

- DocSum/docker_compose/intel/cpu/xeon/compose_tgi.yaml
Fix #1991
Fix #1991 
No
Local test passed.
> Fix TGI image HF_TOKEN environment variable rename

- SearchQnA/Dockerfile
- SearchQnA/docker_image_build/build.yaml
- SearchQnA/tests/test_compose_on_gaudi.sh
- SearchQnA/tests/test_compose_on_rocm.sh
- SearchQnA/tests/test_compose_on_xeon.sh
- SearchQnA/tests/test_compose_vllm_on_rocm.sh
[CICD enhance] SearchQnA run CI with latest base image, group logs in GHA outputs.
> [CICD enhance] SearchQnA run CI with latest base image, group logs in GHA outputs.

- Text2Image/tests/test_compose_on_gaudi.sh
- Text2Image/tests/test_compose_on_xeon.sh
- Translation/Dockerfile
- Translation/docker_image_build/build.yaml
- Translation/tests/test_compose_on_gaudi.sh
- Translation/tests/test_compose_on_rocm.sh
- Translation/tests/test_compose_on_xeon.sh
- Translation/tests/test_compose_vllm_on_rocm.sh
1. Translation run CI with latest base image, group logs in GHA outputs.
2. Text2Image group logs in GHA outputs.
> [CICD enhance] run CI with latest base image, group logs in GHA outputs.

- AgentQnA/README.md
- AgentQnA/docker_compose/intel/hpu/gaudi/compose.telemetry.yaml
- AgentQnA/tests/test_compose_on_gaudi.sh
1. Add validated matrix for AgentQnA
2. Optimize test scripts
> Add validated matrix for AgentQnA

- DocSum/benchmark_docsum.yaml
- benchmark.py
* Fixes how dataset parameters are added to run yaml
This fixes how dataset parameters are added to the run YAML. Previously, it worked only if the dataset parameter was a string. Now, it works with a list, which was the original intent.
'n/a'
- [ x] Bug fix (non-breaking change which fixes an issue)
- None
Tested with both bench_target options and multiple different datasets with bench_target: ["docsumbench"]
> [DocSum] Fix dataset addition to run yaml

- .github/workflows/daily-update-vllm-version.yml
Update Pull Request handling in vllm daily update workflow
> Update Pull Request handling in vllm daily update workflow

- AudioQnA/Dockerfile.openEuler
- AudioQnA/docker_compose/intel/cpu/xeon/compose_openeuler.yaml
- AudioQnA/docker_image_build/build.yaml
- AudioQnA/tests/test_compose_openeuler_on_xeon.sh
- AudioQnA/ui/docker/Dockerfile.openEuler
openEuler is an open source OS run by the OpenAtom Foundation that builds a global community to enhance digital infrastructure and support diverse architectures.
This PR adds support for openEuler-based container images to AudioQnA by introducing Dockerfiles that use openEuler as the base image instead of the current Ubuntu/Alpine base images.
**Benefits of this change**:
- Provides alternative base image option for users preferring openEuler ecosystem
- Enhances compatibility with openEuler-based Kubernetes clusters
- Supports diverse enterprise environments that standardize on openEuler
- Maintains feature parity with existing images while offering different base OS option
The changes include:
- New Dockerfiles using openEuler base images for core AudioQnA components
- Updated package …
> Add openEuler support for AudioQnA

- AudioQnA/docker_compose/intel/cpu/xeon/compose_openeuler.yaml
- ChatQnA/docker_compose/intel/cpu/xeon/compose_openeuler.yaml
- CodeGen/docker_compose/intel/cpu/xeon/compose_openeuler.yaml
This PR updates the `vllm-service` configuration in the Docker Compose files for the `AudioQnA`, `ChatQnA`, and `CodeGen` services. The main changes are upgrading the `vllm-cpu` image version and removing the unnecessary `privileged: true` flag from the service definitions.
**vllm-service configuration updates:**
* Upgraded the `vllm-service` Docker image from `openeuler/vllm-cpu:0.9.1-oe2403lts` to `openeuler/vllm-cpu:0.10.1-oe2403lts` in `AudioQnA`, `ChatQnA`, and `CodeGen` Compose files. [[1]](diffhunk://#diff-aee097a386cdc15bb4841ba8132893e016f9401de43b2cce41bc07a65af9a761L28-L35) [[2]](diffhunk://#diff-e433e1ddf46d184b769dbd1b667e380933766341e09d06a0d4ebe35364794ac3L91-L98) [[3]](diffhunk://#diff-0f41d99452a1be6ae3e6ae84f6f1f2efad9b876060cadf09c98548b3e6b1d1a6L7-L14)
* Removed the …
> Bump the version of `openeuler/vllm-cpu` to 0.10.1

- ChatQnA/kubernetes/helm/cpu-openeuler-values.yaml
This PR adds a new Helm values file, `cpu-openeuler-values.yaml`, to configure the ChatQnA deployment for openEuler compatibility. The file sets image tags and repositories for all enabled services to use openEuler-specific images and versions.
openEuler compatibility configuration:
* Added `cpu-openeuler-values.yaml` with overrides to set all main and subchart image tags to `latest-openeuler` for openEuler support.
* Configured the `vllm` service to use the `openeuler/vllm-cpu` image with a specific tag and set the LLM model to `meta-llama/Meta-Llama-3-8B-Instruct`.
* Updated the `teirerank` service to use the `openeuler/text-embeddings-inference-cpu` image with an openEuler-specific tag.
* Ensured all other enabled services (`data-prep`, `retriever-usvc`, `tei`, `nginx`, `chatqna-ui`) …
> Add openEuler Helm values for ChatQnA

- AgentQnA/docker_compose/intel/hpu/gaudi/compose.yaml
- AgentQnA/docker_image_build/build.yaml
- AgentQnA/tests/step1_build_images.sh
- CodeGen/docker_compose/intel/hpu/gaudi/compose.yaml
- CodeGen/docker_image_build/build.yaml
- CodeGen/tests/test_compose_on_gaudi.sh
- CodeTrans/docker_compose/intel/hpu/gaudi/compose.yaml
- CodeTrans/docker_image_build/build.yaml
- CodeTrans/tests/test_compose_on_gaudi.sh
- DocSum/docker_compose/intel/hpu/gaudi/compose.yaml
- DocSum/docker_image_build/build.yaml
- DocSum/tests/test_compose_on_gaudi.sh
- VisualQnA/docker_compose/intel/hpu/gaudi/compose.yaml
- VisualQnA/docker_image_build/build.yaml
- VisualQnA/tests/test_compose_on_gaudi.sh
Use built image opea/vllm-gaudi:1.4 for AgentQnA, CodeGen, CodeTrans, DocSum and VisualQnA.
> Use built image opea/vllm-gaudi:1.4 for AgentQnA, CodeGen, CodeTrans, DocSum and VisualQnA.

- DBQnA/docker_compose/amd/gpu/rocm/README.md
- DBQnA/docker_compose/amd/gpu/rocm/compose.yaml
- DBQnA/docker_compose/intel/cpu/xeon/README.md
- DBQnA/docker_compose/intel/cpu/xeon/compose.yaml
- DBQnA/docker_image_build/build.yaml
- DBQnA/tests/test_compose_on_rocm.sh
- DBQnA/tests/test_compose_on_xeon.sh
- DBQnA/ui/react/src/App.test.tsx
- DBQnA/ui/react/src/components/DbConnect/DBConnect.tsx
The deprecated Text2SQL microservice is being replaced by Text2Query, and we are currently porting DBQnA to the new service.
> Porting DBQnA to Text2Query
